### ISSUE TITLE
Behavior for custom fields

### ISSUE THREAD

**Issue by fcabaud** [maxtepkeev/python-redmine#100]
Hello

  Firstly, I would like to say:

- I'm happy with this usefull python module.
- Thanks for this work

  I have a strange behavior with this line
project.issues.get(issue_id).custom_fields

  For one issue I got the list of custom field.
  For another issue I got "AttributeError" exception.

  **both issues belongs to the same project and have the same custom field list**

  Any Idea ?

Thanks

**Comment by maxtepkeev** [comment]
Hi,

It's impossible to say where the problem is without seeing your code and your issue's data.

Can you please give me the code to reproduce the error, not just this line but at least 5-7 lines before and 5-7 lines after this line. I also need the full traceback and please give me the dump of your 2 issues, you can do that with ``list(project.issues.get(issue_id))``

After that I can try to reproduce the error and see where the problem is.

**Comment by fcabaud** [comment]
Please find below a simple code.
On the 10th line project.issues.get(57474) produced an exception.
both issues 61680 and 57474 belong to the same project and have the same custom fields

from redmine import Redmine
server = 'https://private-url.com'
key = "2398472394872349328742938"  
project = "project"
red = Redmine(url = server, key = key, project = project)
project = red.project.get('project')
a = project.issues.get(61680).custom_fields
list(project.issues.get(61680))
project.issues.get(57474)
list(project.issues.get(57474))
a = project.issues.get(57474).custom_fields

Traceback (most recent call last):
  File "D:\utils_redtools.evm\src\redtools\custProblem.py", line 10, in <module>

    list(project.issues.get(57474))
**TypeError: 'NoneType' object is not iterable**

**Comment by fcabaud** [comment]
Sorry I Closed the issue by error. I still need help...

**Comment by maxtepkeev** [comment]
It looks like ``project.issues.get(57474)`` returns ``None``, meaning python-redmine can't find an issue with id 57474 in your result set. Maybe this issue has a ``closed`` status ? Because ``project.issues`` returns only open issues by default.

**Comment by fcabaud** [comment]
Yes this issues has a closed status.
"Because project.issues returns only open issues by default."
  -> How can I get custom fields of a closed status ?

**Comment by maxtepkeev** [comment]
It's not a problem with a custom fields of an issue. ``project.issues`` returns only issues with an ``open`` status, i.e. you just don't receive issues with ``closed`` status at all using ``project.issues``. This is the default behaviour of Redmine API and Python Redmine just respects it.

So if you want to get all issues for a project, currently the only way to do it is like this:

```python
project = red.project.get('project')
issues = red.issue.filter(project_id=project.id, status_id='*')
```

**Comment by fcabaud** [comment]
Thank you very much. It works now.
Merci beaucoup.
