### ISSUE TITLE
create issue redmine 3.0.3

### ISSUE THREAD

**Issue by ilvalle** [maxtepkeev/python-redmine#101]
I got an exception running both
```
redmine = Redmine('...', username='...', password='...')
issue = redmine.issue.create(project_id='temsbvt', subject='Test 1')

issue = redmine.issue.new()
issue.project_id = 'temsbvt'
issue.subject = 'Test 1'
issue.save()
```
I've checked and the project_id, username and password are correct because I can see and filter issues.
The exception
```
Traceback (most recent call last):
  File "C:\Users\ValleriP\workspace\Dbchecker\edifact_checker.py", line 59, in <module>
    issue = redmine.issue.create(project_id='temsbvt', subject='Test 1')
  File "C:\Python27\lib\site-packages\redmine\managers.py", line 180, in create
    response = self.redmine.request('post', url, data=data)
  File "C:\Python27\lib\site-packages\redmine\__init__.py", line 128, in request
    raise JSONDecodeError(response)
redmine.exceptions.JSONDecodeError: Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was
```
using redmine-3.0.3 - python-redmine-1.2.0

**Comment by maxtepkeev** [comment]
The exception says ``Unable to decode received JSON, you can inspect exception's "response" attribute to find out what the response was``.

1) Have you tried inspecting exception's ``response`` attribute, specifically, ``response.text``, to see what is returned as the response ?
2) Have a look at [this](http://python-redmine.readthedocs.org/faq.html#create-update-delete-resource-operations-doesn-t-work). Maybe this is what you're dealing with ?

**Comment by ilvalle** [comment]
Hi @maxtepkeev, sorry for the late answer.
redmine runs on http, no https.
response.text contains a html page where the title is 'Check Point UserCheck'

**Comment by ilvalle** [comment]
sorry, I've just figured out that is the company firewall blocking my request.
