### ISSUE TITLE
Getting Closed Issues

### ISSUE THREAD

**Issue by beltsonata** [maxtepkeev/python-redmine#102]
Apologies if I've missed it, but I can't work out how to get *all* issues from a Redmine project. I can only get non-closed ones.

I've been reading python-redmine.readthedocs.org/resources/issue_status.html but I'm afraid I don't understand it. 

Could you please help? :)

**Comment by loechel** [comment]
Hi,

you look at the wrong resource: 
http://python-redmine.readthedocs.org/resources/issue.html#filter

issues = redmine.issue.filter(project_id='project', **status_id='*'**)

**Comment by beltsonata** [comment]
Fantastic! Thank you very much.

**Comment by maxtepkeev** [comment]
@loechel Thanks!
