### ISSUE TITLE
Delete a parent_issue_id in a issue

### ISSUE THREAD

**Issue by kelupa** [maxtepkeev/python-redmine#103]
Hi:
If you have a issue that have a parent issue and I want delete it (parent issue relationship). How can I do that?

Is It possible put 

issue.parent_issue_id = 0
¿?

thanks.

**Comment by maxtepkeev** [comment]
Hi,

Sorry for the delay with reply, I was at the EuroPython conference for a week. I can't test this right now, but have you tried setting it to ``None`` ?

**Comment by kelupa** [comment]
It woks with ''

**Comment by kelupa** [comment]
It woks with
```python
 myissue.parent_issue_id = ''
```

**Comment by maxtepkeev** [comment]
Hi,

I finally had a chance to try. It works with ``None`` also which is more intuitive than using just ``''``.
