### ISSUE TITLE
Get project issue categories

### ISSUE THREAD

**Issue by vrcmarcos** [maxtepkeev/python-redmine#105]
Hi,

I'm trying to fetch project specific issue categories, but I can't loop through the resultset. I follow these steps:

1. Fetch a redmine project
2. Set a variable with redmine_project.issue_categories
3. Try to loop through the variable

Here's an ipdb debug session output:
```bash
ipdb> redmine_project.issue_categories
<redmine.resultsets.ResourceSet object with IssueCategory resources>
ipdb> redmine_project.issue_categories[0]
*** ResourceSetIndexError: Resource not available by requested index
```

I've requested the project with the *(include='issue_categories')* flag. 

Can anyone help me, please?

**Comment by maxtepkeev** [comment]
Hi,

It looks like this project doesn't have any issue categories.
If you do ``list(redmine_project.issue_categories)`` you should see an empty list.
Also you can check if a project has any issue categories by issuing a manual request through your webbrowser like this: http(s)://REDMINE_URL/projects/PROJECT.json?include=issue_categories

**Comment by vrcmarcos** [comment]
Hi @maxtepkeev , thank you for your support!

I did the request, and see that the response JSON has no issue category. You're right!

But, when I need to create a Task on Redmine, I need to select a proper value to this *Location* field, that identifies the task current situation.

![screen shot 2015-07-30 at 1 24 00 pm](https://cloud.githubusercontent.com/assets/2333864/8988739/5ef27cce-36be-11e5-8d0d-836dfb30d4a8.png)

But I'm unable to fetch these states. Could you help me with this?

**Comment by maxtepkeev** [comment]
I don't know why it's called location in your Redmine version, but according to html you showed, it seems to be an issue status, so, have you tried ``redmine.issue_status.all()`` - [docs](http://python-redmine.readthedocs.org/resources/issue_status.html#all).

**Comment by vrcmarcos** [comment]
It's because I used Google Translator to translate my pt-BR Redmine to en-US lol.

I can fetch the states with redmine.issue_status.all(). But not every project use all issue statuses. Can I fetch a per-project issue-statuses?

**Comment by maxtepkeev** [comment]
Issue statuses are global, i.e. they are the same for all projects, while issue categories are a per project entity, so no, you can't fetch a per project issue statuses because there is no such thing in Redmine at all.

**Comment by vrcmarcos** [comment]
Oh, my fault!

Thanks for your help, @maxtepkeev !
