### ISSUE TITLE
Cannot get generated Index by Title page

### ISSUE THREAD

**Issue by dlmueller** [maxtepkeev/python-redmine#106]
Let https://redmine.example.com be my Redmine instance and "myproject" the ```project_id``` of my project with a wiki containing at least the page "somepage". With the following code I'm able to get the content of that page using the REST-API (presumably via https://redmine.example.com/projects/myproject/wiki/somepage.json):

```python
from redmine import Redmine
redmine = Redmine("https://redmine.example.com", key = "...")
page = redmine.wiki_page.get("somepage", project_id = "myproject")
``` 

Now Redmine offers two special index pages:
* Index by Title
* Index by Date

### Index by Title

HTML = https://redmine.example.com/projects/myproject/wiki/index
JSON = https://redmine.example.com/projects/myproject/wiki/index.json
XML = https://redmine.itz.uni-halle.de/projects/dienst-email/wiki/index.xml

With ```python-redmine 1.2.0``` on ```Python 2.7.6``` and ```Redmine 2.4.2.stable``` I'm not able to fetch that Index by Title wiki page. Instead I'm getting the following KeyError exception:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/redmine/managers.py", line 127, in get
    return self.resource_class(self, self.retrieve()[0])
  File "/Library/Python/2.7/site-packages/redmine/managers.py", line 71, in retrieve
    if isinstance(response[self.container], dict):
KeyError: 'wiki_page'
```

### Index by Date

HTML = https://redmine.example.com/projects/myproject/wiki/date_index
JSON = *not available on Redmine 2.4.2.stable*
XML = *not available on Redmine 2.4.2.stable*

The JSON/XML versions of that page might be unavailable either with intent or due to a bug. Perhaps that issue is already fixed in newer versions of Redmine. But that's another story ...

**Comment by maxtepkeev** [comment]
Do get all wiki pages for a project use ``filter`` operation, e.g. ``wiki_pages = redmine.wiki_page.filter(project_id='vacation')``, this will return you the result which is returned when you request ``https://redmine.example.com/projects/myproject/wiki/index.json``.

As for the Index by date - it is not supported by Redmine via REST API even in the latest 3.x branch, I have no idea why.

**Comment by loechel** [comment]
Hi @dlmueller,

this is intended behaviour of Redmine, see http://www.redmine.org/projects/redmine/wiki/Rest_WikiPages 

Those are special Template Pages which are no ordinary Wiki Pages
index will give you all Wiki-pages of the Project 
http://demo.redmine.org/projects/demo/wiki/index.json
http://demo.redmine.org/projects/demo/wiki/index.xml
by the way, @maxtepkeev this could be used to make a wiki_page.all function with a required project_id

date_index is a special page without json or xml support and will throw an error
http://demo.redmine.org/projects/demo/wiki/date_index.json
http://demo.redmine.org/projects/demo/wiki/date_index.xml

**Comment by maxtepkeev** [comment]
@loechel ``index`` can already be accessed via ``redmine.wiki_page.filter(project_id=PID)``, I really don't see a reason to implement an ``all()`` method with a required ``project_id`` arg, because it will just duplicate the ``filter()`` method. Also the purpose of ``all()`` method is to be executed without any required arguments and your suggestion will conflict with the current ideology.

**Comment by dlmueller** [comment]
@maxtepkeev, thank you for the explanations. Now I'm able to solve my problem. This tool is REALLY great work!
