### ISSUE TITLE
Unable to set enabled_modules on newly created project

### ISSUE THREAD

**Issue by Boldie** [maxtepkeev/python-redmine#107]
I got a problem while trying to set the enabled_modules field on a newly created project (using rm..project.new()):

      File "./redmineServerCopy.py", line 155, in doTransscription
        proj.enabled_modules = [u'issue_tracking']
      File "/usr/local/lib/python2.7/dist-packages/redmine/resources.py", line 200, in __setattr__
        raise ReadonlyAttrError
    redmine.exceptions.ReadonlyAttrError: Can't set read only attribute

The API shows me this should be possible: http://www.redmine.org/projects/redmine/wiki/Rest_Projects

PS: The rest of the lib is cool :)

**Comment by maxtepkeev** [comment]
Hi Sven,

``enabled_modules`` is a read-only attribute, you should use ``enabled_module_names`` to set new modules for the project, see example in the [docs](http://python-redmine.readthedocs.org/en/latest/resources/project.html#new), also this is exactly how Redmine itself is doing it (see the [link](http://www.redmine.org/projects/redmine/wiki/Rest_Projects) you posted).

**Comment by maxtepkeev** [comment]
I believe this can be closed.
