### ISSUE TITLE
How to find out the parent id of a project

### ISSUE THREAD

**Issue by ariwk** [maxtepkeev/python-redmine#110]
It is possible to update or set it while creation but redmine.project.all() or redmine.project.get() does not support that king of information.
I really appreciate any help

**Comment by maxtepkeev** [comment]
If an issue has a parent issue, it will be available through the ``parent`` attribute, please see more details in [this](https://github.com/maxtepkeev/python-redmine/issues/27#issuecomment-39309674) answer.

**Comment by maxtepkeev** [comment]
Oh sorry, you were asking about the project and not about the issue, but anyway, the answer stays the same, if a project has a parent project, it will be available through the ``parent`` attribute.

**Comment by ariwk** [comment]
Thanks! it works as expected. 
Could you update the documentation please? It would be nice to find the approach over there.
In the meantime, thank you so much for your really good job in here!

**Comment by maxtepkeev** [comment]
You're welcome. I updated my TODO list to make a doc update about that.
