### ISSUE TITLE
Bundled requests library lacks cacerts.pem, every SSL verification fails when certifi is not installed

### ISSUE THREAD

**Issue by languitar** [maxtepkeev/python-redmine#114]
The requests library usually contains a `cacert.pem` file with trusted root certificates from Mozilla [1]. The version bundled in this library does not contain this file and hence every certificate verification fails, except the certifi package is installed.

[1] http://docs.python-requests.org/en/latest/user/advanced/#ca-certificates

**Comment by maxtepkeev** [comment]
Yes, this is a known problem. It was already discussed in-depth in #109. The fix is coming, currently ``pip install certifi`` is the best available option for https requests. Closing this in favour of #109.
