### ISSUE TITLE
Is it possible to upload files to a wiki page?

### ISSUE THREAD

**Issue by tibaldo** [maxtepkeev/python-redmine#115]
I can do it for an issue, but not for a wiki page (using redmine 1.4.0 from python2.7 anaconda distribution). If it is possible could you please provide example code? Otherwise would you consider to add this feature to a next release? That would be extremely helpful.

**Comment by maxtepkeev** [comment]
Yes, this is currently not possible, but it shouldn't be hard to implement. I'll try to do this on the weekends.

**Comment by maxtepkeev** [comment]
Implemented in v1.5.0
