### ISSUE TITLE
Upload files to Files

### ISSUE THREAD

**Issue by Farkal** [maxtepkeev/python-redmine#117]
This an enhancement and would be very nice because today I am obliged to use a script with selenium to upload my files :disappointed:

**Comment by maxtepkeev** [comment]
Unfortunately there is no API for that in Redmine, but I'll see if it's possible to implement such functionality without API, e.g. via raw POST requests or something like that.

**Comment by Farkal** [comment]
Ok thank you very much :smile:

**Comment by rapedme** [comment]
I found simple file uploader,
but, not support version_id and tooltip (with redmine 3.x)
https://github.com/gertvdijk/redmine-file-uploader

**Comment by maxtepkeev** [comment]
@rapedme Thx, I'll have a look at it.

**Comment by maxtepkeev** [comment]
It looks like there will be an API available in Redmine 3.4 for this. So let's wait for the official release and then add support for this API to Python-Redmine.

**Comment by maxtepkeev** [comment]
Added in d98864bedeee25e79f0e23161af76ae9f3ba0169. Will be part of the upcoming 2.1.0 release.
