### ISSUE TITLE
File called redmine.py

### ISSUE THREAD

**Issue by samsalas** [maxtepkeev/python-redmine#118]
I was wondering why the simple "from redmine import Redmine" doesn't work....

It is because I called my file "redmine.py". So for your information, do not call your file "redmine.py" when using the redmine package. Maybe you can add this in the "conflict" instructions.

**Comment by maxtepkeev** [comment]
Actually, this isn't related to python-redmine. This is how Python module imports work, you can read about absolute/relative imports and PYTHONPATH to get a general idea about all this stuff.

Anyway thanks for this issue, I'm sure it will help someone else having the same problem.
