### ISSUE TITLE
No documentation on journals (issue comments)

### ISSUE THREAD

**Issue by pfctdayelise** [maxtepkeev/python-redmine#120]
Firstly, I just wanted to say this library is a real pleasure to use. So thanks for that.

The only problem I encountered is that it was difficult to figure out how to access the issue comments, I found there is a resource called 'Journal' which is the comments, but it is not well documented like the other resources.

Cheers for making such a nice well-documented lib!

**Comment by maxtepkeev** [comment]
Agree, thanks for raising this issue. Will do that ASAP.

**Comment by Heilage** [comment]
Any progress on these docs? I'm currently trying to add new journals to an issue, but the new() operation doesn't seem to be supported (or I'm doing something wrong).

**Comment by maxtepkeev** [comment]
Yes, I'm preparing for v2.0.0 release which will include updated docs. But basically IssueJournal resource is just a wrapper, it doesn't have any standard methods, e.g. new(), filter() etc. If you want to add new journals just use ``redmine.issue.update(ISSUE_ID, notes='blah')`` that's it

**Comment by maxtepkeev** [comment]
This information was added to the new docs that will be available together with v2.0.0 in the end of March.
