### ISSUE TITLE
return 0 for empty custom field values

### ISSUE THREAD

**Issue by andrew-klepcha** [maxtepkeev/python-redmine#122]
I use version 1.5.0 of python-redmine. A problem appeared after I added some custom fields to existing tasks in Redmine. These are list-type fields. When I am trying to update an issue (for other fields, not for the newly created ones), a Validation Error for issue.save() appears .
As a workaround, I changed all custom fields that == 0 to an empty string.
I think that changing "return 0" to "return ''" (empty string) in redmine/resources.py:850 may help.

**Comment by maxtepkeev** [comment]
Hi,

Sorry for making you wait for so long for the response.

I believe that if there is such a bug it depends on the Redmine version being used, I wan't able to reproduce it with Redmine 3.2.0.

Can you please tell me what Redmine version do you use ?

**Comment by maxtepkeev** [comment]
It seems that this was only possible for Redmine < 2.5.0.

Your proposed solution is now used in v1.5.1. Thanks.
