### ISSUE TITLE
get browser URL for any object

### ISSUE THREAD

**Issue by dpocock** [maxtepkeev/python-redmine#124]
It would be useful if every object had a method to obtain the URL for viewing the object in Redmine from a browser

**Comment by maxtepkeev** [comment]
Almost (because it doesn't make sense for all objects) every resource object already provides a url property for this, e.g. ``project.url``, ``issue.url`` etc. Does that cover your needs or you need something different

**Comment by dpocock** [comment]
OK, I hadn't seen that when inspect an object with ```vars(issue.project)```

I notice that if I invoke ```issue.project.url``` it returns a URL with the project ID rather than the ```project.identifier``` string, could that be changed?  The identifier is better for clean URLs.

**Comment by maxtepkeev** [comment]
Agree, will fix this ASAP.

**Comment by maxtepkeev** [comment]
Fixed in v1.5.1
