### ISSUE TITLE
Invalid authentification ?

### ISSUE THREAD

**Issue by rgarrigue** [maxtepkeev/python-redmine#127]
Hi

I'm trying to get a list of project whose custom field "kanboard id" isn't null. Since there's no filter for project I'm looping over all project when I hit a "redmine.exceptions.AuthError: Invalid authentication details".

I don't get it, I'm connected with an admin account, I can get a specific project and display its identifier.

Is there some restriction I should be aware about your python API, or redmine's API ?

Here's my `testRedmine.py` code in case it might help

    from redmine import Redmine
    import json

    #redmine = Redmine('http://redmine', key="16e9ceee9df21360e8e8c1a695c27316edd1339", version = "3.2.0")
    redmine = Redmine('http://redmine', username="bid", password="bid", version = "3.2.0")

    if redmine.auth():
        print "Redmine OK"
    else:
        print "Redmine KO"
        exit

    project = redmine.project.get('equipe-support-technique')
    print project
    pall = redmine.project.all()
    print pall

    for p in pall:
        print p.id
        print p.identifier

And the output

    Redmine OK
    Equipe Support technique
    <redmine.resultsets.ResourceSet object with Project resources>
    Traceback (most recent call last):
      File "testRedmine.py", line 19, in <module>
        for p in pall:
      File "/usr/lib/python2.7/site-packages/redmine/resultsets.py", line 102, in __iter__
        self._evaluate()
      File "/usr/lib/python2.7/site-packages/redmine/resultsets.py", line 81, in _evaluate
        offset=self.manager.params.get('offset', self.offset)
      File "/usr/lib/python2.7/site-packages/redmine/managers.py", line 62, in retrieve
        response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
      File "/usr/lib/python2.7/site-packages/redmine/__init__.py", line 132, in request
        raise AuthError
    redmine.exceptions.AuthError: Invalid authentication details

**Comment by maxtepkeev** [comment]
Hi

No, there're no limits or restrictions of that kind neither in python-redmine nor in Redmine API.

Are you able to retrieve a list of projects from a web browser going to http://your-redmine-url/projects.json?limit=100 ?

**Comment by rgarrigue** [comment]
Hi again

I found out the reason for this issue. We're using redmineCRM's favorite projects plugin, which is doing a redirection that screw up with authentification. Session's still here, but user switch to anonymous, thus no project listed...

So nevermind, sorry for the disturbance.

**Comment by kuthoong** [comment]
I enabled Enable REST web service in `/settings?tab=api` and it worked.
