### ISSUE TITLE
Getting all the users in Redmine

### ISSUE THREAD

**Issue by SQA777** [maxtepkeev/python-redmine#128]
Hello.

I tried this package (python-redmine) and pyredmine.  pyredmine references less objects than python-redmine but pyredmine has a useful feature.  It has a "users" object, which lists all the users in Redmine, not just the users attached to a project.

Is there anything like this in python-redmine?

**Comment by maxtepkeev** [comment]
Hi,

Please read the (docs)[http://python-redmine.readthedocs.org/resources/user.html#all] before posting questions. It's all there.

Thanks.

**Comment by SQA777** [comment]
Max, Sorry about that.  I found the answer on Friday.   Should have closed this issue out.

**Comment by maxtepkeev** [comment]
No problem. Glad you figured it out.
