### ISSUE TITLE
Getting the permissions for roles

### ISSUE THREAD

**Issue by SQA777** [maxtepkeev/python-redmine#129]
I am able to get all the "roles" for the Redmine we are using.

However, for each role, there is only an ID and a name.  Are permission attributes not supported in the Role object in python-redmine?

**Comment by maxtepkeev** [comment]
Hi,

``redmine.role.all()`` returns you all the available roles in Redmine with only ``id`` and ``name`` attributes. If you need to get each role's permissions you have to do this:

```python
roles = redmine.role.to_resource_set([role.refresh() for role in redmine.role.all()])
```

``refresh()`` method on the role resource is a convenient shortcut to ``redmine.role.get(ROLE_ID)``, that means that to get each role's permissions you have to make a separate request to Redmine for each role. This is not a python-redmine's limitation, this is how Redmine's REST API works and there is nothing we can do about that.

Hope that helps.

**Comment by SQA777** [comment]
Max,

Thanks for the answer.  I used the code that you listed and for "roles", it is a list with all the permissions.  The permissions are just Unicode strings.

So, if I wanted to add/delete a "permission", is it just appending/removing the "permission" from the "roles" list?

Example:

# To add
roles.append('edit_project')

# To delete
roles.remove('edit_project')

**Comment by maxtepkeev** [comment]
If you want to add/edit/remove new roles to/from Redmine - you can't, because there is no API for that in Redmine, you can only read roles through API (like I explained above) and add/edit/delete them through Redmine's admin interface.

If you're talking about adding/removing users with roles to/from some project - there is a ProjectMembership resource for that. Here are the [docs](http://python-redmine.readthedocs.org/resources/project_membership.html).

**Comment by SQA777** [comment]
Max,

For what I need to do (make Redmine read-only for part of the day), I can't add/remove uesrs to/from a project.  If I remove a user from a project, they have no visibility about the project.  During a read only period, I want the user to be able to "view" things but not edit/create/delete things.

I suppose I can get all the users of a project and get the roles for each user.

Then I can create dummy roles --> for example, have a role called "manager" and another one called "manager_readonly" and use the ProjectMembership APIs to delete a user/role and then add the user back to the project with different roles.  

I'll look into that.

**Comment by maxtepkeev** [comment]
Yes, you need to create dummy read only roles via Redmine's admin interface, then you need to get their ID's via ``redmine.role.all()``, then you need to iterate through all you projects, get all the memberships of a project and for each membership change role to the needed read-only role, for example:

```python
projects = redmine.project.all()

for project in projects:
    for membership in project.memberships:
        membership.role_ids = [NEEDED_READ_ONLY_ID1, NEEDED_READONLY_ID2]
        membership.save()
```

I haven't tested this code but I believe it should work or at least give you an idea about what to do.

**Comment by maxtepkeev** [comment]
Can we close this or you still need some help ?

**Comment by maxtepkeev** [comment]
Looks like we can close this.
