### ISSUE TITLE
Cannot get fixed versions on project

### ISSUE THREAD

**Issue by amazpyel** [maxtepkeev/python-redmine#130]
I'm trying to get a list of project fixed versions:

```python
>>> from redmine import Redmine
>>> redmine = Redmine(url='some url', key='api key', requests={'verify': False})
>>> project = redmine.project.get('project_name')
>>> project.versions
<redmine.resultsets.ResourceSet object with Version resources>

>>> project.versions[0]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\MyEnvs\youtrack2redmine\lib\site-packages\redmine\resultsets.py", line 93, in __getitem__
    return next(itertools.islice(self, item, item + 1))
  File "C:\MyEnvs\youtrack2redmine\lib\site-packages\redmine\resultsets.py", line 102, in __iter__
    self._evaluate()
  File "C:\MyEnvs\youtrack2redmine\lib\site-packages\redmine\resultsets.py", line 81, in _evaluate
    offset=self.manager.params.get('offset', self.offset)
  File "C:\MyEnvs\youtrack2redmine\lib\site-packages\redmine\managers.py", line 62, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "C:\MyEnvs\youtrack2redmine\lib\site-packages\redmine\__init__.py", line 149, in request
    raise UnknownError(response.status_code)
UnknownError: Redmine returned unknown error with the code 406
```

Is it correct usage of API?

**Comment by maxtepkeev** [comment]
Hi,

I can't reproduce this issue here, tried with several Redmine versions and everything works perfectly.

Do you have this problem only with project versions ?
What Redmine version and python-redmine versions do you use ?

**Comment by amazpyel** [comment]
Hi Max, 

Well, I guess it's a redmine issue because /projects/foo/versions.xml returns me an error message:

> This page contains the following errors:
>error on line 1 at column 1: Extra content at the end of the document
>Below is a rendering of the page up to the first error.

I don't know how to find out redmine version and I've installed python-redmine by means pip.

**Comment by maxtepkeev** [comment]
You can see Redmine version visiting http(s)://YOUR_REDMINE_URL/admin/info
You can get python-redmine version doing ``pip list | grep redmine`` or from python:

```python
from redmine import __version__
print __version__
```

**Comment by amazpyel** [comment]
Thank you,

Redmine version: 2.6.9.stable
python-redmine version 1.5.1

**Comment by maxtepkeev** [comment]
Everything should work fine with these versions.

Can you check that REST API is enabled visiting ``http(s)://YOUR_REDMINE_URL/settings?tab=api``. If it's not enable it, restart Redmine just in case and after that please visit ``http(s)://YOUR_REDMINE_URL/projects/YOUR_PROJECT/versions.json``. You should see versions in JSON format, if it's still not working - show me what output you get.

**Comment by amazpyel** [comment]
> Can you check that REST API is enabled visiting http(s)://YOUR_REDMINE_URL/settings?tab=api
Unfortunately, I don't have such tab :) 

> http(s)://YOUR_REDMINE_URL/projects/YOUR_PROJECT/versions.json

Blank page displayed though. But I can get issue.json, for example. 

Well, I need a list of fixed versions so do not need to hardcode versions id. Currently, I'm using hardcode approach.

**Comment by maxtepkeev** [comment]
> > Can you check that REST API is enabled visiting http(s)://YOUR_REDMINE_URL/settings?tab=api

> Unfortunately, I don't have such tab :) 

Can you manually check if REST API is enabled visiting Administration -> Settings -> Authentication then.

**Comment by amazpyel** [comment]
@maxtepkeev "Enable REST web service" option enabled.

**Comment by maxtepkeev** [comment]
That's weird. It should work. It's definitely a problem on Redmine side and I have no more ideas what you can do to resolve this issue, so the only thing I can recommend is to start an issue on the Redmine forum, also check Redmine logs maybe you'll see the problem in there.

Sorry that I can't help you more. Also if you figure out the issue, it would be great if you post the solution here, because that may help somebody with the same problem in the future.

**Comment by maxtepkeev** [comment]
Forgot to mention. If you have some webserver in front of the Redmine, e.g. nginx, lighttpd or whatever, it may strip out some headers, if misconfigured, and cause the problem you're experiencing. Try to run Redmine via Webrick (built-in Redmine webserver) and see if that resolves the issue

**Comment by amazpyel** [comment]
Thank you for your time and clarification!

**Comment by amazpyel** [comment]
Issue resolved. It was not even an issue of the Redmine. It was an issue in redmine plugin which operates fixed versions. :(

**Comment by maxtepkeev** [comment]
Glad you resolved the issue.

Can you please elaborate on what exactly was the problem and how you fixed it. I'm asking because AFAIK fixed versions are built-in inside Redmine and aren't provided by a plugin. So it would be great if you could give a little bit more information.

**Comment by amazpyel** [comment]
Unfortunately, I can't explain what exactly was a problem because I'm not an admin of redmine instance (other person handle it). Admin told me that it was a problem with Redmine plugin which interacts with fixed version and this plugin does not return version by api accidently.
