### ISSUE TITLE
Support for custom fields in time entry

### ISSUE THREAD

**Issue by Dark-Passenger** [maxtepkeev/python-redmine#134]
Hi how do i handle custom fields while creating a new time entry

Currently if I pass the Custom field name in create function as a keyword argument it gives me a validation error that it needs a value(the custom field is compulsory).

**Comment by maxtepkeev** [comment]
Hi, don't have time to test right now, but should be the same as for issues, e.g.:

```python
issue = redmine.issue.create(
    project_id='vacation',
    subject='Vacation',
    custom_fields=[{'id': 1, 'value': 'foo'}, {'id': 2, 'value': 'bar'}]
)
```

**Comment by Dark-Passenger** [comment]
Yup supported. Thanks.
