### ISSUE TITLE
Get budget_hours on subtasks

### ISSUE THREAD

**Issue by Jokerbullot** [maxtepkeev/python-redmine#135]
Hello,

First of all, thanks for your module. It's a pleasure to use.
Second, I'm sorry to post that here. It's more a question than an issue.

Finnaly, my problem : 
I'd like to get the total budget_hours (and spent,remaining,...) of a taks including the all the subtaks budget_hours.

That's what I do : 
```
top_issue = rm.issue.get('443496', include='children')
for subs in top_issue.children:
      print(subs.budget_hours)
```

Unfortunality it dosen't work.

Do we see a way to achieve my goal ?
Is there a parameter to get time directly from the variable issue ?
Is there a way to iterate on childrens to get the budget_hours ?

Regards,
Jkr.

**Comment by maxtepkeev** [comment]
Hi,

Glad you liked the package.

``budget_hours`` isn't a standard attribute, at least not in vanilla Redmine, maybe it's a custom field which was created in your Redmine admin interface, if yes you need to inspect ``subs.custom_fields`` for its existance.

**Comment by Jokerbullot** [comment]
oh ok
Since top_issue.budget_hours works I thought aze.budget_hours souhld works too.


Tyvm Max.

**Comment by maxtepkeev** [comment]
Eh, maybe you have some plugin that is adding ``budget_hours`` to your issues. Also if you say that it works in top_issue than it means that it's just not set in some or all of your sub issues in Redmine, and you can work around that by using ``getattr(subs, 'budget_hours', 0)`` that means that is ``budget_hours`` attribute exists it's value will be returned and if not 0 will be returned.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
