### ISSUE TITLE
Filter operation with no status_id parameter set found no closed issues.

### ISSUE THREAD

**Issue by andrius-momzyakov** [maxtepkeev/python-redmine#136]
I'm using Redmine 2.5.2.
Tried to iterate over all issues for a given project with 
`for issue in rm.issue.filter(project_id='portal'):`
but discovered that it returned open issues only.
In Docs it's not clear, which status or statuses are used by default in the above case.
Using 
`for issue in rm.issue.filter(project_id='portal', status_id='*'):`
worked as approriate for me.

**Comment by maxtepkeev** [comment]
Yeah I know, actually python-redmine just uses default Redmine API behaviour, and it returns only open issues by default. But I agree that docs need a bit of clarification. Thanks for raising this issue.

**Comment by maxtepkeev** [comment]
This information was added to the new docs that will be available together with v2.0.0 in the end of March.
