### ISSUE TITLE
I just want to get activities of each project? I don't konw how to do?

### ISSUE THREAD

**Issue by flexiwind** [maxtepkeev/python-redmine#137]
the activities like this:
today
05:33 Defect #23190 (New): rma
jamel mack

2016-06-28
22:58 Defect #23175 (Resolved): Ticket overview table on project page (from 3.2) exposes
Glad that it works as needed, thanks for the fast feedback. Jean-Philippe Lang

22:55 Defect #23175: Ticket overview table on project page (from 3.2) exposes trackers to user roles wi...
Alright, tested the new 3.3 release and as you said, the issue is fixed there.
Thanks and nevermind. Tobias Fischer
how to get those info??

**Comment by flexiwind** [comment]
the activities like this:
    today
    05:33 Defect #23190 (New): rma
        jamel mack
    2016-06-28
    22:58 Defect #23175 (Resolved): Ticket overview table on project page (from 3.2) exposes       
      Glad that it works as needed, thanks for the fast feedback. Jean-Philippe Lang
    22:55 Defect #23175: Ticket overview table on project page (from 3.2) exposes trackers to user      roles wi...
       Alright, tested the new 3.3 release and as you said, the issue is fixed there.
       Thanks and nevermind. Tobias Fischer
how to get those info??

**Comment by flexiwind** [comment]
thank you for yours reply：
I have seen the docs before，there is a picture may express what i want。

![issue_picture](https://cloud.githubusercontent.com/assets/17748188/16474178/0c3452ae-3ea7-11e6-81b0-0c02b3de3d1f.png)

**Comment by maxtepkeev** [comment]
I understand what you want, but I can't write the code for you, it doesn't work this way, you have to read the docs and try something and if you can't figure it out then you have to show what you tried (your code) and I can tell you what you're doing wrong. I may give you a hint though. What you want is called issue journals, so:

```python
issue = redmine.issue.get(ISSUE_ID, include='journals')

for record in issue.journals:
    print record.id, record.user, record.created_at
    print record.notes
    print record.details
```

Also see [docs](http://python-redmine.readthedocs.io/resources/issue.html#get).

And no, you can't just get all activities (journals) in one API call, you have to first get all the issues you're interested at, and then for each issue you have to make a separate call with ``include='journals'`` to get it's activities (journals).

**Comment by flexiwind** [comment]
oh...that's it,thank you so much for your answer.
