### ISSUE TITLE
Support for REST API for Search

### ISSUE THREAD

**Issue by freakysheep** [maxtepkeev/python-redmine#138]
In Redmine 3.3.0 REST API for Search was added (http://www.redmine.org/issues/6277). Are you planning to support this (or is it already supported? then some documentation would be helpful).

**Comment by maxtepkeev** [comment]
Yes, I've seen they added that. It's not currently supported, but I have plans to add support for this in python-redmine, but I don't have any ETA, because I'm currently don't have much free time, so as always pull requests are greatly appreciated.

**Comment by maxtepkeev** [comment]
Implemented in 1031909e5ec9e0ddc5587ad87871bf0951cfe385 and will be available in v2.0.0
