### ISSUE TITLE
Req: Ability to set connection timeouts?

### ISSUE THREAD

**Issue by petiepooo** [maxtepkeev/python-redmine#141]
There doesn't seem to be any way to specify a connection or read timeout on any of the requests.  urllib3 has the Timeout utility, and requests accepts a timeout named parameter, but it doesn't seem to be carried out to the Redmine interface.

**Comment by maxtepkeev** [comment]
http://python-redmine.readthedocs.io/configuration.html#connection-options

**Comment by petiepooo** [comment]
Ah.. i'm a fool.  It was staring me in the face too, as I was already using one of the other requests options.

Confirmed as working.  Thanks for your patience..
