### ISSUE TITLE
controlling issue's owner

### ISSUE THREAD

**Issue by yo5191** [maxtepkeev/python-redmine#142]
Hi.
I am using python redmine to make issue and I need a way to control issue's owner.
For my understanding' the only way to control the owner is to access redmine with the user I want to set as owner.

Is there another solution?
Does someone knows how to control issue's owner threw python redmine?

Thanks.

**Comment by maxtepkeev** [comment]
The only solution currently available is to use admin account and [impersonate](http://python-redmine.readthedocs.io/configuration.html#impersonation) as another user that needs to be the author of the issue. There are no other ways as far as I know of at least using vanilla Redmine, maybe there is a plugin for this somewhere...
