### ISSUE TITLE
parent_issue_id has no effect on a new issue

### ISSUE THREAD

**Issue by orlitzky** [maxtepkeev/python-redmine#145]
Hello, I'm probably doing something wrong, but I can't seem to create a new issue with a parent issue. Everything else works fine, but when all of the issues are created, the parent is there, the children are there -- everything's great -- except none of the children have their "Parent task" field set.

First I'm creating the parent issue:

``` python
parent_issue = redmine.issue.create(project_id=project_identifier,
                                    subject=parent_issue_subject,
                                    tracker_id=billing_tracker_id,
                                    assigned_to_id=accountant_id)
print('Created parent issue {:d}.'.format(parent_issue.id))
```

That works great: the new issue looks exactly as expected, and its ID is printed to the console. Then I'm looping through a bunch of objects and creating a child issue for each one:

``` python
child_issue = redmine.issue.create(
                      project_id=project_identifier,
                      subject=issue_subject,
                      tracker_id=billing_tracker_id,
                      description=issue_description,
                      assigned_to_id=accountant_id,
                      parent_issue_id=parent_issue.id)
msg = 'Created child issue {:d} of parent issue {:d}.'
print(msg.format(child_issue.id, parent_issue.id))
```

That also works mostly as expected, **except** that the new child issue doesn't have a parent task set. In other words, it's not a child issue at all, so the parent issue is left sitting there by itself.

This is with redmine-3.2.0 and python-redmine-1.5.1 on python-3.4.3. Any suggestions would be appreciated!

**Comment by maxtepkeev** [comment]
Hi, it looks like you're doing everything properly.

Unfortunately I'm currently on vacation so can't help you with this right now, also I'm sure that setting parent_issue_id worked fine, maybe this is somehow connected with Redmine version that you're using, because if you see the changelog for Redmine 3.3.0 there are some fixes exactly for setting parent id. So if you can you can try to upgrade Redmine for now, it that doesn't help I will be able to figure out where the problem is when I return back from vacation in a week.

**Comment by orlitzky** [comment]
Thanks for the suggestion, I'll try to upgrade Redmine after-hours and see how it goes.

**Comment by orlitzky** [comment]
I just upgraded to redmine-3.3.0, and I'm sorry to say that didn't fix it =)

**Comment by maxtepkeev** [comment]
I've just checked everything under Redmine 3.3.0 and everything works as expected. Can you recheck using http://demo.redminecrm.com ? Login and password is admin.

**Comment by maxtepkeev** [comment]
Hi, any news on this ? Did you figure out the problem ?

**Comment by maxtepkeev** [comment]
Closing this due to the lack of activity. If you still need help please let me know and I'll reopen this issue.

**Comment by orlitzky** [comment]
Oh, sorry! I didn't receive the email notifications for your previous comments. I'll test against the demo instance and see what happens.

**Comment by orlitzky** [comment]
Well, it worked fine on the RedmineCRM demo, so that meant it had to be something specific to our installation. It turns out, the user I was using didn't have the "manage subtasks" permission, and that is necessary for assigning the parent issue id. I've got it working now, thank you.

**Comment by maxtepkeev** [comment]
Ah, permissions... Yes. I'm glad you got it working.

Thanks for returning back with the explanation and solution.

**Comment by miketorrence** [comment]
I'm having the same problem.  I ensured that the user I'm using has proper permissions.  I even tried giving the user admin permissions and no luck, it seems to just be ignoring the parent_issue_id when creating the issue.
