### ISSUE TITLE
Key error when requesting all Issues

### ISSUE THREAD

**Issue by moritzbuck** [maxtepkeev/python-redmine#146]
When trying to get all Issues of my redmine instance I get some error that I really cannot understand, e.g. `[i for i in redmine.issue.all()]`, I get Err: 

```python
/usr/local/lib/python2.7/dist-packages/redmine/managers.pyc in retrieve(self, **params)
     71 
     72             # A single resource was requested via get()
---> 73             if isinstance(response[self.container], dict):
     74                 results = response[self.container]
     75                 total_count = 1
KeyError: 'issues'
```
Also if I try to access issues directly, e.g. `redmine.issue.get(1084)`, I get this : 
```python
/usr/local/lib/python2.7/dist-packages/redmine/__init__.pyc in request(self, method, url, headers, params, data, raw_response)
    145             raise ValidationError(to_string(', '.join(e if is_string(e) else ': '.join(e) for e in errors)))
    146         elif response.status_code == 500:
--> 147             raise ServerError
    148 
    149         raise UnknownError(response.status_code)

ServerError: Redmine returned internal error, perhaps you are doing something wrong
```

even though the `myreadmin.something.wtf/issues/1083` exists....

**Comment by maxtepkeev** [comment]
There is something wrong with your Redmine, because it returns 500 error, did you enable API in admin interface of Redmine ? Also try to request myreadmin.something.wtf/issues/1083.json via browser, you'll probably get 500 error.

**Comment by moritzbuck** [comment]
Thank you I will contact my admin! Regards

**Comment by moritzbuck** [comment]
Thanks, it turned out to be a bug due to some plugin or something, projects where accessible but not issues...

**Comment by maxtepkeev** [comment]
Great, then I believe we can close this.
