### ISSUE TITLE
Creating/saving TimeEntry

### ISSUE THREAD

**Issue by moritzbuck** [maxtepkeev/python-redmine#147]
Sorry, an other short question, I guess it also has to do with our setup but I'll ask anyhow:
I create a new `time_entry` and when I try to save it I get a key error: 
```python
/usr/local/lib/python2.7/dist-packages/redmine/managers.pyc in create(self, **fields)
    194 
    195         try:
--> 196             resource = self.to_resource(response[self.container])
    197         except TypeError:
    198             raise ValidationError('Resource already exists')  # fix for repeated PUT requests

KeyError: 'time_entry'
```
When I look at the relevant `response` I get from our redmine, it is actualle a `time_entries` ressourceSet...

**Comment by maxtepkeev** [comment]
Yes, there is something wrong, when you create a resource, vanilla Redmine returns a single created resource object, so this is definitely somehow connected with your Redmine setup.

**Comment by moritzbuck** [comment]
Arg, sorry for all the trouble, it turned out to be the "s" missing in "https" ...

**Comment by maxtepkeev** [comment]
Ah, yes, we even have an [entry](http://python-redmine.readthedocs.io/faq.html#create-update-delete-resource-operations-doesn-t-work) in FAQ about that.
