### ISSUE TITLE
SNIMissingWarning:

### ISSUE THREAD

**Issue by yo5191** [maxtepkeev/python-redmine#148]
Hi.
I have a script that uses python-redmine.
It worked fine for a month but today it started throwing the following errors:

/usr/local/tools/release/lib/python2.7/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/tools/release/lib/python2.7/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Does anyone have an idea how can I handle it?
I tried to use "requests = {'verify':False}" but it didn't help.

Thanks.

**Comment by yo5191** [comment]
When I use python 3.2 I get the following warnings:
/usr/local/python/python3-release/lib/python3.2/subprocess.py:389: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
/usr/local/python/python3-release/lib/python3.2/site-packages/redmine/packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

**Comment by maxtepkeev** [comment]
This is a warning generated by urllib3 library that is used by requests library that is used by python-redmine. Actually everything is explained in the [link]( https://urllib3.readthedocs.org/en/latest/security.html) that urllib3 shows you, I don't know what else to add to this. Just read it and decide how you're going to handle it. ``requests = {'verify':False}`` won't help because this error basically says that your Python version is insecure and you should upgrade it, so this has nothing to do with any library but with your Python version itself.

And don't use Python 3.2 it's super old, use Python 3.3 at least or better 3.5.

**Comment by yo5191** [comment]
I used urllib3.disable_warnings() and then I got the following error:
[Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.

Then I used "requests = {'verify':False}" and I got the following error:
 resource = self.to_resource(response[self.container])
KeyError: 'issue'

Do you have an idea what can I do to overcome it without upgrading my python?

**Comment by maxtepkeev** [comment]
You said that everything was working for a month and then stopped, that means that something has changed on your system, it was either a python or requests library upgrade, can you try to figure out what has changed ? 

> Then I used "requests = {'verify':False}" and I got the following error:
resource = self.to_resource(response[self.container])
KeyError: 'issue'

Can you give me more information about what were you doing, e.g. show code that is causing this ? If that was a resource create/update operation then the only thing that can cause this behaviour is when you're using http URL but you should have used https and your server does a redirect from http to https and your POST/PUT request is transformed into GET.

**Comment by maxtepkeev** [comment]
Closing this due to the lack of activity. If you still need help please let me know and I'll reopen this issue.
