### ISSUE TITLE
ResourceError when freezed with cxFreeze

### ISSUE THREAD

**Issue by vlegoff** [maxtepkeev/python-redmine#149]
I've tried to use PythonRedmine in a standalone application, built with cxFreeze.  I'm unsure about the nature of the problem, this may also happen because PythonRedmine is executed in a thread.  In all cases, it works perfectly well when in Python.  If I freeze it however, I get the following error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "...\autoupdate.py", line 68, in run
    if self.check():
  File "...\autoupdate.py", line 79, in check
    project = redmine.project.get("cocomud-client")
  File "C:\python27\lib\site-packages\redmine\__init__.py", line 47, in __getatt
r__
    return ResourceManager(self, resource)
  File "C:\python27\lib\site-packages\redmine\managers.py", line 40, in __init__

    raise ResourceError
ResourceError: Unsupported Redmine resource

Python 2.7, latest PythonRedmine.

**Comment by maxtepkeev** [comment]
This has nothing to do with python-redmine, please see issue #139 for the description of the same problem but with pyinstaller, and [here](https://cx-freeze.readthedocs.io/en/latest/faq.html#problems-with-running-frozen-programs) is the information about how to solve this problem for cxFreeze.

**Comment by vlegoff** [comment]
Thanks for the answer.  I had no idea this problem existed.  Perhaps (only perhaps) should a section be included in the documentation to explain this and how to solve it for PythonRedmine (E.G.: what libraries to include in the standalone).

**Comment by maxtepkeev** [comment]
Good idea about mentioning this in the docs. I'll put that in my TODO list.
