### ISSUE TITLE
Creating new issue returns KeyError: 'issue'

### ISSUE THREAD

**Issue by millertime145** [maxtepkeev/python-redmine#150]
I'm having an problem creating a new issue. I'm able to retrieve issues.

Example:
File "post.py", line 22, in
issue = redmine.issue.create(project_id = 1517, subject = 'This is a test', description = 'foo')
File "C:\Python27\lib\site-packages\redmine\managers.py", line 196, in create
resource = self.to_resource(response[self.container])
KeyError: 'issue'

In the managers.py file I added a "print response" after line 193 and before 194 and this returned a bunch of existing issues within project 1517.
Example return:
{u'total_count': 11, u'limit': 25, u'issues': [{.....}]}  
the [{.....}] is the list of existing issues

Any help is greatly appreciated.

**Comment by maxtepkeev** [comment]
You're probably using http while you should be using https protocol, see [this](http://python-redmine.readthedocs.io/faq.html#create-update-delete-resource-operations-doesn-t-work) for details.

**Comment by millertime145** [comment]
Sorry I should have mention this. I am using the https protocol: redmine=Redmine("https://.....").

**Comment by maxtepkeev** [comment]
Than probably you have the opposite situation, e.g. you're using https but your webserver is doing redirect to http for some reason. That's the only reason for that mistake to happen.

**Comment by millertime145** [comment]
Do you know of a work around so the webserver does not redirect to http?

**Comment by maxtepkeev** [comment]
Well, you just have to set up your webserver properly, e.g. it shouldn't do the redirects. Have you tried using http in Redmine, e.g. redmine=Redmine("http://...") ?

**Comment by millertime145** [comment]
I have but get the same error. Unfortunately I didn't set up the webserver and I don't have access to change the webserver. 

I've also tried 'allow_redirects':False. This returned: UnknownError: Redmine returned unknown error with the code 302.

**Comment by maxtepkeev** [comment]
Yes, because allow_redirects just won't allow requests library, which python-redmine is using to follow that redirect and the error you're receiving (302) confirms that you're having this redirect problem that I talked about in my previous responses.

It seems that you have a badly configured webserver which is doing redirects even when it shouldn't, e.g. when you tried to uses https. So you need to contact webserver admin and ask him to fix this weird behaviour.

**Comment by millertime145** [comment]
Thanks Max! I will figure out who to contact. I appreciate your help!

**Comment by millertime145** [comment]
Webserver admin fixed the problem and I'm able to create a new issue. Thanks again for the help!!!

**Comment by maxtepkeev** [comment]
This is great! Thanks for letting me know.

**Comment by jonfen** [comment]
I am having a similar error message:

redmine = Redmine('https://redmine.***.com/redmine/', version='3.2.0', key='***')
issue = redmine.issue.new(***)
issue.save()
`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python\Python33_64\lib\site-packages\redminelib\resources\base.py", line 374, in save
    self._decoded_attrs = self.manager.create(**self._changes).raw()
  File "C:\Python\Python33_64\lib\site-packages\redminelib\managers\base.py", line 163, in create
    resource = self._process_create_response(request, response)
  File "C:\Python\Python33_64\lib\site-packages\redminelib\managers\base.py", line 174, in _process_create_response
    return self.to_resource(response[self.container])
KeyError: 'issue'
`

**Comment by maxtepkeev** [comment]
Hi @jonfen 

I'm 99,9% sure this is not a Python-Redmine problem, usually this is either a web server misconfiguration or some Redmine plugin is breaking an API. I would suggest you to have a look what an actual response from Redmine is to figure out what's going on.

**Comment by maxtepkeev** [comment]
@jonfen Interesting, can you please tell me your Redmine version and give an example of the request to reproduce this behaviour.

**Comment by jonfen** [comment]
@maxtepkeev version 3.2.0

`curl -X POST -k -H 'X-Redmine-API-Key: ******' -H 'Content-Type: application/xml' -i 'https://redmine/redmine/issues.xml' --data '<?xml version="1.0"?>
  <issue>
    <project_id>2</project_id>
    <subject>Successful REST Test</subject>
    <priority_id>2</priority_id>
  </issue>'`

`curl -X POST -k -H 'X-Redmine-API-Key: ******' -H 'Content-Type: application/xml' -i 'https://redmine/redmine/issues.xml' --data '<?xml version="1.0"?>
  <issue>
    <project_id>Project_Name</project_id>
    <subject>Failing REST Test</subject>
    <priority_id>2</priority_id>
  </issue>'`

**Comment by maxtepkeev** [comment]
@jonfen 

Thanks for this example. It looks like this is a bug in Redmine which was fixed in 3.3.1, see http://www.redmine.org/issues/23766 for details
