### ISSUE TITLE
Infinite loop when uploading zero-length files

### ISSUE THREAD

**Issue by Tauwasser** [maxtepkeev/python-redmine#152]
When uploading zero-length files when creating issues or updating them, python just hangs and seemingly does nothing anymore. Apparently this has to do with the fact that the file is opened as a stream and the underlying code in packages/requests will now try to send in chunks, but I know too little python to identify the respective line of code.

Example code:

`redmine.issue.create(project_id=project.id, subject='Upload Test', tracker_id=1, description='Test uploading zero-length file', status_id=3, priority_id=7,uploads=[{'path': '/path/to/empty.file'}])`

**Comment by maxtepkeev** [comment]
Hi, ok, I'll look into it, meanwhile you can just add a check in your code for the zero-length files.

**Comment by maxtepkeev** [comment]
This is a bug in requests, see https://github.com/kennethreitz/requests/issues/3066. I've tried the current master branch of requests and it works fine now, i.e. raises ``ValidationError: 1 file(s) could not be saved.``

I've also added a size check in python-redmine which will be a part of the next release. (See 71cb6e53ecc868144191fd95c9da5617d01eb72d)

Thanks for the bug report.
