### ISSUE TITLE
Crash when trying to connect to redmine version 2.3.2

### ISSUE THREAD

**Issue by belvedere-trading** [maxtepkeev/python-redmine#153]
Hi,

I was trying to use the library with Redmine 2.3.2 and I am getting a crash:

File "/Library/Python/2.7/site-packages/redmine/__init__.py", line 47, in __getattr__
    return ResourceManager(self, resource)
File "/Library/Python/2.7/site-packages/redmine/managers.py", line 40, in __init__
    raise ResourceError
redmine.exceptions.ResourceError: Unsupported Redmine resource

Have you all seen this before?  If I point the code to demo.redmine.org it works fine, this demo site runs Redmine 3.0.0.devel.14065.

Here is a bit more information about the environment.

Environment:
  Redmine version                2.3.2.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.13
  Environment                    production
  Database adapter               Mysql2

**Comment by belvedere-trading** [comment]
We are just so far behind, we will just upgrade it.   No reason to look into this.

**Comment by maxtepkeev** [comment]
Hi, sorry that I didn't answer earlier. Actually, everything should work with Redmine 2.3.2 and even earlier versions. I think you have some configuration problems with Redmine or you didn't enable REST API in settings or there is some plugin that messes up everything. In any case this is not connected with python-redmine but with Redmine itself.

**Comment by belvedere-trading** [comment]
Thanks for getting back to us.  We do have the REST api enabled and the unsupported pyredmine library has been working fine.  It might be a plugin we have installed, but since we plan to upgrade we will do that first and then try this out again.  Thanks for getting back to us.

**Comment by maxtepkeev** [comment]
Sure, let me know if upgrade doesn't help, we'll try to figure out what's causing this weird behaviour.
