### ISSUE TITLE
Filter doesn't seem to do anything

### ISSUE THREAD

**Issue by carroarmato0** [maxtepkeev/python-redmine#154]
Given:  connection to Redmine (v3.0.3) works

I'm trying to fetch the info of a User given his login:

`        users = redmineapi.user.filter(name='carroarmato0')
`
But I keep getting no results.

Based on the redmine access logs, it would seem like a request isn't even made.

**Comment by maxtepkeev** [comment]
Please, read the [docs](http://python-redmine.readthedocs.io/operations.html#filter) before using the library to understand the concepts:

> ResourceSet object is lazy, i.e. it doesn’t make any requests to Redmine when it is created and is evaluated only when some of these conditions are met:

> Iteration. A ResourceSet is iterable and it is evaluated when you iterate over it.
> for project in redmine.project.all():
        print(project.name)

> len(). A ResourceSet is evaluated when you call len() on it and returns the length of the list.
> len(redmine.project.all())

> list(). Force evaluation of a ResourceSet by calling list() on it.
> list(redmine.project.all())

> Index. A ResourceSet is also evaluated when you request some of it’s Resources by index.
> redmine.project.all()[0]  # Returns the first Resource in the ResourceSet

**Comment by carroarmato0** [comment]
Oooh I misunderstood that part. Makes whole lot of sense now.

Thanks! Works like a charm :)
