### ISSUE TITLE
Private notes/journals on Issue objects

### ISSUE THREAD

**Issue by Heilage** [maxtepkeev/python-redmine#158]
First off, great library. I've been implementing a customer-oriented interface for Redmine, and your work is making ours a whole lot easier.

To the issue: `Issue` objects have related `Journal`s. I'm not sure exactly how this maps to the Redmine backend, but notes/journals/comments can be marked private, and thus hidden from non-priveledged (sp?) users. I can't seem to find out how the `Issue.journals` collection stores this flag. We need to filter private notes on our application. 

Any suggestions?

**Comment by maxtepkeev** [comment]
You need Redmine >= 3.3.0 for that, see http://www.redmine.org/issues/20985

**Comment by Heilage** [comment]
Ah, good to know. We are on 3.1.1, this might be a good reason to upgrade.
