### ISSUE TITLE
Delete attachments

### ISSUE THREAD

**Issue by kelupa** [maxtepkeev/python-redmine#160]
Hi:

I want to delete attachments on issues, but I have been looking for on www.redmine.org and I didn't find anything. 
I mean... delete attachments using python... 

Do you know how to do this?

Thanks in advance.

**Comment by maxtepkeev** [comment]
You need Redmine >= 3.3.0 for this to work. Also you need python-redmine >= 2.0.0 which is not released yet, but you can use a v2 branch at your own risk, because this can be unstable at the moment. I plan a release on March. So you have to wait a little bit.

**Comment by kelupa** [comment]
ok... 

I'll wait.

Thank you very much.
