### ISSUE TITLE
Upload a document

### ISSUE THREAD

**Issue by vlegoff** [maxtepkeev/python-redmine#161]
I know this is supposed to be accessible through Redmine 3.4, which isn't yet published, but since I saw a 'upload' method in the Redmine object, I was wondering what could be done through it... and especially if we could upload a file already?  If not as a document, then we could update the URL in a wiki page, for instance, and I know updating a wiki page through PythonRedmine is possible since I use it about every day for my project.  I didn't try the 'upload' method, though.  I've used the 'download' method often, especially since we didn't have to download the file at once and could display a progress bar.  As for uploading, I guess that's not possible.  Still, what can we do for the time being?  Is it possible to upload a file and fetch its URL, for instance?

**Comment by maxtepkeev** [comment]
The ``upload`` method on Redmine object just uploads a file to the Redmine and returns an assigned token that identifies this file inside Redmine. Then you can use this token to attach this uploaded file to the resource that supports attachments, for example Issue or Wikipage. If you just upload a file and don't attach it to the resource, it will just stay in Redmine, if you lose a token, you can't get it again through the REST API, you need to search for it manually inside the Redmine database.

That's all that you can do with it for now. And no, it's not possible to upload a file via ``upload`` and fetch it's url, BUT if you upload and then attach it to some Resource, it becomes an Attachment resource by itself (surprise, surprise), and then it will have an id, url and so on, and you can use ``redmine.attachment.get(ID)`` to get this info from it.

The low-level details of this process are described [here](http://www.redmine.org/projects/redmine/wiki/Rest_api#Attaching-files).

**Comment by vlegoff** [comment]
Thank you very much.  Not sure I should ask questions on the issue 
tracker, but thank you for the answer, it works perfectly.

**Comment by maxtepkeev** [comment]
You're welcome.

I don't see any problem in asking questions here, there's even a ``question`` label for such issues ;)
