### ISSUE TITLE
Regexp in custom field filter

### ISSUE THREAD

**Issue by DennyWeinberg** [maxtepkeev/python-redmine#164]
We can use the `~` sign before the string to search if we want to find all issues containing a string in a custom field.

Example:
`list(redmine.issue.filter(**{'cf_%s' % (conf.re_cf_jiraLinkId): '~LX-2822'}))`

This finds all issues containing LX-2822 in the custom field with id `conf.re_cf_jiraLinkId`.

Could you please add this to the doc?

**Comment by maxtepkeev** [comment]
Cool. I'll definitely add that. Thanks.

**Comment by maxtepkeev** [comment]
This information was added to the new docs that will be available together with v2.0.0 in the end of March.
