### ISSUE TITLE
Set created_by during new issue creation

### ISSUE THREAD

**Issue by fafnir1990** [maxtepkeev/python-redmine#169]
Hello

I would like to ask if there is any possibility to set "created_by" field during creation of new issue?

Thanks in advance for reply

Best regards

Rafal

**Comment by maxtepkeev** [comment]
Hi, you mean the user who created an issue ? It's already there, see ``author`` attribute.

**Comment by fafnir1990** [comment]
Ok, thank you for reply, I`ll try

**Comment by maxtepkeev** [comment]
You can see all available attributes using ``dir()``, e.g. ``dir(issue)``, it's mentioned somewhere in the docs btw.

Closing this issue for now, if you need more help with this just post it here and I'll reopen it.

**Comment by fafnir1990** [comment]
Hello, I tried our solution, but unfortunately "author" attribute is unfortunately read only during creation and updating. Is it possible to add argument to redmine.issue.new(), which allows to substitute author_id?

**Comment by maxtepkeev** [comment]
Yes, it's a read-only attribute, it's a limitation of Redmine API and I can do nothing about it. So a user who created an issue is considered an author of it. If you need to change an author you have to either use his/her login/password or you can use admin account and use impersonation feature to switch to other user accounts.

**Comment by maxtepkeev** [comment]
Closed due to inactivity
