### ISSUE TITLE
How to get custom_field value

### ISSUE THREAD

**Issue by vfabi** [maxtepkeev/python-redmine#170]
How to get issue custom_filed value by it's name or id?

**Comment by maxtepkeev** [comment]
Like all other fields. Did you try something ?

One way would be:

```python
issue = redmine.issue.get(1)

for cf in issue.custom_fields:
    print cf.id, cf.name, cf.value
```

**Comment by vfabi** [comment]
Hmm, 
Yes, i tryed this, but it's not usable in some cases. 
I use Django to render issues, so in template engine i just iterating issues with printing theirs fields, and to get\print custom field i need to iterate issue one more time :(
It would be nice to just get custom filed by it's id or name, without iterating to get specific field.

**Comment by vfabi** [comment]
Django template:
<ul>
    {% for issue in issues %}
        <li>
        {{ issue.id }} {{ issue.priority }} {{ issue.subject }} {{ issue.**???CUSTOM_FILED???** }}
        </li>
    {% endfor %}
</ul>

**Comment by maxtepkeev** [comment]
So, you're interested only in printing specific custom field here ?

**Comment by vfabi** [comment]
Yes

**Comment by maxtepkeev** [comment]
Well, there is a helper for this, you can do issue.custom_fields.get(X) where X is the custom field's id, but you can't call a method and pass a param to it in django template afaik, so you'll have to create a custom tag I guess.

**Comment by vfabi** [comment]
issue.custom_fields.get(X)  returns custom filed name, but not value :(

> but you can't call a method and pass a param to it in django template afaik
You are right, and it's a problem :(

> you'll have to create a custom tag I guess.
Yes, only this way. But i think it's only workaround solution.

**Comment by maxtepkeev** [comment]
issue.custom_fields.get(X) return a Resource object, which you can use to access anything from this resource, e.g issue.custom_fields.get(X).value.

I don't see this as a problem at all, I can't provide users with accessors for all the possible situations, you can either create a custom tag and use it to access everything you need or you can prepare your code in python before passing it to template.

**Comment by vfabi** [comment]
You are right, there is no one solution for all cases/situations. I just want to notice, that it could be more flexible and useful to get custom fields value the same way as other issue fields. So as you proposed before, i am going to do it with template tag. 
Thx for you help and time.
