### ISSUE TITLE
Filter don't get closed issues

### ISSUE THREAD

**Issue by vfabi** [maxtepkeev/python-redmine#171]
Filter don't get issues with 'Closed' status. Issue with id=518 have 'Closed' status.

Code:
```
issues_redmine = redmine.issue.all().filter((52, 118, 193, 209, 517, 518))
for issue in issues_redmine:
    print(str(issue.id), str(issue.status))
```
Prints:
```
('517', 'In Progress')
('209', 'Accepted')
('193', 'Accepted')
('118', 'In Progress')
('52', 'Accepted')
```

**Comment by maxtepkeev** [comment]
```issues_redmine = redmine.issue.filter(status_id='*').filter((52, 118, 193, 209, 517, 518))```

I know it's weird, but Redmine API doesn't return closed issues by default and python-redmine just respects this behaviour for now, so you have to explicitly get closed issues like this.

**Comment by vfabi** [comment]
Heh, such not obvious thing. Thx fo your help.
