### ISSUE TITLE
Code sample on how to attach a file to a ticket

### ISSUE THREAD

**Issue by adriens** [maxtepkeev/python-redmine#172]
Hi,

It would very convenient to have a code snippet that shows how to upload a attach a file to a given ticket.

Thank you in advance for your help.

**Comment by maxtepkeev** [comment]
Well, there is a code sample in the [docs](http://python-redmine.readthedocs.io/resources/issue.html#new)...

**Comment by adriens** [comment]
I did not finf the docs, i did only look at the README.md code sample.
The doc you are pointing does perfectly fit my needs :+1: 
Thanks a lot for having ponted this.

Kind Regards,
Adrien

**Comment by maxtepkeev** [comment]
If you look at the README.md just a few lines after the code sample there is a section called Documentation which points to the docs I gave you ;-)
