### ISSUE TITLE
How do I access a repository in a project?

### ISSUE THREAD

**Issue by vinay87** [maxtepkeev/python-redmine#173]
I'm trying to extract the path to a repository from all projects in my Redmine database. I dont see anything in the documentation about this? Is this feature covered?

**Comment by maxtepkeev** [comment]
Python-Redmine is just a client to a Redmine API and this feature isn't accessible through Redmine API, that means that Python-Redmine also doesn't provide this feature for you. Here are the [docs](http://www.redmine.org/projects/redmine/wiki/Rest_api) of Redmine API if you're interested.

**Comment by maxtepkeev** [comment]
Closed due to inactivity
