### ISSUE TITLE
How to get issues history?

### ISSUE THREAD

**Issue by breezetemple** [maxtepkeev/python-redmine#174]
I do not find a way to query issues' history ? Is that possible ?

**Comment by maxtepkeev** [comment]
Wha do you mean by "history" ? If you mean comments that were left by participants this is called "journals":

```python
issue = redmine.issue.get(ISSUE_ID, include='journals')

for record in issue.journals:
    print record.id, record.user, record.created_at
    print record.notes
    print record.details
```

**Comment by breezetemple** [comment]
You are right, thanks for you help and time!

**Comment by manish2507** [comment]
> Wha do you mean by "history" ? If you mean comments that were left by participants this is called "journals":
> 
> ```python
> issue = redmine.issue.get(ISSUE_ID, include='journals')
> 
> for record in issue.journals:
>     print record.id, record.user, record.created_at
>     print record.notes
>     print record.details
> ```

Details is not coming in proper format. I mean it is giving id's of changes. Can you suggest me how to get name. like Status changed from new to resolved.

**Comment by maxtepkeev** [comment]
@manish2507 That's how Redmine is giving the response, Python-Redmine has no control over the response data or format. If you need real status names instead of ids you have to do ``redmine.issue_status.all()`` which returns all issue statuses available in your Redmine instance and get real status names from there by ids. Docs: https://python-redmine.com/resources/issue_status.html#all

**Comment by manish2507** [comment]
thanks

**Comment by dmahmutov** [comment]
Hello there. Im trying `<issues = redmine.issue.all()>` and want to get history "journals". But i cant. Am i right. By trying. `<for record in issues:
                                             print(record.id) etc>`

**Comment by dmahmutov** [comment]
@maxtepkeev

**Comment by maxtepkeev** [comment]
@dmahmutov ``issues = redmine.issue.all()`` returns you a ResourceSet of issues, so at first you have to iterate over it to get access to individual issues, and then each issue will provide you with journals attribute.

**Comment by dmahmutov** [comment]
@maxtepkeev Hey there again. Wish that I'm not so annoying, but
```
for issue in issues:
      records = redmine.issue.get(issue.id, include='journals')
      for record in records:
             <work with journals>   
```

am I righty then?

**Comment by maxtepkeev** [comment]
@dmahmutov https://python-redmine.com/resources/issue.html#journals

**Comment by dmahmutov** [comment]
Hello there again, what type of statutes issue.all() method returns?

**Comment by maxtepkeev** [comment]
Hi, what do you mean by "type of statuses" ? It returns the same statuses, that Redmine has.
