### ISSUE TITLE
Filter formatting for newer versions of Redmine (>3.2.2 at least) apparently not compatible with issue.filter

### ISSUE THREAD

**Issue by PauloZan** [maxtepkeev/python-redmine#176]
There doesn't seem to be a way to add the filtering parameters in the format needed for newer versions of Redmine (>3.2.2 at least) as described in the document found by @benvdh (http://www.freelancingdigest.com/articles/redmine-query-reference/). Specifically, I can´t replicate the syntax needed for filtering the issues created between two dates.

For example, in recent versions of Redmine if we wish to filter all issues between April 1st, 2017 and April 15th, 2017 the following would be appended to the search string (before urlencoding):

f[]=created_on&op[created_on]=><&v[created_on][]=2017-04-01&v[created_on][]=2017-04-30

or after urlencoding:

f%5B%5D=created_on&op%5Bcreated_on%5D=><&v%5Bcreated_on%5D%5B%5D=2017-04-01&v%5Bcreated_on%5D%5B%5D=2017-05-12

This example of the "new" filtering can be tried out on the redmine.org website:

https://www.redmine.org/projects/redmine/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=o&f%5B%5D=created_on&op%5Bcreated_on%5D=%3E%3C&v%5Bcreated_on%5D%5B%5D=2017-04-01&v%5Bcreated_on%5D%5B%5D=2017-05-15&f%5B%5D=&c%5B%5D=tracker&c%5B%5D=status&c%5B%5D=subject&c%5B%5D=updated_on&c%5B%5D=category&group_by=

The main problem is that, as parameters to filter are passed by a dict, the new syntax used by Redmine for filtering is incompatible with Python (there are multiple v[created_on][] keys in my example, but there could be multiple f[] keys in general).

Any ideas on how to solve this?

**Comment by maxtepkeev** [comment]
Yes, the query syntax described in #57 isn't available in Python-Redmine yet, but will be, I'm working on that.

For your case to filter all issues between 2 dates you can use
```python
redmine.issue.filter(created_on='><2012-04-01|2012-04-15')
```
You can find more examples [here](http://www.redmine.org/projects/redmine/wiki/Rest_Issues#Listing-issues).

I will update the Issue documentation regarding ``created_on`` field.

**Comment by PauloZan** [comment]
Thanks @maxtepkeev for the quick response, but the older format of filtering doesn't work with Redmine 3.2.2.stable, at least for the specific case I presented. I debugged the http request (using the requests library) after modifying my code to use the format documented in the Redmine docs (and sugested above):

`GET /redmine/issues.json?key=*****&project_id=10018&tracker_id=10019&status_id=%2A&sort=id&created_on=%3E%3C2017-04-01%7C2017-04-30&limit=60&offset=15700 HTTP/1.1`

which seems ok, but actually Redmine doesn't recognizing the created_on filter and returns all 15760 issues logged on tracker 10019.

The behavior can be reproduced manually on "www.redmine.org".

I´ve tried a workaround by inserting the dict directly, i.e.:

`issue.filter(**{"project_id":project, "tracker_id":tracker, "status_id":"*", "sort":"id",
                                   "f[]":"created_on", "op[created_on]":"><", "v[created_on][]":dataini, "value[created_on][]":dataend})`

but it only recognizes the first "value" (I had to change v[created_on] to value[created_on] for the second parameter because we can't have two identical keys in the dict). 

I've reverted to filtering the created_on dates in python after downloading, which is clearly suboptimal.

**Comment by maxtepkeev** [comment]
Just checked, works perfectly, this is a raw response from the browser (returns 8 issues):

``http://www.redmine.org/projects/redmine/issues.json?created_on=%3E%3C2012-03-01|2012-03-07``

And this is a Python-Redmine code:

```python
>>> from redminelib import Redmine
>>> redmine = Redmine('http://www.redmine.org/projects/redmine')
>>> len(redmine.issue.filter(created_on='><2012-03-01|2012-03-07'))
8
```

Absolutely same result.

**Comment by PauloZan** [comment]
Thanks @maxtepkeev , but there seems to be a regression with Redmine 3.2.2 or a problem with our installation. I can't reproduce the raw browser response we get on www.redmine.org on our server.

I couldn't find this specific bug on the Redmine bug tracker, but I'll start debugging our installation.

Anyhow, it is certainly a problem with Redmine (either with 3.2.2 ou our installation), not with python-redmine.

**Comment by maxtepkeev** [comment]
Yep, you can try to upgrade your installation and see if that helps. If not then it must be a problem with some plugins, you can turn all of them off and turn on one by one and see which one is causing this.

Would be great if you reply here when you figure what is causing this strange behaviour.

**Comment by PauloZan** [comment]
I'll try to upgrade on our test server. We don't have any plugins installed, but I'll reply here if I find out why the server isn't replying correctly (note that it doesn't throw any errors either).

Thanks @maxtepkeev.

**Comment by maxtepkeev** [comment]
Closing this as there's no feedback.
