### ISSUE TITLE
redmine Project Memberships for group_id?

### ISSUE THREAD

**Issue by Jiangshan00001** [maxtepkeev/python-redmine#178]
could the redmine Project Memberships support group_id set?
I test it already support user group read. how to support the user group set?
thanks.

this problem is solved!

eg:
set user_id=1 to role_ids=[1,2] in project_id='vacation' is such as:
>>> membership = redmine.project_membership.new()
>>> membership.project_id = 'vacation'
>>> membership.user_id = 1
>>> membership.role_ids = [1, 2]
>>> membership.save()

set group_id=12 to role_ids=[1,2] in project_id='vacation' is such as:
>>> membership = redmine.project_membership.new()
>>> membership.project_id = 'vacation'
 membership.user_id = 12  # THIS CAN BE THE GROUP ID. group and user is somehow the same in redmine???
>>> membership.role_ids = [1, 2]
>>> membership.save()

maybe the documentation could be imporved
thanks

**Comment by maxtepkeev** [comment]
I'm sorry but I don't understand what you mean, can you give a more detailed explanation or code examples, thx.

**Comment by Jiangshan00001** [comment]
library code is prefect.
just the documentation could be imporved.

**Comment by maxtepkeev** [comment]
Oh, yes, that makes sense. I updated the docs, thanks.
