### ISSUE TITLE
 requested resource doesn't exist

### ISSUE THREAD

**Issue by jj15602242930** [maxtepkeev/python-redmine#179]
redmine = Redmine('http://localhost/redmine/', username='02272', password='123456789')
data_list = [['t123', 'd123', 30, 56, 2, 18, '456'],
                     ['t22', 'd123', 30, 56, 2, 18, '456']
                     ]
issue = redmine.project.get(18)

issue.issues.manager.create(
    subject=data_list[0],
    description=data_list[1],
    done_ratio=data_list[2],
    parent_issue_id=data_list[3],
    tracker_id=data_list[4],
    project_id=data_list[5],
    custom_fields=[{'id': 2, 'value': data_list[6]}])
Error in the last line, There( requested resource doesn't exist)
I was okay with the native test, and this exception occurred on the server test.
The data on the server is a lot. Redmine is from 3.1 to 3.3. Can you help me.

**Comment by maxtepkeev** [comment]
Hi,

It would be much better if you could attach the whole traceback.

Also, don't do ``issue.issues.manager.create`` it should just be ``redmine.issue.create``, where did you get that syntax, it doesn't exist anywhere in the documentation.

Also what do you mean by "I was okay with the native test" ? What do you mean by "native" test ?

**Comment by maxtepkeev** [comment]
Closed due to inactivity.
