### ISSUE TITLE
Filter query for Redmine 1.1.3.stable.5989

### ISSUE THREAD

**Issue by ramesh6666** [maxtepkeev/python-redmine#180]
Hi,
     I would like pointers to write a query that outputs the number of open and closed issues for a given week and also the author opening and closing the issues. Is this possible with Redmine 1.1.3 version which is what I am using?

thx
R

**Comment by maxtepkeev** [comment]
Hi, this is a very old version and you should seriously consider to upgrade, but it should be possible to do that still. You need ``redmine.issue.filter(created_on='><2017-06-26|2017-07-02', status_id='*')`` to return all open and closed issues for previous week, then just iterate over it and take what you need.

**Comment by maxtepkeev** [comment]
Closed due to inactivity.
