### ISSUE TITLE
Python-Redmine no module named redmine – macOS 10.12.5

### ISSUE THREAD

**Issue by ayesjm** [maxtepkeev/python-redmine#181]
i am trying to install python-redmine on a macos 10.12.5. I did the following:

sudo easy_install pip
pip install python-redmine

i get the following output when trying to run a python script:

Joshuas-MacBook-Pro:~ joshuaayes$ ./changelog.py 
Traceback (most recent call last):
  File "./changelog.py", line 2, in <module>
    from redmine import Redmine
ImportError: No module named redmine
Joshuas-MacBook-Pro:~ joshuaayes$ pip install python-redmine
Requirement already satisfied: python-redmine in /Library/Python/2.7/site-packages
Joshuas-MacBook-Pro:~ joshuaayes$

**Comment by maxtepkeev** [comment]
``from redmine import Redmine`` is a 1.x style import, starting from v2 it's ``from redminelib import Redmine``, please follow the [docs](https://python-redmine.com/configuration.html), everything is described there.
