### ISSUE TITLE
parameters other than project_id is not being sent with the request while creating an issue

### ISSUE THREAD

**Issue by SundarBalaji93** [maxtepkeev/python-redmine#184]
Hi,

   I'm trying to create an issue using the below syntax:
    
`   redmine.issue.create(project_id = 15, subject = 'sample message')
`

   But im getting an exception while the above code is getting executed

   **Subject cannot be blank** is the exception message

   while seeing the redmine log i found out that only the **project_id** param was passed into the create 
   api

  **subject** param was left out in the api post request

**Comment by maxtepkeev** [comment]
Hi, I don't think this is python-redmine's fault, otherwise a lot of people would have complained already, unless you found an incompatibility with some Redmine version which is very unlikely.

Try to see if you code works against public Redmine instances (demo.redmine.org or demo.redminecrm.com) and if it does then try to upgrade your Redmine version to the latest one or if you have something in front of it, e.g. nginx) check if it proxies requests correctly.

If it doesn't work against these public instances then I would appreciate if you post the whole code here so we could try to reproduce this issue. Also make sure you're using the latest python-redmine version.

**Comment by SundarBalaji93** [comment]
Im using python-redmine 2.0.2 version. I think this is the latest version

**Comment by SundarBalaji93** [comment]
Im trying to post a new issue in demo.redmine.org using the below url

http://demo.redmine.org/projects/best-project/issues.json?project_id=best-project&subject=sample

**Im getting the same error Subject cannot be blank.**

Please correct the request url if i did miss anything to include

**Comment by maxtepkeev** [comment]
Why are you using get parameters ? This is a post request this is why you're getting this error, anyway I tested it against demo.redminecrm.com and it works as expected, here's the code:

```python
from redminelib import Redmine
redmine = Redmine('http://demo.redminecrm.com', username='admin', password='admin')
redmine.issue.create(project_id=4, subject='hello world')   
```

**Comment by maxtepkeev** [comment]
Oh by the way, check this [section](https://python-redmine.com/faq.html#create-update-delete-resource-operations-don-t-work) from the FAQ, maybe that's your problem.

**Comment by SundarBalaji93** [comment]
this is the issue creation url that im using

http://<our custom redmine domain >/projects/15/issues.json?key=<key value>&tracker_id=2

the body or payload for the above request is 

{
	"issue": {
		"subject": "sample"
	}
}

Here subject is the only required field, But still the response is coming as an error

{
  "errors": [
    "Subject can't be blank"
  ]
}

I think the request body is not getting passed to the redmine issue creation api.But if i change the request url to public redmine instance like this 

http://demo.redmine.org/projects/best-project/issues.json?tracker_id=1

and the request body is the same as the aboe one.It works in that public instance like a charm

what do you think the issue would be?

**Comment by DmitryKaramin** [comment]
I can confirm that something in your code is wrong
this code works fine on [demo.redminecrm.com](demo.redminecrm.com)
> project = redmine.project.get(13)
> issue = redmine.issue.create(
>     project_id=13,
>     subject="Python-redmine"
> )

prove - [http://demo.redminecrm.com/projects/agile/issues](http://demo.redminecrm.com/projects/agile/issues)

**Comment by SundarBalaji93** [comment]
Im using this **2.5.1.stable.161** version of redmine, Will updating redmine to newer version solve the issue?

**Comment by DmitryKaramin** [comment]
Have u succeed on with your problem on demo.redminecrm.com ??

**Comment by SundarBalaji93** [comment]
I haven't tried with demo.redminecrm.com, but i have tried with demo.redmine.org public instance.
This code is working fine
redmine.issue.create(project_id = 15, subject = 'sample message')

But the same code does not work in our redmine.It throws the exception while creating a new issue.

Does the python-redmine gives support to older redmine versions like the one im using(2.5.1.stable.161)?

**Comment by SundarBalaji93** [comment]
the issue was due to one of the installed redmine's plugin.
