### ISSUE TITLE
How can I edit an exist journal?

### ISSUE THREAD

**Issue by ityoung** [maxtepkeev/python-redmine#185]
Hi，
I want to edit an exist journal on my readmine, however,
`issue.update()` or `issue.notes="xxx"` 
can only add a new notes to my issue, I've googled an hour with nothing help, is that a method to do that?

**Comment by DmitryKaramin** [comment]
according to documentation you can use issue.update(). 
in parameters you can find 
notes (string) – (optional). Issue journal note.
Hope it is what you are looking for.

**Comment by ityoung** [comment]
Sorry I didn't explant clear, I mean, if my exist issue id is 123, it's journal id is 12345, 12346, and I want to edit the note of journal 12345, how can I do that?

**Comment by DmitryKaramin** [comment]
This feature is not supported in redmine api yet
[http://www.redmine.org/issues/10171](http://www.redmine.org/issues/10171)

**Comment by ityoung** [comment]
So sad. Thanks a lot in any way!
