### ISSUE TITLE
Uploading files with file objects

### ISSUE THREAD

**Issue by hjpotter92** [maxtepkeev/python-redmine#186]
I am using the awesome package from a self contained AWS Lambda setup. However,  since uploads feature currently required absolute path to a file (which is not possible in a Lambda environment); it'd be helpful if we could use a file object/stream as well to be uploaded.

**Comment by maxtepkeev** [comment]
Makes total sense, thanks for raising this issue.

**Comment by maxtepkeev** [comment]
Tests, docs and a bit of code changes are in 3eb052376a9d0e67ce3ec2c39209b4c8376da033. This will be part of next release.
