### ISSUE TITLE
Using admin API key, create issue with another user

### ISSUE THREAD

**Issue by hjpotter92** [maxtepkeev/python-redmine#187]
I am planning to create an issue with another user as the author. The scenario is something like:

 * A user emails my smtp server
 * I search for existing users on Redmine with the sender's email address
 * I create an issue with the user resource retrieved from the step above

I think that I'd need to use the [`redmine.session` context][2] manager because there is no option to set the author in [`Issues` resource][1] manager.

Is there an alternative to achieve the same?

  [1]: https://python-redmine.com/resources/issue.html
  [2]: https://python-redmine.com/advanced/request_engines.html#session

**Comment by maxtepkeev** [comment]
Unfortunately not, Redmine's REST API doesn't allow to explicitly set the user during issue or other resource's creation, so you need to use session context for this as you assumed.

**Comment by hjpotter92** [comment]
Will the session context accept `impersonate=user.login`?

**Comment by maxtepkeev** [comment]
Yes it should, if it doesn't - it's a bug :)

**Comment by hjpotter92** [comment]
Yep. The `impersonate` parameter worked. Thanks
