### ISSUE TITLE
Connecting with PKI

### ISSUE THREAD

**Issue by DonTheGeek** [maxtepkeev/python-redmine#190]
I'm new here and tried to find another location to ask this question but still ended up here.

I have a redmine instance that is secured using PKI certificates.  I would like to use python-redmine to access the instance but cannot come up with a way to succeed.  I'm able to use curl and the standard URL3 request methods.  How do I tell python-redmine to use PKI?  Shouldn't be that complicated but I am just not seeing it.

I'm currently using the command below to access the non-PKI instance and it works great.
redmine = Redmine(self.RedMineURL, requests={'verify': False}, key='XXXXX')

Thanks for any help or pointing me to someplace that I've overlooked.

Don

**Comment by maxtepkeev** [comment]
Hi,

As stated in the docs we're using python-requests for managing connections. That means that we only support everything that is supported by the python-requests library, you can check all the available options (which you should pass in the requests argument, as you're already doing with `Redmine(self.RedMineURL, requests={'verify': False})` ) [here](http://docs.python-requests.org/en/latest/api/#requests.request).

Perhaps you can try something like `Redmine(self.RedMineURL, requests={'cert': ('/path/client.cert', '/path/client.key')})`, but it's better to ask in the python-requests github.

**Comment by maxtepkeev** [comment]
Closing this as there's no feedback.
