### ISSUE TITLE
possibility to lock user / set user status

### ISSUE THREAD

**Issue by flokli** [maxtepkeev/python-redmine#193]
Current user status is visible at `status`, and it's also possible to filter users by status using
```py
redmine.user.filter(status=…)
```

The meaning of each number is also documented at `docs/resources/user.rst`.

Bot it seems like it's currently not possible to update a users status through the API (which is possible using the PUT method on `/users/{id}.json` with data
```json
'{"user": {"status": 3}}')`
```

**Comment by maxtepkeev** [comment]
It is already possible to do that with the latest version, it just wasn't documented which is already fixed (check User resource documentation), e.g. to lock user:

```python
redmine.user.update(1, status=3)
```

or via save()

```python
user = redmine.user.get(1)
user.status = 3
user.save()
```

**Comment by flokli** [comment]
Thanks!
