### ISSUE TITLE
How to upload files to a issue?

### ISSUE THREAD

**Issue by xixiaocheng** [maxtepkeev/python-redmine#194]

**Comment by maxtepkeev** [comment]
Have you read the docs https://python-redmine.com/resources/issue.html ? See uploads parameter.

**Comment by xixiaocheng** [comment]
Oh, I check the Attachment and Working with Files part.

Should I use the issue.uploads = [{'path': '/absolute/path/to/file'}, {'path': '/absolute/path/to/file2'}] ?

How could I set the windows platform path?

Error occur when I use issue.uploads = [{'path': 'E:\a.txt'}]

**Comment by maxtepkeev** [comment]
E:/a.txt or E:\\a.txt

**Comment by xixiaocheng** [comment]
Thank you for your reply!
I upload a jpg file successfully, but it show 7237fd89c688074f2bc31c38ac9ef70c at the issue redmine page, not a jpg file.

**Comment by maxtepkeev** [comment]
Yes, because you didn't set a filename and Redmine generated one dynamically for you, it's all in the docs, please read them first, and write the code afterwards.

**Comment by xixiaocheng** [comment]
Yes! You are right!
