### ISSUE TITLE
Close a project

### ISSUE THREAD

**Issue by fmonera** [maxtepkeev/python-redmine#199]
Is there any way to close a project?

I tried with:

p.status = 5  # The id of closed status
p.save()

I tried with:

redmine.project.update(777, status = 5)

I tried both with status_id too.

What is the proper way to close a project?

**Comment by maxtepkeev** [comment]
It looks like it's not supported by Redmine's REST API itself. You can retrieve project's status, but you can't change it. There is a ticket for that already https://www.redmine.org/issues/13725

**Comment by maxtepkeev** [comment]
I believe this can be closed. As soon as Redmine will have this functionality it will work in Python-Redmine automatically.
