### ISSUE TITLE
How to access hidden Custom Fields from Users

### ISSUE THREAD

**Issue by FabioOrsi** [maxtepkeev/python-redmine#201]
Hello!
I've been trying to read hidden Custom Fields from Users using the admin token to access Redmine API but they are never returned with neither `user.custom_fields` nor `user.custom_fields._resources`. In these resources I can only read the visible custom fields.
Am I doing something wrong or is it a bug?
Thanks!

**Comment by maxtepkeev** [comment]
Hi!

Redmine doesn't return custom fields that have visible flag set to false, so there's nothing python-redmine can do about it.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
