### ISSUE TITLE
Question: Generate/Get API Access Keys

### ISSUE THREAD

**Issue by FabioOrsi** [maxtepkeev/python-redmine#202]
Hello!

Is it possible to use the Python-Redmine library to generate and get API Access Keys for other users in a session logged in as an Administrator?

Thanks!

**Comment by maxtepkeev** [comment]
Hi @FabioOrsi 

To get an API key for a user just request it's details by ID, e.g. ``redmine.user.get(123)`` where ``123`` is the user ID you're interested in. As far as I remember there's no need to generate it. It will be just there.
