### ISSUE TITLE
Question: How to Copy Issues?

### ISSUE THREAD

**Issue by FabioOrsi** [maxtepkeev/python-redmine#203]
Hello again!

In Redmine's GUI it's possible to make copies of issues, including their attachments.
I was wondering if it's possible to do the same action using the API, including copying the attachments.

The current solution I found is to get each issue, download their attachments, create the new issues and reupload the attachments. This approach is not very practical considering the attachments are over 20MB and that there are about 40000 issues to be copied.

Thanks!

**Comment by maxtepkeev** [comment]
Hi @FabioOrsi 

Yes, issue copying isn't supported in the REST API, only in GUI, also, there's no way to re-associate an already uploaded attachment to an issue without re-uploading it. There's even an [issue](http://www.redmine.org/boards/2/topics/48205) about that.

Unfortunately right now the only way to copy an issue is to do what you're already doing.

**Comment by maxtepkeev** [comment]
I can try to mimic the copy functionality from GUI, but not sure that it will work, so can't promise you anything. Let's keep this issue open until I try and we'll see if that works or not.

**Comment by maxtepkeev** [comment]
Implemented in b5252b2e75f878476f1bfbbc30eee05fc7681791. Will be released in v2.5.0.
