### ISSUE TITLE
How to get the  login user name？

### ISSUE THREAD

**Issue by dofospider** [maxtepkeev/python-redmine#206]
I read the document in several times, but I didn't find the  interface. Can I help me?

**Comment by dofospider** [comment]
maxtepkeev master：

      may be i can‘t clearly show my idea.
       也许我表达的不够准确。
      i mean if i use token logining the api. how to get the logining user name?
      如果我使用一个token登陆，如何获得当前登陆的用户名？

**Comment by maxtepkeev** [comment]
If you mean the login of the user, whose token was used to login, then:

```python
redmine = Redmine('https://redmine.url', key='b244397884889a29137643be79c83f1d470c1e2fac')
user = redmine.auth()
print user.login
```

This is described here https://python-redmine.com/advanced/external_auth.html

**Comment by dofospider** [comment]
thanks for your help.
that's i want.
thanks again.
