### ISSUE TITLE
Is it possible to assign issue to group?

### ISSUE THREAD

**Issue by spentus** [maxtepkeev/python-redmine#207]
Hi,

Is it possible to assign issue to group?

redmine.issue.update(
    issue_id,
    assigned_to_id=user_group_id
)

Got a validation error(
Thank you!

**Comment by maxtepkeev** [comment]
The validation error comes from Redmine, what did it say ?

Check Redmine's Settings -> Issue Tracking -> Allow issue assignment to groups

Python-Redmine doesn't validate this kind of settings, so most likely that Redmine itself doesn't allow you to do so.

**Comment by spentus** [comment]
Thanks
