### ISSUE TITLE
retreiving project parent Breadcrumb from an issue

### ISSUE THREAD

**Issue by Sylvain303** [maxtepkeev/python-redmine#213]
I try to display some issue with de project detailed as a full parent ancestry.

here's my actual code:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: set et ts=4 sw=4 sts=4:

from __future__ import print_function
from redminelib import Redmine, exceptions
import sys

redmine_url = 'https://redmine.domaine.com'
api_key = 'xxxxxxxxxxxx'

issue_id = int(sys.argv[1])

redmine =  Redmine(redmine_url, key=api_key, raise_attr_exception=False)
issue = redmine.issue.get(issue_id)

# find if project as a parent, and format string
p = redmine.project.get(issue.project.id)
project_str = str(p)
while p.parent is not None:
  project_str = "%s > %s" % (p.parent, project_str)
  p = redmine.project.get(p.parent.id)                                                                                                                   

print("#%d [%s] %s" % (issue_id, project_str, issue.subject.encode('utf-8')))
```
It takes almost 3sec for a single issue.
It is a bit slow, can I retrieve it more quickly ?

**Comment by maxtepkeev** [comment]
Hi @Sylvain303 

Apologies for the delay with an answer.

Basically you're doing everything correctly and there's nothing to optimize there, because Redmine doesn't give any information regarding whether a project has parent project or not, so you have to make an API call for every project to figure out whether it still has a parent.

**Comment by maxtepkeev** [comment]
@Sylvain303 Depending on the amount of issues/projects you have another option would be to retrieve all issues and projects into memory and then do the breadcrumb processing logic purely by python without making any API calls.

**Comment by Sylvain303** [comment]
@maxtepkeev , thanks. Hum, there's a lot of issue globally, > 50 000. So I don't think that processing them all to have a breadcrumb is the idea here. I've mainly 2 nested level, and at max 4 I think. I will keep this slow code for now. I may, fetch it in parallel as other query and build the final result if I have too many problem with that. For displaying a single issue, 3s is acceptable. Thanks for your answer. I close the ticket, your first answer was confirming I were doing it as expected. So for now it's OK. Faster query, would happen directly in DB so, if needed.

Thanks.
