### ISSUE TITLE
Question: Is it possible to get  attachments from issue journals?

### ISSUE THREAD

**Issue by tesmerjg** [maxtepkeev/python-redmine#219]
In my redmine instance, I have many issues with journals that have attachments. For example, see this:

![image](https://user-images.githubusercontent.com/438620/52525288-42802180-2c75-11e9-85db-ba4b4136c913.png)

I can easily get the attachments from the issue (count of 5), but I cannot seem to see the attachments related to the journals. Can you point me in the right direction?

Thank you,
John

**Comment by maxtepkeev** [comment]
Hi,

As far as I remember, each journal item can have a ``details`` property which is a list of changes made to the issue, each item in this list is a dictionary, check the ``property`` key and if it's name is ``attachment`` then you can use the ``name`` key to get it's id and make a query to the attachment resource to retrieve the actual file.

And you can always use ``dir()``as described in the docs to inspect the resource to find what attributes does it have.

**Comment by tesmerjg** [comment]
Thank you sir!

On Feb 10, 2019, at 09:34, Max Tepkeev <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

As far as I remember, each journal item can have a details property which is a list of changes made to the issue, each item in this list is a dictionary, check the property key and if it's name is attachment then you can use the name key to get it's id and make a query to the attachment resource to retrieve the actual file.

And you can always use dir()as described in the docs to inspect the resource to find what attributes does it have.
