### ISSUE TITLE
update custom field

### ISSUE THREAD

**Issue by ds485** [maxtepkeev/python-redmine#22]
Hi,
I was trying to update a date custom field. I am not getting an error, the return is actually true also the update time is set but it's not updating the field. I thought it may be a problem with the date field but it's also not working for integer or text fields.

example:
cf_1 = date
cf_2 = integer
cf_3 = text

```
redmine.issue.update(issue.id, cf_1='2014-04-17')
True
redmine.issue.update(issue.id, cf_2='20140417')
True
redmine.issue.update(issue.id, cf_3='20140417')
True
```

but the fields are still empty :(

**Comment by josephc1217** [comment]
> Because you are using the wrong format. Actually, the answer to your question is in [documentation](http://python-redmine.readthedocs.org/resources/issue.html#update):
> 
> ```python
> redmine.issue.update(1, custom_fields=[{'id': 1, 'value': '2014-04-17'}, {'id': 2, 'value': '2014-04-17'}]
> ```

It seems cannot work, i can update other fields like status , priority, etc through redmine.issue.update, but always failed to update the custom_fields like you mentioned. 

I found someone said that the custom_fields can not be update through the redmine.issue.update at present. 

Anyhow, i still dont know how to update the custom_fields successfully.

**Comment by maxtepkeev** [comment]
Hi @josephc1217 

Just checked, works perfectly fine for me, if you're sure that your custom field ids are correctly set, you need to give me more info, what type of custom field, what settings etc., better a screenshot from admin interface with this specific custom field settings you currently have.
