### ISSUE TITLE
HTTPS: issue with attachments url

### ISSUE THREAD

**Issue by jimmy-enyx** [maxtepkeev/python-redmine#231]
Hi everyone,

I have change my redmine url config to accept HTTPS and redirect to HTTPS when HTTP is used.
I encountered some issue with attachments url when using Redmine.download().

```
 redmine_client = Redmine('https://redmine.firm.ext', key='ACCESS_KEY', version="4.0.3")
 issue=redmine_client.issue.get(93966)
 for attachment in issue.attachments: 
     redmine_client.download(attachment.content_url, savepath=".",  attachment.filename)
```
This returns:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/tmp/venv_redmine/lib/python2.7/site-packages/redminelib/__init__.py", line 149, in download
    response = self.engine.request('get', url, params=params or {})
  File "/tmp/venv_redmine/lib/python2.7/site-packages/redminelib/engines/base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/tmp/venv_redmine/lib/python2.7/site-packages/redminelib/engines/base.py", line 138, in process_response
    raise exceptions.HTTPProtocolError
redminelib.exceptions.HTTPProtocolError: Redmine url should start with HTTPS and not with HTTP
```

In fact, `attachment.content_url` returns **http://redmine/attachments/download/331592/smth.txt** instead of **https://redmine.firm.ext/attachments/download/331592/smth.txt**
However `attachment.url` returns **https://redmine.firm.ext/attachments/331592** which seems to be good but it is not a direct download link.

We do not understand this difference, do you have any clue?

Moreover we redirect http://redmine/ to https://redmine.firm.ext/ but in this case we still get HTTP protocol with `HTTPProtocolError: Redmine url should start with HTTPS and not with HTTP`. I see you currently not accept redirection so i am stuck now.

**Comment by maxtepkeev** [comment]
Hi @jimmy-enyx 

This error is thrown by wrong HTTP protocol usage detector, i.e. when one uses HTTP instead of HTTPS, as far as I understand this problem happens only with attachments, to be more specific with ``content_url`` property and that looks like a Redmine bug to me, because if you changed everything to https, all the urls should start with https.

So I would fill a bug report to the Redmine guys, and until they fix it I would use a workaround like this: ``'https' + 'http://foo.bar/opaopa'[4:]``.

**Comment by jimmy-enyx** [comment]
Hi @maxtepkeev 

Thank for your reply.
We change our proxy settings, redirect seemed wrong on redmine side.
Now it seems ok.

Thank you very much!
