### ISSUE TITLE
How to get user assigned to issue?

### ISSUE THREAD

**Issue by spentus** [maxtepkeev/python-redmine#232]
Hello!
How can I get user assigned to issue?
I have issue_ID, i can do "issue = redmine.issue.get(issue_ID)".
But I can't get issue.assigned_to_id.
Where is my mistake, help please?

**Comment by maxtepkeev** [comment]
```python
dir(issue)
[u'assigned_to',
 u'attachments',
 u'author',
 u'changesets',
 u'children',
 u'closed_on',
 u'created_on',
 u'custom_fields',
 u'description',
 u'done_ratio',
 u'due_date',
 u'estimated_hours',
 u'id',
 u'is_private',
 u'journals',
 u'priority',
 u'project',
 u'relations',
 u'start_date',
 u'status',
 u'subject',
 u'time_entries',
 u'tracker',
 u'updated_on',
 u'watchers']
```

it's ``issue.assigned_to``, and you can use python'd ``dir()`` function to inspect any object. It's all written in the Python-Redmine documentation, I suggest to read it thoroughly as it will save you a lot of time in the future.
