### ISSUE TITLE
Get project identifier string

### ISSUE THREAD

**Issue by rroblik** [maxtepkeev/python-redmine#236]
Hi !

I don't find a way to get the internal identifier string (not numeric `id`) for a given project.
For example, the project named `Foo Bar`, id `8`, can have a name (the `project_identifier` in the project admin page) `foo-bar`.

But how to get the `foo-bar` value ? (not the numeric id, and not the name !) I need this because it's the "human constant" of a given project.

Looked at https://python-redmine.com/resources/project.html#get 

Thanks

**Comment by maxtepkeev** [comment]
It's called ``identifier`` if I'm not mistaken, can't check right now, but you can use a ``dir()`` function to introspect an object and see all the available attributes. It's described in the documentation btw.

**Comment by rroblik** [comment]
Thanks @maxtepkeev ; read again the doc and tada : https://python-redmine.com/introduction.html#refresh is what I need :) 

Thanks
