### ISSUE TITLE
How to get all the current user's authorized projects?

### ISSUE THREAD

**Issue by wangke857022523** [maxtepkeev/python-redmine#242]
Hi,

There is some way that i can get current user's authorized projects?

I noticed  there is a way to get project's user:
  redmine.project_membership.filter(project_id='vacation'), 
but i want current user's projects.

Can you help me?

Thanks a lot!

**Comment by maxtepkeev** [comment]
Hi,

Unfortunately there's no easy way to do that through the API.

You can try one thing, impersonate as the user you're interested in and call ``redmine.project.all()``. In theory it should return you only this user's projects. If that doesn't work you will have to go the hard way by first retrieving all projects, then for each project you'll need to retrieve members and then look which projects your user belongs to.

**Comment by wangke857022523** [comment]
Thank you very much for your reply. 
I have tried redmine.project.all(). But this is not universal. I tried two redmine website. One can get it correctly, one is getting an error. Here is my code:

```python
def get_projects(self):
        projects = self.redmine.project.all()
        print(projects)
        project_list = []
        for project in projects:
            project_data = {}
            project_data["id"] = project.id
            project_data["name"] = project.name
            project_list.append(project_data)
        return project_list
```

error message:

> ra.get_projects()
  File "RedmineAdaptor.py", line 23, in get_projects
    for project in projects:
  File "/usr/local/python3/lib/python3.6/site-packages/redminelib/resultsets.py", line 278, in __iter__
    return (self.manager.to_resource(resource) for resource in super(ResourceSet, self).__iter__())
  File "/usr/local/python3/lib/python3.6/site-packages/redminelib/resultsets.py", line 111, in __iter__
    'get', self.manager.url, self.manager.container, **self.manager.params)
  File "/usr/local/python3/lib/python3.6/site-packages/redminelib/engines/base.py", line 89, in bulk_request
    response = self.request(method, url, params=dict(params, limit=limit or self.chunk, offset=offset))
  File "/usr/local/python3/lib/python3.6/site-packages/redminelib/engines/base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/usr/local/python3/lib/python3.6/site-packages/redminelib/engines/base.py", line 153, in process_response
    raise exceptions.AuthError
redminelib.exceptions.AuthError: Invalid authentication details


I'm sure my username and password is valid. But I just can't get all projects. Is there any limits in redmine website setting?

**Comment by maxtepkeev** [comment]
If you're sure that your credentials are correct you should check Redmine settings and make sure that API is enabled.

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
