### ISSUE TITLE
KeyError: 'issue' on Create

### ISSUE THREAD

**Issue by fcabaud** [maxtepkeev/python-redmine#243]
I'm trying to create an issue

```python
issue__ = self.redmine.issue.create(
            project_id=87,
            subject=subject,
            tracker_id=tracker_id,
            description=description,
            status_id=default_status_id,
            fixed_version_id="",
            custom_fields=[]
            )
```
and I got this error

**KeyError: 'issue'**

```python
def _process_create_response(self, request, response):
        """
        Processes create response and constructs resource object.

        :param dict request: Original request data.
        :param any response: Response received from Redmine for this request data.
        """
        return self.to_resource(response[self.container])`
```
where self.container has "issue" value and not "issues" value. So there is an error for "issue" key in response dictionnary.

I saw issue [146](https://github.com/maxtepkeev/python-redmine/issues/146) and I confirm I'm using https protocol and not http.
I got this error for redmine 3.x and redmine 4.x

**Comment by maxtepkeev** [comment]
Hi @fcabaud 

Are you sure you don't have any plugins installed ?

I've just checked the demo.redmine.com (they run the latest Redmine 4.0.5) and was able to successfully create an issue.

**Comment by fcabaud** [comment]
Hello,

Without any plugin it's doesn't work.


```
Plugins
No data to display
```


<redminelib.resultsets.ResourceSet object with Issue resources>
Traceback (most recent call last):
  File "redmine_access.py", line 125, in <module>
    issue_id = redmine_obj.create_issue(args.project, redmine_obj.get_id_tracker_cve(), "Test Fred", "Hello world", [])
  File "redmine_access.py", line 101, in create_issue
    custom_fields=custom_fields
  File "/home/frederic/.local/share/virtualenvs/scripts-mIyQYxzX/lib/python3.7/site-packages/redminelib/managers/base.py", line 163, in create
    resource = self._process_create_response(request, response)
  File "/home/frederic/.local/share/virtualenvs/scripts-mIyQYxzX/lib/python3.7/site-packages/redminelib/managers/base.py", line 174, in _process_create_response
    return self.to_resource(response[self.container])
KeyError: 'issue'


There is no error in redmine logs.


How can I debug that ?


I'm in Redmine 4.0.5.stable

**Comment by maxtepkeev** [comment]
Can you try on demo.redmine.com (admin:admin) ? Does it work for you there ?

**Comment by fcabaud** [comment]
Heu, there is a blank page on http://demo.redmine.com and a connexion error on https://demo.redmine.com.


ping demo.redmine.com doesnt answer . . .

**Comment by maxtepkeev** [comment]
My apologies. It's demo.redmineup.com

**Comment by fcabaud** [comment]
It works on demo.redmineup.com and NOT on our Redmine installed 
both are on Redmine 4.0.5.stable

our redmine is installed from
https://github.com/wyplay/redmine_backlogs/commit/b454433c15eaff41e6a2c3a6738e3162148ad30f

**Comment by fcabaud** [comment]
Our redmine is installed from https://github.com/redmine/redmine/commit/3d8e2b1ce487bb585e7423cd46dcf0157b02d5e4

**Comment by maxtepkeev** [comment]
Well, it's definitely not a python-redmine problem. Perhaps you have some issues with a front end webserver which is misconfigured, if you have any of course, e.g. nginx.

**Comment by fcabaud** [comment]
There is an error for "issue" key in response dictionnary (key is "issue" insteed of "issues").


I dont really see the link with the front end webserver ?


The front end can change the API content ?

**Comment by maxtepkeev** [comment]
You're creating an issue, so the correct key is ``issue`` and not ``issues``. ``issues`` is only returned when you're performing a GET request, which is apparently what happens in your case.

There can be 3 reasons for this:

1) wrong protocol usage (https vs http and vice versa), but you told that you've checked this case
2) badly written plugins that corrupt API response
3) front end webserver which is badly configured, i.e. it changes the request method from POST to GET and you're getting ``isssues`` key instead if ``issue``.

Neither of these 3 aren't python-redmine problem.

**Comment by fcabaud** [comment]
OK. It was a problem of POST/GET due to front end webserver.

Thank you so much.
