### ISSUE TITLE
issue.update: redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist

### ISSUE THREAD

**Issue by sergeyyatmellanox** [maxtepkeev/python-redmine#244]
Hi,

When I try to update the notes(or any other attribute) I get this exception:

> redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist

The issue exists and I can 'get' it but not update it.
My code:

```
>>> x = redmine_server.issue.get(1438402)
>>> new_note = 'my new note'
>>> redmine_server.issue.update(1438402, notes=new_note)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/python_redmine-2.0.2-py2.7.egg/redminelib/managers.py", line 221, in update
    return self.redmine.engine.request(self.resource_class.http_method_update, url, data=data)
  File "/usr/lib64/python2.7/site-packages/python_redmine-2.0.2-py2.7.egg/redminelib/engines/base.py", line 75, in request
    return self.process_response(self.session.request(method, url, **kwargs), return_raw)
  File "/usr/lib64/python2.7/site-packages/python_redmine-2.0.2-py2.7.egg/redminelib/engines/base.py", line 158, in process_response
    raise exceptions.ResourceNotFoundError
redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist
```

**Comment by maxtepkeev** [comment]
Hi,

Your code is correct, you can check it against a public demo ad demo.redmineup.com

Are you able to update/create any resource via api (project/issue/etc) ?

**Comment by sergeyyatmellanox** [comment]
Yes. I have other issues I can both get and update.
The API works fine for most of them except for the few that I try to understand what's wrong with them/API.

**Comment by maxtepkeev** [comment]
I've never seen this situation before and never heard somebody complaining about that, so I can only assume that it can be some bug in Redmine and suggest you to try to update to the latest version first.

If that doesn't help it would be very interesting to see what the response from Redmine is for such issues (you can use ``print`` statements in Python-Redmine code (redminelib/engines/base.py -> process_response() method, check response.status and response.content variables).

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
