### ISSUE TITLE
Filter with assign_to_id, it gave me no result

### ISSUE THREAD

**Issue by komisan19** [maxtepkeev/python-redmine#245]
i want to find a specific user with assign_to_id 10 and query_id 9.
```
redmine.issue.filter(query_id=9, sort='id:desc', assign_to_id=10, limit=100)
```
but, the return result is not the result of the assigned user.
isn't it controlled by API?

**Comment by maxtepkeev** [comment]
It's ``assigned_to_id``, please check the [docs](https://python-redmine.com/resources/issue.html#filter).

**Comment by komisan19** [comment]
If it does not correspond to aasigned_to_id, will I return it with All?

**Comment by maxtepkeev** [comment]
I'm not sure I understood your question.

**Comment by komisan19** [comment]
I changed the argument from assign_to_id to assigned_to_id, 
but it still doesn't work. Are there any other solutions?

**Comment by maxtepkeev** [comment]
Can you please give more details on what exactly doesn't work, what query are you executing, which results do you get ? 

I mean, I've checked and it works, so it's either a problem with a query or with values that you're giving to the filters.

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
