### ISSUE TITLE
How to get watcher list from a issue

### ISSUE THREAD

**Issue by WayneKuo1024** [maxtepkeev/python-redmine#246]
Hi, 

I am tring to retrieve watcher list from issue
But I can only find method to add() or remove() watcher

Is there any method I can get watcher list from issue?

issue = redmine.issue.get(X)
issue.watcher

Thanks a lot!

**Comment by maxtepkeev** [comment]
Everything is in the docs: https://python-redmine.com/resources/issue.html#get

``issue.watchers``

**Comment by WayneKuo1024** [comment]
Thanks,
I tried to upgrade python-redmine package then the watcher list can be retrieved correctly.
