### ISSUE TITLE
Asyncio version

### ISSUE THREAD

**Issue by ekohl** [maxtepkeev/python-redmine#247]
Are there any plans to rewrite the library to use asyncio? I realize this is a big commitment which is why I'm asking it here.

**Comment by maxtepkeev** [comment]
That might happen, but since custom engines are available only in pro version, asyncio won't be a part of a free version for sure.

**Comment by ekohl** [comment]
The thing is, my understanding is that you can't really max an asyncio API with sync code. All functions should be `async def ...` because otherwise you still force code to be synchronous. Otherwise I'd already have looked at a custom aiohttp based engine.

**Comment by maxtepkeev** [comment]
Generally speaking you're right, but since Python's meta programming capabilities are almost infinite, when the time comes to implement asynio support I'll figure something out to make it work.

**Comment by maxtepkeev** [comment]
I believe this can be closed.
