### ISSUE TITLE
redminelib.exceptions.ValidationError after parallel api calls

### ISSUE THREAD

**Issue by eoss-tw** [maxtepkeev/python-redmine#249]
Hi, our applications uses redmine as job status manager. During our processing we got ins some cases (1/100) the following exception from redmine client
```  File "/madxxx/production/madxxx_production/monitoring/pm_jobhandling.py", line 190, in create_production_series
    version.save()
  File "/usr/local/lib/python3.7/dist-packages/redminelib/resources/base.py", line 373, in save
    self._decoded_attrs = self.manager.create(**self._changes).raw()
  File "/usr/local/lib/python3.7/dist-packages/redminelib/managers/base.py", line 162, in create
    response = self.redmine.engine.request(self.resource_class.http_method_create, url, data=request)
  File "/usr/local/lib/python3.7/dist-packages/redminelib/engines/base.py", line 76, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/redminelib/engines/base.py", line 166, in process_response
    raise exceptions.ValidationError(', '.join(': '.join(e) if isinstance(e, list) else e for e in errors))
redminelib.exceptions.ValidationError: Name has already been taken
```

version is hereby a new redmine.version object. I guess that the id it used internally is not unique because one worker has no information about the new versions on other workers. Do you have a solution how the system can create independently new e.g. version objects on different nodes? Right now there is no inter worker communication to share process data.

redmine v4.0.0.stable
py-redmine 2.2.1

Thanks in advance
Thilo

**Comment by maxtepkeev** [comment]
Hi Thilo,

This looks like a typical race condition problem, I don't know the design details of your script, but the basic idea here is to form a queue of data to be saved in Redmine first and to fire the parallel creation of resources only afterwards evenly distributing resources to be created between workers. If currently the creation happens independently there is no way for one worker to know what the other workers have already created. Or you can just skip the Exception and assume that Version resource has already been created by another worker so you can proceed to the next one safely.

**Comment by eoss-tw** [comment]
Yeah, I thought in that direction. Normally the queue ensures that there arent equally executed jobs in the system. Because I used the loosely coupled worker paradigm I wont implement inter worker communication, hence your option 2 will be the way.

Thanks for the clearification
