### ISSUE TITLE
 About partial update of resources

### ISSUE THREAD

**Issue by komisan19** [maxtepkeev/python-redmine#250]
hi, i want to achieve this.
```
        issue = redmine.issue.get(12345)
        issue.assigned_to = "hoge"
        issue.save()
```
However, when I do this, I get an `redminelib.exceptions.ForbiddenError: Requested resource is forbidden` error

Can't update some resources?
thank you

**Comment by maxtepkeev** [comment]
Hi, it should be ``issue. assigned_to_id = X`` where X is the user id. It's all in the docs.

**Comment by komisan19** [comment]
ok,thank you!
After changing the code it worked
