### ISSUE TITLE
Why do the notes require the CRM plugin when they are part of the Redmine API?

### ISSUE THREAD

**Issue by jonfen** [maxtepkeev/python-redmine#251]
Why do the notes require the CRM plugin when they are part of the Redmine API?

Python-redmine notes:
https://python-redmine.com/resources/note.html?highlight=notes

Updating Notes via direct REST API:
https://www.redmine.org/projects/redmine/wiki/Rest_Issues#Updating-an-issue

**Comment by maxtepkeev** [comment]
This is a special Note resource, that is part of RedmineCRM and has nothing to with WikiPage resource, see https://www.redmineup.com/pages/plugins/crm
