### ISSUE TITLE
Company Proxy

### ISSUE THREAD

**Issue by bohniti** [maxtepkeev/python-redmine#252]
Dear Developer,

The connection failed while I tried to connected with our Redmine Server. It seems our company proxy blocks it.

``` python
from django.conf import settings
from redminelib import Redmine

server = Redmine(settings.REDMINE_URL, key=settings.REDMINE_KEY)
project = server.project.get(settings.REDMINE_PROJECT_ID)

print('Project ID:' + project.id)
print('Created on:' + project.created_on)

>>requests.exceptions.ProxyError: HTTPSConnectionPool(host='tools.mobility.siemens.com', port=443): Max retries exceeded with url: /redmine/projects/FXM%20Monitoring%20von%20ICE4-Batterien.json?key=8a22a10337dcb5803ef3562937e146ca42dafa67 (Caused by ProxyError('Cannot connect to proxy.', ConnectionResetError(10054, 'Eine vorhandene Verbindung wurde vom Remotehost geschlossen', None, 10054, None)))
```

I found an [issue ](https://github.com/maxtepkeev/python-redmine/issues/198) which already addressed the problem. The problem is that the provided [link](https://2.python-requests.org//en/latest/api/#requests.request) for further connection settings is no longer available. I would be happy if someone could help by solving the problem or by proving the current documentation link. 

Thank you a lot

**Comment by maxtepkeev** [comment]
Hi @bohniti 

Looks like Requests team changed the link, here's a new one: https://requests.readthedocs.io/en/latest/api/#requests.request

**Comment by bohniti** [comment]
Okay, thank you. I tried the proxy settings, but it doesn't work. 

Any other ideas what could cause the error?

I have contacted the Redmine support and my sysadmin as well. If I get any beneficial advice, I will share it as well.

**Comment by maxtepkeev** [comment]
This looks like a network problem which is most likely should be fixed by your sysadmin.

I don't think we or Redmine support can help here.

**Comment by bohniti** [comment]
Okay, I contacted them already and still waiting for a reply. Thought maybe there is sth else I can do because the other issue sounds similar. 

Anyways, thank you for your support. And if the sysadmin is saying sth which can help the community, I will do that.

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
