### ISSUE TITLE
Export issues descriptions to csv

### ISSUE THREAD

**Issue by A6bIPov** [maxtepkeev/python-redmine#253]
How do I can export all issues columns to csv, including descriptions?
Tried solution from request #221 - it has downloaded csv with all columns, but without issue description.

Another question:
I have tried to use export method with "columns" argument and got an exception:

`issues = redmine.issue.filter(project_id=ID, status_id = '*', cf_21 = '2.0.0')
issues.export('csv', savepath=PATH, filename='issues.csv', columns='all')`

TypeError: export() got an unexpected keyword argument 'columns'

How I can to avoid that exception? I am using Python-Redmine ver. 2.2.1

Thank you in advance.

**Comment by A6bIPov** [comment]
Well I have fixed issue with exception "TypeError: export() got an unexpected keyword argument 'columns'" - just replaced python-redmine package, that was installed using "pip-install" on package from Git. Export method in the package, that available via PIP has no "columns" argument.

But still has no solution, how it is possible to export issues description

**Comment by maxtepkeev** [comment]
Hi @A6bIPov,

Yes, the column export functionality isn't available in PyPI yet, but will be, so if you need it right now you did the right thing.

Regarding your question about description, try using `.export('csv', savepath=PATH, filename='issues.csv', columns=['all_inline', 'description'])`

**Comment by A6bIPov** [comment]
`.export('csv', savepath=PATH, filename='issues.csv', columns=['all_inline', 'description'])`

Thank you so much, this is exactly what I need
