### ISSUE TITLE
Freeze when im trying to get all issues.

### ISSUE THREAD

**Issue by dmahmutov** [maxtepkeev/python-redmine#255]
I'm trying to <issues_all = redmine.issue.all()>, but when im trying to run through them. Code freezes. 
How can I get issues partially?

**Comment by dmahmutov** [comment]
limit parameter helped me, but is it necessary to add <limit> parameter to get all issues? or its bug?

**Comment by maxtepkeev** [comment]
all() method returns all issues, that's why it's called all. If you don't need all, you can either use limit/offset functionality or filter method instead of all.

P.S. The code doesn't freeze, most likely you have a lot of issues that's why it takes time to retrieve all of them

**Comment by maxtepkeev** [comment]
Closed due to the lack of activity.
