### ISSUE TITLE
reading of user notified_project_ids and mail_notification 

### ISSUE THREAD

**Issue by APWK** [maxtepkeev/python-redmine#258]
Hey, 

I tried to read 'notified_project_ids' and 'mail_notification'  from users and followed the [description ](https://python-redmine.com/resources/user.html?highlight=notified_project_ids).
```
red_server = connect_server()
user = red_server.user.get(1)
```

'user' contains in my case only:
`[('issues', None), ('time_entries', None), ('memberships', None), ('groups', None), ('id', id), ('login', ''), ('firstname', ''), ('lastname', ''), ('mail', ''), ('created_on', ''), ('last_login_on', ''), ('api_key', ''), ('status', 1)]
`

I also tried it with 
`        users = red_server.user.get(86, include=['mail_notification', 'notified_project_ids'])
`

Funny thing is that pushing 'notified_project_ids' and 'mail_notification' updates works fine:
`response = red_server.user.update(86, mail_notification='selected', notified_project_ids=[68])
`

I thought it has to do with admin right, which is not the case. Any ideas, what I am doing wrong? How can I pull the 'notified_project_ids' and 'mail_notification' information with API?
Help is very much appreciated. Thank you!

**Comment by maxtepkeev** [comment]
Hi,

I don't think it's available through API for reading. You can check this by yourself visiting the following URL: http(s)://your-redmine-url/users/ID.json, where ID is user id you're interested in, for example if you check the demo server http://demo.redmineup.com/users/11.json you will see that there's no such attributes as mail_notification or notified_project_ids, i.e. they're accepted by Redmine API when you create or update the user, but not exposed through the API for reading.

**Comment by APWK** [comment]
Thanks for the feedback. A colleague pointed that out as well. I just didn't think so if it is available for the creation and updating process. Why would it not be available for reading too...

**Comment by maxtepkeev** [comment]
Totally agree with you.

Unfortunately Redmine API is very inconsistent in many cases. You can fill a bug report on their forum, maybe they will fix this someday.

**Comment by APWK** [comment]
alright- thanks again
