### ISSUE TITLE
How I use filter find all  created_on after sometime ?

### ISSUE THREAD

**Issue by SAMZONG** [maxtepkeev/python-redmine#259]
Hi

I just use redmine.issue.filter()  find created after 2020-05-01 00:00:00  ALL CASEs.

```
In [77]: issues = redmine.issue.filter(issue.created_on > datetime.date(2020,5,30))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-77-70aba3f22bd0> in <module>
----> 1 issues = redmine.issue.filter(issue.created_on > datetime.date(2020,5,30))

TypeError: filter() takes 1 positional argument but 2 were given

In [78]: issue.created_on
Out[78]: datetime.datetime(2020, 5, 29, 4, 47, 35)

In [79]: redmine.issue.filter(issue.created_on >= datetime.datetime(2020, 5, 29, 4, 47, 35))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-79-52ea727d510b> in <module>
----> 1 redmine.issue.filter(issue.created_on >= datetime.datetime(2020, 5, 29, 4, 47, 35))

TypeError: filter() takes 1 positional argument but 2 were given
```
What I do bad ?  anybody can help ? 

thanks.

**Comment by maxtepkeev** [comment]
You should use keyword arguments as shown in the docs, i.e. ``redmine.issue.filter(created_on=> datetime.date(2020,5,30))``

**Comment by SAMZONG** [comment]
> thanks comments, but have an another error

In [109]: list(redmine.issue.filter(created_on='>2020-05-31'))
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-109-b6c23414a98c> in <module>
----> 1 list(redmine.issue.filter(created_on='>2020-05-31'))

/usr/local/lib/python3.7/site-packages/redminelib/resultsets.py in __iter__(self)
    303         Returns requested resources in a lazy fashion.
    304         """
--> 305         return (self.manager.to_resource(resource) for resource in super(ResourceSet, self).__iter__())

/usr/local/lib/python3.7/site-packages/redminelib/resultsets.py in __iter__(self)
    136             try:
    137                 self._resources, self._total_count = self.manager.redmine.engine.bulk_request(
--> 138                     'get', self.manager.url, self.manager.container, **self.manager.params)
    139             except exceptions.ResourceNotFoundError as e:
    140                 if self.manager.resource_class.requirements:

/usr/local/lib/python3.7/site-packages/redminelib/engines/base.py in bulk_request(self, method, url, container, **params)
     94         limit = params.get('limit') or 0
     95         offset = params.get('offset') or 0
---> 96         response = self.request(method, url, params=dict(params, limit=limit or self.chunk, offset=offset))
     97
     98         # Resource supports limit/offset on Redmine level

/usr/local/lib/python3.7/site-packages/redminelib/engines/base.py in request(self, method, url, headers, params, data)
     81         """
     82         kwargs = self.construct_request_kwargs(method, headers, params, data)
---> 83         return self.process_response(self.session.request(method, url, **kwargs))
     84
     85     def bulk_request(self, method, url, container, **params):

/usr/local/lib/python3.7/site-packages/redminelib/engines/base.py in process_response(self, response)
    176         elif status_code == 422:
    177             errors = response.json()['errors']
--> 178             raise exceptions.ValidationError(', '.join(': '.join(e) if isinstance(e, list) else e for e in errors))
    179         elif status_code == 500:
    180             raise exceptions.ServerError

ValidationError: 创建于 是无效的  (translate to english: Create on is validationError)

- I try use `start_date`,  but got same error response.

**Comment by SAMZONG** [comment]
@maxtepkeev  I get question.

can not use '>2020-05-30' , but  '>=2020-05-30' is right.

**Comment by chrisdaloa** [comment]
hi, whats the correct way to use a filter "beetween" date? for eample from '2023-01-01' to '2023-31-01'
Thanks

**Comment by maxtepkeev** [comment]
@chrisdaloa Should be `><2023-01-01|2023-01-31`
