### ISSUE TITLE
Get Issues by Query ID

### ISSUE THREAD

**Issue by PetruLunguGartner** [maxtepkeev/python-redmine#260]
Hi,
It's possible to search issues by QueryID?
The Redmine(address, api_key).query.get(query_id) returns QueryName, QueryID, etc... but I need to have Issues assigned to this QueryID.

It's possible to search issues by QueryID?

Thanks.

**Comment by maxtepkeev** [comment]
Hi,

Have you tried ``redmine.issue.filter(query_id=QID)`` where QID is query id ?

**Comment by PetruLunguGartner** [comment]
Hi Max,
looks like works... returns <redminelib.resultsets.ResourceSet object with Issue resources>
but not able to iterate it or to get something from.

Please help.
Спасибо

**Comment by maxtepkeev** [comment]
Hey,

What do you mean by "not able to iterate", ResourceSet **is** iterable, i.e.

```python
for issue in redmine.issue.filter(query_id=QID):
    print('{}: {}'.format(issue.id, issue.subject))
```

most likely if you don't get anything, then there're no issues for this query id

Let me know if it helps.

Cheers.

**Comment by PetruLunguGartner** [comment]
this throws: "redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist"
Have ~1000 Issues for this query.
I can see them in browser. /projects/pr_name/issues?query_id=430

**Comment by PetruLunguGartner** [comment]
This works:
        for issue in self.__redmine__.issue.filter(query_id=p_query_id, project_id=self.__project_id__):
            print('{}: {}'.format(issue.id, issue.subject))

Thanks.

**Comment by maxtepkeev** [comment]
Yeah, forgot about the project_id, good to know you made it work. Thx.

**Comment by Doezer** [comment]
Hey,
I spent half an hour trying to figure out why my request based only on query id wasn't working before finding this, so thanks.
Although I believe it could be told in the documentation, at this point: https://python-redmine.com/resources/issue.html#filter.
Just thought it could improve it so I made a PR: #285
