### ISSUE TITLE
issue_custom_field_ids not working?

### ISSUE THREAD

**Issue by sigttou** [maxtepkeev/python-redmine#268]
Hi,

getting the issue custom fields does not work:

```
p = redmine.project.get(78)
p.issue_custom_fields_ids
.
.
ResourceAttrError: Resource doesn't have the requested attribute
```

Setting it and saving works, but after getting it again, it's not changed.
```
p = redmine.project.get(78)
p.issue_custom_fields_ids = [1,5]
p.save()
p.issue_custom_fields_ids
Out[81]: [1, 5]
p = redmine.project.get(78)
p.issue_custom_fields_ids
.
.
ResourceAttrError: Resource doesn't have the requested attribute
```
Changes to the settings in Redmine do not change or enable the given issue fields for the project. (settings->issue tracking->custom fields, remain the same.)

**Comment by maxtepkeev** [comment]
Hi,

You can only set/update them, not get, it's a limitation of Redmine API, so there's nothing we can do here unless they add support for it.

**Comment by sigttou** [comment]
Thank you for your answer.

The mistake was a typo in `issue_custom_field_ids`, sorry.
