### ISSUE TITLE
[question] Filter versions with due_date between two given date

### ISSUE THREAD

**Issue by SajadJalilian** [maxtepkeev/python-redmine#269]
I need to filter issues where issue fixed_version due date is between two given date.
For example versions which they due_date is in current month.
I tried everything I could think of, but I couldn't figure it out.

**Comment by maxtepkeev** [comment]
@SajadJalilian You can use fixed_version parameter together with created_on for a date range, i.e. ><2021-03-01|2021-03-07 which means between 1st and 7th of March 2021

**Comment by SajadJalilian** [comment]
@maxtepkeev Thank you.
For the record.

This query works just fine:
‍‍`redmine.issue.filter(assigned_to_id=250, status_id=5, fixed_version__updated_on=f'><2021-01-20|2021-02-18')`
But I have no luck with this one :(
`redmine.issue.filter(assigned_to_id=250, status_id=5, fixed_version__due_date=f'><2021-01-20|2021-02-18')`

It seems because 'due_date' is not present in all issues but 'updated_on' is.

**Comment by maxtepkeev** [comment]
I was actually thinking about:

`redmine.issue.filter(assigned_to_id=250, status_id=5, fixed_version=123, due_date=f'><2021-01-20|2021-02-18')`

Have you tried doing it this way ?

**Comment by SajadJalilian** [comment]
Unfortunately I'm not working on that project anymore and I can not test. Thank you I really appreciate your help
