### ISSUE TITLE
authenticating to both Webserver and Redmine

### ISSUE THREAD

**Issue by dpocock** [maxtepkeev/python-redmine#273]
Some users set up HTTP Digest authentication to protect the web server.  Users have to log in twice: first they authenticate to the web server or proxy, then they login through the Redmine login form.  How can python-redmine handle both challenges, both sets of credentials?

**Comment by maxtepkeev** [comment]
@dpocock Hi, I believe this is beyond the scope of the problems that Python-Redmine should be able to solve. If some users have authentication on top of the Redmine they're suppose to handle it in their own scripts.
