### ISSUE TITLE
The program freezes during a request

### ISSUE THREAD

**Issue by BigForLy** [maxtepkeev/python-redmine#274]
I want to receive data by request:
`redmine_connection = Redmine('http://link/redmine', key=REDMINE_API)`
`while True:`
`set_issues_update = list(redmine_connection.issue.filter(status_id=string_list_status, project_id=CurrentProjectId, assigned_to_id=self.list_users_to_string).values())`
For a while, everything runs flawlessly, but after a while the program freezes in this place. It may not die off for several days. There is nothing in the log. the list itself is executed in a loop. What could be the problem? Or tell me where to see the error

**Comment by BigForLy** [comment]
![image](https://user-images.githubusercontent.com/71991260/112899347-7a6bac80-90fb-11eb-9efd-19e3ccd41cd0.png)

**Comment by BigForLy** [comment]
> maybe need usage session, but i see expected type
> ![image](https://user-images.githubusercontent.com/71991260/112899347-7a6bac80-90fb-11eb-9efd-19e3ccd41cd0.png)

No, freezes not stoped

**Comment by maxtepkeev** [comment]
Hi, this can happen if your Redmine has lots of data and you don't limit/filter it. Have you tried appending a limit or filter and see if that helps ?

**Comment by BigForLy** [comment]
> Привет, это может произойти, если в вашем Redmine много данных, и вы не ограничиваете / не фильтруете их. Вы пробовали добавить ограничение или фильтр и посмотреть, поможет ли это?

this happens even when the task list is 36

**Comment by BigForLy** [comment]
> Hi, this can happen if your Redmine has lots of data and you don't limit/filter it. Have you tried appending a limit or filter and see if that helps ?

this happens even when the task list is 36

**Comment by BigForLy** [comment]
I have a couple more ideas, I will write about them when I collect more information

**Comment by BigForLy** [comment]
![image](https://user-images.githubusercontent.com/71991260/115184254-dd4ad500-a0f6-11eb-9e21-bf811a55e01c.png) 
This code freezing about underline string
count set_issues_update is from 25 to 40

**Comment by BigForLy** [comment]
![image](https://user-images.githubusercontent.com/71991260/115184650-b93bc380-a0f7-11eb-98d8-92503b64ac88.png)
blue = fine complite
red = bed complite, this last log string

**Comment by BigForLy** [comment]
I create a request in a thread, after a while I cannot stop it, then nothing happens
My request_method:
![image](https://user-images.githubusercontent.com/71991260/117892426-20e9c680-b2d2-11eb-88c2-1b75c2967e01.png)
My program:
![image](https://user-images.githubusercontent.com/71991260/117892265-d2d4c300-b2d1-11eb-9d68-d97317356b95.png)
Log try and false my request:
![image](https://user-images.githubusercontent.com/71991260/117892344-031c6180-b2d2-11eb-877d-3e596b680d2a.png)

**Comment by maxtepkeev** [comment]
Hi @BigForLy 

Apologies about the delay with an answer, your code (without threading) is fine and doesn't hang, your problem comes from incorrect threading usage. It's a bit tricky to make Python-Redmine work and benefit from threading and if you need that functionality there is a [PRO](https://python-redmine.com/editions.html#pro-edition) version that has threading and multiprocessing support, but only for read operations e.g. `filter()` and `all()`.
