### ISSUE TITLE
How could i count the people on each project

### ISSUE THREAD

**Issue by ThierryHenry1994** [maxtepkeev/python-redmine#275]
Hi，i want to count all users of each project.
I used "users = redmine.user.all() " 
but how could i print all users onto consle

thanks

**Comment by ThierryHenry1994** [comment]
add my try

for i in users:
    print(i)

but failed
![image](https://user-images.githubusercontent.com/32047768/112965900-48e6f580-917c-11eb-8c17-8980219f68d0.png)

**Comment by BigForLy** [comment]
Use 
`users = list(redmine.user.all())`

**Comment by ThierryHenry1994** [comment]
> Use
> `users = list(redmine.user.all())`

it doesn't work but thanks for your advices. Do I have to have administrator privileges？
![image](https://user-images.githubusercontent.com/32047768/113002209-249f0f00-91a4-11eb-87bf-04517699bffc.png)

**Comment by BigForLy** [comment]
> > Use
> > `users = list(redmine.user.all())`
> 
> it doesn't work but thanks for your advices. Do I have to have administrator privileges？
> ![image](https://user-images.githubusercontent.com/32047768/113002209-249f0f00-91a4-11eb-87bf-04517699bffc.png)

Do I have to have administrator privileges？ YES
I'm not sure, but without administrator rights, you can only watch your actions

**Comment by BigForLy** [comment]
![image](https://user-images.githubusercontent.com/71991260/113028638-eeae5a80-91a4-11eb-9812-86f625c35f13.png)

**Comment by BigForLy** [comment]
![image](https://user-images.githubusercontent.com/71991260/113028694-02f25780-91a5-11eb-9ba5-e366390f28e6.png)

**Comment by ThierryHenry1994** [comment]
Thank for your show.I will try to get administrator rights.Back to my original question，how to count member in my project.
My target is count all projects and their members.Thank you again for your reply

**Comment by ThierryHenry1994** [comment]
![image](https://user-images.githubusercontent.com/32047768/113075856-5f369500-9200-11eb-8d4b-988822a461f2.png)
I don't find interface to get project's member

**Comment by ThierryHenry1994** [comment]
I have got the way to resolve my problem fortunately.

 for i in list(project.memberships.values()):
      print(i)
