### ISSUE TITLE
Validation error without message

### ISSUE THREAD

**Issue by Francesko90** [maxtepkeev/python-redmine#276]
Hi

I started to use your library (thanks for the great works) version 2.3.0 with Python 3.6.9

I try to create a wikipage with following script 

```
from redminelib import Redmine

redmine = Redmine('https://redmine.organization.it', username='---', password='----')
wiki_page = redmine.wiki_page.new()
wiki_page.project_id = 'project-id'
wiki_page.title = 'FooBar'
wiki_page.text = 'foo'
wiki_page.parent_title = 'Yada'
wiki_page.comments = 'bar'
wiki_page.save()
```

 But I receive following error
 
```
 Traceback (most recent call last):
  File "redmine.py", line 10, in <module>
    wiki_page.save()
  File "/home/fcaronte/.local/lib/python3.6/site-packages/redminelib/resources/base.py", line 388, in save
    resource = self.manager.create(**self._changes)
  File "/home/fcaronte/.local/lib/python3.6/site-packages/redminelib/managers/base.py", line 187, in create
    response = self.redmine.engine.request(self.resource_class.http_method_create, url, data=request)
  File "/home/fcaronte/.local/lib/python3.6/site-packages/redminelib/engines/base.py", line 83, in request
    return self.process_response(self.session.request(method, url, **kwargs))
  File "/home/fcaronte/.local/lib/python3.6/site-packages/redminelib/engines/base.py", line 178, in process_response
    raise exceptions.ValidationError(', '.join(': '.join(e) if isinstance(e, list) else e for e in errors))
redminelib.exceptions.ValidationError
```

In other issues I see that the validation error have  a message, but in this case the message is empty

**Comment by maxtepkeev** [comment]
@Francesko90 Hi, ValidationError comes directly from Redmine, so if you see an empty message there can be 2 reasons for this:

1) Redmine itself returned empty message
2) Redmine returned non-empty message but it was structured in a way Python-Redmine didn't expect it to be

You can find out the truth by debugging a response in engines/base.py process_response method.

**Comment by Francesko90** [comment]
@maxtepkeev thanks for the feedback, I investigate (without debugging but with REST Api) our redmine return the error code 422 with error type empty

```
<?xml version="1.0" encoding="UTF-8"?>
<errors type="array"></errors>
```

I try with another redmine instance and works fine
