### ISSUE TITLE
ServerError trying to relate two issues in Redmine 4.2.0

### ISSUE THREAD

**Issue by guillermoml** [maxtepkeev/python-redmine#277]
This code:
`issue_relation.create(
        issue_to_id=3450,
        issue_id="3449",
        relation_type='relates'
    )`

fails in Redmine 4.2.0. The error is:
`redminelib.exceptions.ServerError: Redmine returned internal error, check Redmine logs for details`

Inside the log you can see:
`Completed 500 Internal Server Error in 288ms (ActiveRecord: 155.8ms)  
NoMethodError (undefined method 'split' for 3450:Integer):
app/controllers/issue_relations_controller.rb:110:in 'relation_issues_to_id'
app/controllers/issue_relations_controller.rb:51:in 'create'
`

It's **not** a python-redmine bug, it's a Redmine bug: https://redmine.org/issues/35039 where the creator of redmine-java-api reported the same error.

To avoid it you can convert both issue_to_id and issue_id to strings.

It only affects 4.2.0 and it will be addressed in 4.2.1. I just wrote the issue to warn people to be aware of this Redmine's bug.

**Comment by guillermoml** [comment]
I applied Marius' patch for Redmine created in issue https://redmine.org/issues/35039 and can confirm that works perfectly.
As a workaround you can convert issues' ids from integer to string to keep working if you can't patch the Redmine instance.

**Comment by maxtepkeev** [comment]
@guillermoml Many thanks for the info!
