### ISSUE TITLE
[Question] Any way to use Redmineup agile fields?

### ISSUE THREAD

**Issue by Doezer** [maxtepkeev/python-redmine#286]
Hi,
I'd like to be able to do some operations on story points, which are available in RedmineUP agile plug-in: https://www.redmineup.com/pages/plugins/agile

I'm guessing if it were to be available it would be in the pro version as for checklists. But is it possible to get it anyway, maybe with a more raw version of the "raw()" method? Or does the redmine API simply doesn't send it at all?

Thanks

**Comment by maxtepkeev** [comment]
Hi,

At the moment this isn't supported even in a pro version, there are plans to add support for this, but currently no ETA.

The RedmineUP Agile plugins does have an API for agile data, you can have a look at the docs here https://www.redmineup.com/pages/help/agile/rest-api-agile-data and with some programming you can implement a few calls to the endpoint and then merge the received data with the data returned from Python-Redmine.

**Comment by Doezer** [comment]
Thanks for the info!

**Comment by Doezer** [comment]
If anyone finds this issue and needs a bit of guidance, here's the code:
```
import requests
rep = requests.get(url=f'{redmine_server}/issues/{issue_id}/agile_data.json', 
                   headers={'X-Redmine-API-Key': api_key})
return rep.json()["agile_data"]["story_points"]
```

There are other ways to [authenticate](https://www.redmine.org/projects/redmine/wiki/Rest_api#Authentication)
