### ISSUE TITLE
issue.uploads problem

### ISSUE THREAD

**Issue by smilesheep** [maxtepkeev/python-redmine#287]
Hi,
I'm using **Redmine 4.1.1.stable**, Environment:
>   Redmine version                4.1.1.stable
>   Ruby version                      2.5.8-p224 (2020-03-31) [x86_64-linux]
>   Rails version                       5.2.4.2

When I use the **issue.uploads** method, I got an error 'NoMethodError (undefined method `start_with?' for #<ActionController::Parameters:0x00007f99ad2520d0>)'. **Redmine Log Details** are:
```
Completed 500 Internal Server Error in 62ms (ActiveRecord: 8.6ms)
  
NoMethodError (undefined method `start_with?' for #<ActionController::Parameters:0x00007f99aee11c08>):
  
plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:20:in `block in save_attachments'
plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:19:in `each'
plugins/clipboard_image_paste/lib/clipboard_image_paste/attachment_patch.rb:19:in `save_attachments'
app/controllers/issues_controller.rb:169:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'
```
Please help me, Thanks!!

**Comment by maxtepkeev** [comment]
Hi,

That's an internal error in Redmine, so I can't help here, I can only suggest to update to the latest version, be sure you don't have any plugins installed, if you do, remove them first and try afterwards, there are a lot of reports when some plugin can mess everything up, and the latest - raise an issue at the Redmine forum.

**Comment by smilesheep** [comment]
Thank you for your suggestion. :)
