### ISSUE TITLE
Filter by relations?

### ISSUE THREAD

**Issue by supermitch** [maxtepkeev/python-redmine#288]
The Redmine GUI can filter issues "Related to" with many options:

<img width="110" alt="image" src="https://user-images.githubusercontent.com/1152280/125534685-ad06c999-c022-49d8-b09c-bafc83a255e5.png">

Are these options available via the API or Python-Redmine? I have searched everywhere and can't find anything.

I know I can include relations, but these relations are just other issue IDs. I still wouldn't be able to manually do "... in project" filtering without a second get for that individual issue, to determine which project it's in. Right?

**Comment by supermitch** [comment]
I can partially answer my own issue (that I forgot I'd created): By URL decoding a UI query URL, I was able to discovery that you can add `'relates': '!*'` in your query, and you will filter out issues with relations. For example:

```
redmine.issue.filter(
        **{
            'tracker_id': 20,
            'status_id': '*',
            'relates': '!*',
            'include': 'relations',
        }
)
```

seems to be working. I haven't experimented with other `relates` queries, but this seems to return only issues without relations.

**Comment by maxtepkeev** [comment]
Hi @supermitch 

Apologies for the delayed answer and thanks for posting your solution which is absolutely correct.

You can find other possible relate operators [here](https://www.redmine.org/projects/redmine/repository/entry/trunk/app/models/query.rb#L327).

There's additional information regarding tricky uses of operators in other resources in #57 and #205. I really need to find some time and add all these pieces of knowledge to the docs.
