### ISSUE TITLE
issue.filter - redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't existHi,

### ISSUE THREAD

**Issue by Raoul555** [maxtepkeev/python-redmine#291]
Hi,

I'm trying to retrieve all issue from a specific query. I know the query_id, so I do:
```
(Pdb) response = self.redmine.issue.filter(query_id=1563)
(Pdb) L = list(response)
```

Query 1563 is own by me. It shows issues in the redmine GUI (with the URL https://<my_redmine_hostname>/projects/rd/issues?query_id=1563)

But this code return me:
```
(Pdb) L = list(response)
*** redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist
```

Version, python 3.9:
```
(Pdb) redminelib.__version__
'2.3.0'
```

I don't see what I'm doing wrong, so wondering if this is not a bug.

Thanks,
Raoul.

**Comment by guillermoml** [comment]
> I think it's the same as #60

I accidentally deleted a number, it's #260, not 60.
You need to include the _project_id_.

**Comment by maxtepkeev** [comment]
Yes, you have to include a project_id. Docs are updated with that info.
