### ISSUE TITLE
missing attributes causes exceptions

### ISSUE THREAD

**Issue by duaneellissd** [maxtepkeev/python-redmine#293]
In our case - redmine authenticates with LDAP - so - for example users do not have a password in redmine, and thus the passwd_changed_on user field does not exist for all users.

But, when you print the attributes of a user, or do something that causes the "passwd_changed_on" field to be fetched - and it does not exist - the application crashes because that field does not exist in the "user"

Example:
```python
    
server = Redmine(url=cfg['url'], key=cfg['key'],requests={'verify':False})

thisuser = server.user.get('current')
print("thisuser pwchange on: %s" % thisuser.passwd_changed_on )
Thi
```
fails  horribly throwing an exception, it should not.

In this simple case - The getattr() function should support a default value  but this is sort of pervasive 
ie: if an issue does not have  field accessing the issue crashes in simular ways

This type of problem occurs in multiple places in just about every type of thing - making it really hard to figure what attribute is missing. I have had to resort to modifying the library source code to print the missing/offending attribute name - I should not have to do that.

While "technically correct" the  implementation choices makes the API presented very brittle and fragile and super crash prone, sigh :-(

Perhaps if the attribute is missing - the library should substitute NONE for this item.

**Comment by maxtepkeev** [comment]
Hi, sorry that it took me one year to reply...

Have you checked the docs before trying to modify the library code ? There is already a solution to your problem here: https://python-redmine.com/configuration.html#exception-control

**Comment by maxtepkeev** [comment]
Closing as resolved, feel free to reopen if I'm missing something or you have additional questions.
