### ISSUE TITLE
Not possible to generate issue preview

### ISSUE THREAD

**Issue by n158** [maxtepkeev/python-redmine#294]
While editing issue in web, there is possibility to press preview to see parsed textile formatting. In this case the web page send to server this request:
POST https://redmine.host.com/issues/preview/edit/3783?project_id=some_project

In this project this functionality is not implemented. Are there any possibility to get it in the future release?

**Comment by maxtepkeev** [comment]
Hi @n158 

It's a GUI only feature which isn't available via Redmine's REST API and since Python-Redmine communicates with Redmine via this REST API there's no way for us to implement this feature until it will be available via Redmine's REST API.
