### ISSUE TITLE
File downloaded with redmine.download() is corrupt

### ISSUE THREAD

**Issue by newnewcoder** [maxtepkeev/python-redmine#296]
I download issue's attachment by using `redmine.download()`, it's work well most of time, but sometimes the file gets corrupted and no exception occurs. I tried opening the file via a text editor and found the login page html code in there, has anyone encountered this and how to prevent it?

**Comment by maxtepkeev** [comment]
Hi @newnewcoder 

Apologies for such a late reply.

I've checked the code to be sure and we always pass the authentication information to Redmine when `redmine.download()` method is used. My guess is that you might have installed some plugin which broke issue downloading for some attachments as it already happened before for some people, so if the problem still persists I would suggest to disable all plugins and see if that helps, if yes start turning them on one by one to see which is causing the problem.

If it's not a plugin problem feel free to reopen a new issue, but please provide more details, the exact code you're using, your python-redmine version, redmine version, requests version etc.
