### ISSUE TITLE
Custom queries example

### ISSUE THREAD

**Issue by albasili** [maxtepkeev/python-redmine#297]
I'd like to fetch the issues in my custom queries and use them to programmatically generate my Changelog (or a section of it). Unfortunately while I was able to fetch project object and individual issues, i did not get anything in return for custom queries.

Is there an example I can try out? Are there any options ti debug what's happening?

I also thought there might be an acess right issue, but I'm using my own API key and I own those custom queries, so I shouldn't have access rights problems. 

Thanks for any hint!

**Comment by maxtepkeev** [comment]
Hi @albasili 

Apologies for the delay with an answer.

To get custom queries you can use `redmine.query.all()` or `redmine.query.get(ID)` if you know the id beforehand, see [docs](https://python-redmine.com/resources/query.html).

But most likely you have the same problem as in #260 and #291 i.e. in order for a `query_id` filter to work in `issue.filter()` you also have to provide a `project_id` filter at the same time.

You can also check the [introspection](https://python-redmine.com/introduction.html#introspection) part, if you haven't already, for some tiny little tricks which can help you understand what exactly was returned from Redmine.

Closing this as resolved, but feel free to reopen if you have additional questions.
