### ISSUE TITLE
How to use API to manage document tab module?

### ISSUE THREAD

**Issue by ImageWQ** [maxtepkeev/python-redmine#299]
I tried to read the information in the project document and download the file, but I couldn't find the solution. Do you have a good method? Thank you for your contribution!

**Comment by maxtepkeev** [comment]
Hi @ImageWQ 

Python-Redmine is a client to the Redmine's REST API, so it supports only what's available via that API and I'm afraid there's no endpoint for documents there.

There are issues on their forum like [this](https://www.redmine.org/issues/18245) and [this](https://www.redmine.org/issues/21378) which were submitted 8 and 7 years ago and didn't get much attention unfortunately.

Until Redmine implements Document support in their REST API there's nothing we can do here in Python-Redmine.
