### ISSUE TITLE
time_entry_activities support for project creation

### ISSUE THREAD

**Issue by lbayerlein** [maxtepkeev/python-redmine#302]
Hi,

I have a question about creating new projects. Here is an example snippet:

```
project = redmine.project.create(
    name=pr_name,
    identifier=pr_id_name,
    description=pr_description,
    is_public=False,
    parent_id=parent_project,
    inherit_members=False,
    tracker_ids=pr_tracker_ids,
    enabled_module_names=['issue_tracking', 'time_tracking', 'issue_templates'],
    time_entry_activities=[{"id": 30, "name": "test"}]
)
```

All variables are set and the project is created. The `time_entry_activities` are default and should be configured with an `create` or an `update` function. But that does not work. Where is my mistake or hasn't it been supported, yet?

Thanks

**Comment by maxtepkeev** [comment]
Hi @lbayerlein 

Yes, this isn't supported by Redmine's REST API itself, when they start supporting it, your example will work straight out of the box in Python-Redmine as we don't hardcode any attributes/params.

You can fill a feature request on their forums.
