### ISSUE TITLE
add start time and end time in python-redmine library

### ISSUE THREAD

**Issue by Adityashah007** [maxtepkeev/python-redmine#304]
I am using that meeting plugin  of Redmine but your library is unable to fetch the details that are now present in Redmine like start time and end time  plz do something or tell me an alternate so I'd be able to do this

**Comment by maxtepkeev** [comment]
@Adityashah007 In order for Python-Redmine to get information from that meeting plugin, it has to have either a REST API endpoint or inject it's data into existing Redmine endpoints and this plugin does none of that, so Python-Redmine can't help you until the developers of this plugin make one of the changes described above.
