### ISSUE TITLE
Sorting by two columns

### ISSUE THREAD

**Issue by mvidelgauz** [maxtepkeev/python-redmine#305]
I am trying to sort fetched issues by two columns, and following the documentation https://python-redmine.com/resources/issue.html#filter I first wrote
`redmine.issue.filter(..., sort = 'priority:desc')`

But now, I want to sort the result also by the issue ID, within each priority. I found a sample at https://www.redmine.org/projects/redmine/wiki/Rest_Issues that looks like `sort=category:desc,updated_on`
so I tried adding this to my query:
`redmine.issue.filter(..., sort = 'priority:desc, id')`
(tests with sort = 'id' and sort = 'id:desc' alone show that the "id" is correct name of the column)

But that didn't work - the result is still sorted only by priority

**Comment by maxtepkeev** [comment]
Hi, @mvidelgauz 

Sorting by 2 columns works, but there should be no space between comma and the second field, i.e.:
`redmine.issue.filter(..., sort = 'priority:desc,id')`

Can you try that and reply back if that worked for you ?

**Comment by maxtepkeev** [comment]
Closing as resolved, feel free to reopen if I'm missing something or you have additional questions.
