### ISSUE TITLE
Issue Filters with Custom Field

### ISSUE THREAD

**Issue by mrhatch** [maxtepkeev/python-redmine#306]
Looking at the documentation it states I can do the following:
issues = redmine.issue.filter(
    project_id='vacation',
    cf_22='~foo'
)

When I do this I get 0 results, if I change it to:

issues = redmine.issue.filter(
    project_id='vacation',
    cf_22=1
)

I get the expected results.  The custom field is of type key/value list

**Comment by maxtepkeev** [comment]
Hi @mrhatch 

I'm not quiet sure what your question is, the first code sample is just an example and cf_22='~foo' means we want to get issues with custom field with id 22 contains the substring "foo", so if you don't have issues with cf id 22 for such a condition you're obviously getting 0 issues and you have to tweak an example for you case which as I understand you already did.

**Comment by maxtepkeev** [comment]
Closing as resolved, feel free to reopen if I'm missing something or you have additional questions.
