### ISSUE TITLE
Get Issue IDs for already existing issues.

### ISSUE THREAD

**Issue by redmineuser1234** [maxtepkeev/python-redmine#307]
Hello, I am trying to grab the issue ID of issues that have already been created. So far, the only thing I can find that is along the lines of the information I am trying to access is:

> redminelib.managers.ResourceManager.get(resource_id)

However, this only returns the status ID of the issue, not a unique identifier for that specific information. Is there a way to access that info?

**Comment by maxtepkeev** [comment]
Hi, have you read the docs (https://python-redmine.com/resources/issue.html#read-methods) ?

After you've retrieved your issue(s) in on of the ways described in the docs, you can get it's id by accessing id attribute, i.e. `issue.id`
