### ISSUE TITLE
Nose for testing is deprecated

### ISSUE THREAD

**Issue by orlitzky** [maxtepkeev/python-redmine#312]
Distributions are removing nose because the upstream project has been dead for a long time. See, for example, https://fedoraproject.org/wiki/Changes/DeprecateNose -- although in my case it's Gentoo that is affected.

In short, python-redmine should probably switch to nose2 or pytest, as suggested by https://nose.readthedocs.io/en/latest/.

**Comment by maxtepkeev** [comment]
Switched to pytest in 7b85b9691c02084615f3d96b6d1c7da370ea0561. Thanks.

**Comment by orlitzky** [comment]
Great, thank you!
