### ISSUE TITLE
Issues.export have any export limits?

### ISSUE THREAD

**Issue by EgorKrasnov** [maxtepkeev/python-redmine#314]
Hello! I have a question about issues.export. After reading 
> issues = redmine.issue.filter(project_id='176',status_id='*')
len(issues) return correct values - 626

But after export i have only 500 rows in file 
> issues.export('csv', savepath='./', filename='issues.csv', columns='all')

I didnt find any limits in documentation https://python-redmine.com/resources/issue.html and same functionality 
> entries = redmine.time_entry.filter(from_date='2023-01-01')
> entries.export('csv', savepath='./', filename='entries.csv', columns='all')

easilly exporting more than 500 rows :) 

How can i fix this? Thank you!

**Comment by maxtepkeev** [comment]
Hi @EgorKrasnov 

This has nothing to do with Python-Redmine, it's a configurable limit on Redmine side which you can change in Administration -> Settings -> Issue Tracking -> Issue export limit, the default value is 500.

**Comment by EgorKrasnov** [comment]
Even in my thoughts it was not to check the redmine settings. Thanks a lot! Good luck! :)

**Comment by maxtepkeev** [comment]
No problem, you're welcome.
