### ISSUE TITLE
Not able to update journals

### ISSUE THREAD

**Issue by dreace1** [maxtepkeev/python-redmine#315]
Hey, when I try to update journals I get the following error.
```shell
Traceback (most recent call last):
  File "d:\vscode-workspace\jedmine\redmine_parser.py", line 102, in <module>
    print(journal.save(notes=""))
          ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\redminelib\resources\base.py", line 398, in save
    self.manager.update(self.internal_id, **self._changes)
  File "D:\python\Lib\site-packages\redminelib\managers\base.py", line 251, in update
    response = self.redmine.engine.request(self.resource_class.http_method_update, url, data=request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\redminelib\engines\base.py", line 83, in request
    return self.process_response(self.session.request(method, url, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\site-packages\redminelib\engines\base.py", line 169, in process_response
    raise exceptions.ResourceNotFoundError
redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist
```

This is my code.

```python
redmine_parser = RedmineParser()
redmine_issue = redmine_parser.issue.get(44194)
redmine_parser.issue_journal.update(285724, notes="test")

for journal in redmine_issue.journals:
    print(journal.save(notes=""))
```

I'm able to update all other fields besides the journals. Am I doing something wrong?

**Comment by maxtepkeev** [comment]
@dreace1 Code LGTM.

A few questions:

1) Are you on Redmine >= 5.0.0 ?
2) You have `redmine_parser.issue_journal.update(285724, notes="test")` - does that one work and updates the journal with id 285724 ?

**Comment by dreace1** [comment]
1.) Unfortunately I can't check our version until monday. But then thats probably the problem.
2.) That one gives the same error.

**Comment by maxtepkeev** [comment]
Then, most likely you have Redmine <5.0.0, because that functionality is only available starting from >=5.0.0. Could you please check Redmine version on Monday and reply back. Thanks.

**Comment by dreace1** [comment]
Yes I'll do that. Thanks for the quick answer!

**Comment by dreace1** [comment]
Unfortunately we don't have >= 5.0.0. But thanks for your help!

**Comment by maxtepkeev** [comment]
I see, but you can always upgrade your Redmine and then this functionality will work.
