### ISSUE TITLE
Access to custom_fields by index name

### ISSUE THREAD

**Issue by aseques** [maxtepkeev/python-redmine#316]
Hi, just started using your library and it's excellent, but I'm stuck on this, I read the docs but can't find anything.

Basically I am trying to access to the value of a custom field called 'email_origen', I know that I can access to the field by index, but since I indexes might change over time I'd rather access to it by name.

This loop will give me the title of the field and the value
```
issues = redmine.issue.all(sort='category:desc',limit=2)
  for issue in issues:
    print(issue.custom_fields[1]) 
    print(issue.custom_fields[1].value)
```
This won't work
```
issues = redmine.issue.all(sort='category:desc',limit=2)
  for issue in issues:
    print(issue.custom_fields['email_origen']) 
```
It's giving me an object that on printing shows as: 

> <redminelib.resultsets.ResourceSet object with CustomField resources>

How could I access the data in the CustomField object for 'email_origen'? 

Thanks

**Comment by maxtepkeev** [comment]
Also #215 might be helpful.

**Comment by aseques** [comment]
Thanks a lot @maxtepkeev, option 2 is what I wanted to do, couldn't find the right combination by my own though.
