### ISSUE TITLE
How to get subjects of subtasks (children)

### ISSUE THREAD

**Issue by tsengs** [maxtepkeev/python-redmine#32]
Hi there,

we updated your fix by download the zip, but we still can't get what we need. We've tried the following:

> > > issue = redmine.issue.get(105)
> > > issue.children.total_count
> > > 1
> > > issue.children.get(264)
> > > <redmine.resources.Issue #264 "五月協助輔導員舉辦助理集訓">
> > > len(list(issue.children.manager.all()))
> > > 106
> > > len(list(issue.children.manager.filter(include = 'children')))
> > > 106

we have to specify the id of the subtask to get it (in this case, it's 264). But we would like to get all of them, how do we do that? When we use manger.all like above, it delivers all the tasks, but we just want "all the subtasks". We can't find it in the documentation.

please advice, thank you.

**Comment by diaojunxian** [comment]
@tsengs I also need to get all the subtasks from a issue id, had you solved it ?
