### ISSUE TITLE
How to: Create Issue onbehalf of another user

### ISSUE THREAD

**Issue by misilot** [maxtepkeev/python-redmine#325]
Is it possible to create an issue on behalf of another user?

Looking at https://python-redmine.com/resources/issue.html, it doesn't seem like it is, but just want to make sure I'm not missing something.

Thanks!

**Comment by maxtepkeev** [comment]
Yes you can do that. It's called impersonation, see [docs](https://python-redmine.com/configuration.html#impersonation) for details.

**Comment by misilot** [comment]
Is there a way to impersonate only a specific call? For example, I want to do all my lookups, and changes as user A, but I want to go and create a ticket based on the changes made as User B (not an admin)?

**Comment by maxtepkeev** [comment]
Yes, it's called a session request and is described [here](https://python-redmine.com/advanced/request_engines.html#session).

**Comment by misilot** [comment]
Thanks!
