### ISSUE TITLE
ResourceNotFoundError: Requested resource doesn't exist

### ISSUE THREAD

**Issue by KotPet** [maxtepkeev/python-redmine#334]
Hi!
 
I stuck with creating issue with your lib. I'm sure I dont know something, if i usig get() or all() those works fine but, if I would like to create an issue no mather wich way I try  create or new, both lead to the same exeption.

here is the way i tried it
```
from redminelib import Redmine


redmine = Redmine('http://redmine.omegabyte.hu/', username='******', password='*******')

issue = redmine.issue.create(
project_id='project_id',
subject = 'subject',
description = 'foo',
estimated_hours = 4,
done_ratio = 40,
#custom_fields=[{'id': 14, 'value': ''},{'id': 4, 'value': 'Nincs'},{'id': 1, 'value': ''},{'id': 3, 'value': ''},{'id': 2, 'value': ''},{'id': 5, 'value': 'Nincs megadva'},{'id': 7, 'value': 'Egyéb'},{'id': 10, 'value': ''},{'id': 11, 'value': ''},{'id': 12, 'value': 'Nem tervezett'}]
)
```
I got those errors:
>>py new.py
Traceback (most recent call last):
  File "D:\Work\Árajánlat\new.py", line 7, in <module>
    issue = redmine.issue.create(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kotel\AppData\Local\Programs\Python\Python312\Lib\site-packages\redminelib\managers\base.py", line 187, in create
    response = self.redmine.engine.request(self.resource_class.http_method_create, url, data=request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kotel\AppData\Local\Programs\Python\Python312\Lib\site-packages\redminelib\engines\base.py", line 83, in request
    return self.process_response(self.session.request(method, url, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kotel\AppData\Local\Programs\Python\Python312\Lib\site-packages\redminelib\engines\base.py", line 169, in process_response       
    raise exceptions.ResourceNotFoundError
redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist

Does anyone have some suggestion how can I fix this? 

Thanks in advance

Peter

**Comment by maxtepkeev** [comment]
Hi @KotPet 

```redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist```

raises when Redmine returns 404 error, and 404 error can happen either if you don't have permission to create issues or when you supply parameters which don't make sense for Redmine, i.e. non-existent `project_id`, so be sure to check those 2 things.

**Comment by KotPet** [comment]
Hi @maxtepkeev

The problem was the non existing project_id. I was thinking of completely different things I hadn't even thought of that. 
everything works fine now, thanks for the help!
