### ISSUE TITLE
[Question] Efficient way of retrieving the top-level parent of an issue.

### ISSUE THREAD

**Issue by OctoOctoPy** [maxtepkeev/python-redmine#341]
Hello,

I have a similar question to issue #213 .

I am trying to access an attribute of a top-level parent of an issue. My code to retrieve the top-level issue looks something like this:

```
# issue is a resource.Issue object 
while issue:
    parent = getattr(issue, "parent", None)
    if parent:
        issue = redmine.issue.get(parent.id) # redmine is a configured Redmine object
    else:
        break 
```

I wanted to ask for some expertise on whether or not there is a more efficient way of retrieving the top-level issue. Especially when doing this for a number of issues, the amount of requests start to pile up and running the code takes a significant amount of time.

An alternative would be to create a ResourceSet by calling `all_issues = redmine.issue.all()` and then accessing the parent through the `all_issues.get(parent_id)` method in the loop. But I am uncertain if this is more efficient if there is a large amount of issues.

I would be grateful for any insight or idea provided on how to tackle this problem.

**Comment by maxtepkeev** [comment]
Hi @OctoOctoPy 

If you only need issues that have a parent you can grab them using `parent_id=*&` filter and on the opposite `parent_id=!*&` will give you issues without parent_id.

For example:

```python
issues = redmine.issue.filter(parent_id='*&')
```

`issues` will contain only issues that have a parent. You can add more filters if needed, like `project_id` etc.

Then you will need to grab the actual parent ids:

```python
parent_ids = [issue.parent.id for issue in issues]
```

And finally do a filter query to grab the details of the parents:

```python
parent_issues = redmine.issue.filter(issue_id=','.join(parent_ids))
```

Then you can iterate as usual.

I didn't test the code above, but it should work if only I didn't make a typo somewhere, but you should get the idea of how this can be done.

Hope that helps.

**Comment by OctoOctoPy** [comment]
@maxtepkeev 

First of all thanks for the help.

But I am not looking for every issue with a parent but rather the highest parent in a hierarchy of child parent relationships. For example many issues have a structure like the following:

`Issue 3 is parent of Issue 2 is parent of Issue 1` (Sometimes the hierarchy might go deeper than this)

Then when dealing with Issue 1 I have to get some information out of Issue 3. (In our case we have some information stored in a custom field and for some analysis I always need the information of the top most parent)

I have to do this for a lot of issues and doing it the way I have done in the post above is pretty time consuming.

I thought maybe I was overlooking a cleaner way of doing this and wanted to ask for some advice.

**Comment by maxtepkeev** [comment]
@OctoOctoPy 

I see, well, doing http request for every issue is definitely extremely time consuming, but there's no perfect solution for your problem using API.

I would still proceed with the way I described above:

1) Get all issues that have a parent in one request using filter() and iterate over them to create a issue_id->parent_id lookup dict.
2) Now get all issues without parent by using another fiilter() and put them in another issue_id->custom_fields dict
3) Now get all issues no matter whether they have a parent or not and iterate over them like you're currently doing and use the dict from step 1 to get the top issue parent_id by current issue parent_id, now when you'll find that parent is not in that dict, that means that you found your highest parent and you should get the custom fields from the dict from step 2.

It will be the fastest possible way I know, the only problem you might have is lack of memory if you have thousands of issues, to solve this problem you can use a project_id filter for example to work with issues project by project etc, also try to release memory as soon as you can by calling `del var` and `gc.collect()` afterwards.

**Comment by OctoOctoPy** [comment]
@maxtepkeev 

Thank you so much for your input! I will try the idea out and see whether or not this works for my case.

Marking this as completed as my question was answered.
