### ISSUE TITLE
Behavior when calling time_entry.filter(project_id) on a project without time tracking module

### ISSUE THREAD

**Issue by OctoOctoPy** [maxtepkeev/python-redmine#342]
Hey,

I have a question concerning the behavior when calling project_time_entries = redmine.time_entry.filter(project_id=my_project_id) where my_project_id is a ~~empty project~~ project without the time tracking module.

When doing so, this returns a `<redminelib.resultsets.ResourceSet object with TimeEntry resources>` where inside of the **total_count** attribute the error string `redminelib.exceptions.ResultSetTotalCountError: Total count is unknown before evaluation` is stored.

Then when calling for example len(project_time_entries) or trying to iterate over it, like for example:
```
for time_entry in project_time_entries:
    #Do something
```
You get the `redminelib.exceptions.ResourceNotFoundError: Requested resource doesn't exist` error.

Is this expected behavior? ~~I naively expected it to be something like an "empty" ResourceSet  which behaves similar to an empty list.~~
EDIT: It probably is, as the time_entry.json does not exist. But how do you effectively check for this case?

### How to replicate:

1. Create a completely empty/bare minimum Redmine project. (In my case it just had an empty project description and nothing else) 
EDIT: The Time Tracking module is deactivated

3. Configure the Redmine object.

4.  Call redmine.time_entry.filter(project_id = project_id_of_empty_project)

**Comment by maxtepkeev** [comment]
Hi @OctoOctoPy 

As you already found out you only get this behaviour when the time entry module isn't enabled (and it's disabled by default unless you enable it in the project settings).

You can get the current project enabled modules by using `include=enabled_modules` param (Redmine >=2.6.0 only), i.e.

```python
project = redmine.project.get('my_project_id', include=['enabled_modules'])
print(project.enabled_modules)
```

It's there in the docs: https://python-redmine.com/resources/project.html#get

**Comment by OctoOctoPy** [comment]
@maxtepkeev 

Thank you for your answer. This helps a lot.

Closing this as problem/question was solved.
