### ISSUE TITLE
project.issues does not return all issues

### ISSUE THREAD

**Issue by idokasher** [maxtepkeev/python-redmine#45]
Hi,

Using Redmine 2.4.2.stable and latest python-redmine, when trying to retrieve all the issues using the following code:

project = redmine.project.get("my_proj")
issues = project.issues

I get a list of 25 unique issues, repeating itself 21 times so that len(issues) = 21 \* 25.

Thanks,
Ido.

**Comment by bellefab** [comment]
I use Redmine 2.5.3 and it seems that a code like this : 

project = redmine.project.get("my_proj")
issues = project.issues

returns the set of 'open' issues in the limit of 100 elements.
As is I was using 
redmine.issue.filter(project_id="my_proj",
                                  status_id="*", limit=100)

The messages in the log files seem to say the same thing.
Is that true ?
Is it possible to update the documentation to explicit the 'project.issues' behavior ? I think it is a bit confusing without doc.

Thanks

**Comment by maxtepkeev** [comment]
Hi,

Not exactly, see:

```python
>>> len(redmine.project.get('foobar').issues)
464

>>> len(redmine.issue.filter(project_id='foobar'))
464

>>> len(redmine.issue.filter(project_id='foobar', status_id='open'))
464

>>> len(redmine.issue.filter(project_id='foobar', status_id='closed'))
1243

>>> len(redmine.issue.filter(project_id='foobar', status_id='*'))
1707
```

So yes, the default behaviour is to return all open issues, absolutely no limiting comes into play unless you ask for it via object slicing syntax, i.e.:

```python
>>> len(redmine.project.get('foobar').issues[:105])
105
```

**Comment by bellefab** [comment]
Humm ... ok, I see.

My problem was that when I used
 
```python
>>> redmine.project.get('foobar').issues
```

I though I will get the whole set of issues but I get only the 'open' ones.
That is why I think a comment in the documentation would be helpful.

Anyway, thanks for the quick answer.
And thanks for python-redmine  :)

**Comment by maxtepkeev** [comment]
Returning only open issues is the default behaviour of Redmine API itself, but I can add a note in the documentation of course.
