### ISSUE TITLE
Unicode error when trying to acces resource.url

### ISSUE THREAD

**Issue by ynnk** [maxtepkeev/python-redmine#46]
Resource let's say 'wiki_pages fails' to return url property  when wiki.title contains french accents.
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 6: ordinal not in range(128)
- wiki.query_one is utf8 encoded
- wiki.title is unicode encoded 

ex:
## '{0}'.format(u"Une suite de caractères en français")

UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-112-3190c2025fda> in <module>()
----> 1 '{0}'.format(u"Une suite de caractères en français")

patch in my version using

```
@property
def internal_id(self):
    return self.title.encode('utf8')
```

but query_one could also be unicode.

**Comment by Boldie** [comment]
I have version 1.4.0 installed and I still have a similar bug when doing the following line (the string was loaded from another redmine installation via get before):

    rmTo.wiki_page.create(text= 'h1. test', project_id= 'project', title=u'Kompatibilit\xe4t')

I got this error:

    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/redmine/managers.py", line 172, in create
        url = '{0}{1}'.format(self.redmine.url, formatter.format(self.resource_class.query_create, **fields))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 31: ordinal not in range(128)

**Comment by maxtepkeev** [comment]
Actually it's not a similar issue, can you please open a separate issue for that. I'll have a look at it at the weekends.
