### ISSUE TITLE
allow "exporting" data from redmine

### ISSUE THREAD

**Issue by alozanoff-planisys** [maxtepkeev/python-redmine#58]
Hi,

I want to export a wiki as html instead of redmine wiki format, basically just need to request the wiki page with .html and return it raw instead of decoded json and it works, i looked at the code a little and it seems it would need some tweaks across to be able to do this. 

I will look into it myself but let me know if you think you can implement this easily so i don't waste too much time.

Thanks!

**Comment by dlmueller** [comment]
Note that http://pandoc.org/ might convert textile-markup to HTML:

> Pandoc can convert documents in ..., textile, ... HTML formats

**Comment by maxtepkeev** [comment]
@dlmueller Thanks for the info, but I don't think we'll need this one because Redmine provides export functionality by itself, we just need to implement it in python-redmine, but unfortunately I don't have time to do this right now.

**Comment by maxtepkeev** [comment]
Implemented in 897bcc4d1850fbe9280181557b39d08cbfefc9cd and will be available in v2.0.0.
