### ISSUE TITLE
Option to fail silently when resource optional but valid attr is not set

### ISSUE THREAD

**Issue by andreiavram** [maxtepkeev/python-redmine#6]
Currently, if trying to access resource.attr when the attr is not set on the resource will raise an exception. 

This is useful when trying to access an invalid attribute for a given resource, like "issue.date_due" instead of "issue.due_date". But this exception is also thrown up when the given attr is not set on the resource, even though it is valid for the given resource (for example, if due date is not set, issue.due_date will raise an exception.

One could always wrap code in try catch statements, but this might be impractical, especially in contexts when this is not as easy to do (for example, in django template code)

**Comment by aman1792** [comment]
It turned out very useful.
