### ISSUE TITLE
Support for redmine-git-hosting?

### ISSUE THREAD

**Issue by saz** [maxtepkeev/python-redmine#67]
Hey,

we're running Redmine with the redmine-git-hosting plugin.
I need to access the public keys of a user or all public keys for all users in a project.

Any chance for adding support for this?

**Comment by maxtepkeev** [comment]
Hi, any news on this ? Or can this be closed ?

**Comment by saz** [comment]
Sorry. Yes, I've got some news.

Although redmine_git_hosting 1.0.0 is in beta right now, I think this release will contain the required API endpoints. If you're able to confirm this, I'm able to create a PR, which should add support for it.

https://jbox-web.github.io/redmine_git_hosting/releases-notes/release-1.0.0.html

**Comment by maxtepkeev** [comment]
Cool, from their changelog it looks like that is exactly what we need. If you have time to create a PR, go for it.

**Comment by maxtepkeev** [comment]
It turns out they are injecting all the info through standard API endpoints so we don't need to do anything on our side. Closing this issue.
