### ISSUE TITLE
issue.due_date

### ISSUE THREAD

**Issue by ds485** [maxtepkeev/python-redmine#77]
Hi,

``` python
import datetime
...
issue.due_date = datetime.date(2014, 2, 1)
...
issue.save()
```

this is creating a new issue but the due_date is not set? bug or misuse?

**Comment by maxtepkeev** [comment]
Hi,

Works here using Redmine 2.5.2.stable:

```python
>>> issue = redmine.issue.new()
>>> issue.subject = 'foo'
>>> issue.project_id = 'test_project'
>>> issue.due_date = datetime.date(2015, 12, 23)
>>> issue.save()
True
>>> issue.id
3
>>> redmine.issue.get(3).due_date
datetime.date(2015, 12, 23)
```

Can you try to run the same code but instead of datetime use a string like '2015-12-23' and see if that works. Also what Redmine version are you using ?

**Comment by ds485** [comment]
Hi,
stupid me. The method was also creating sub issues with no due date... sry
