### ISSUE TITLE
Filtering issue on subject

### ISSUE THREAD

**Issue by ckidder** [maxtepkeev/python-redmine#79]
I've spent a few days trying to figure out how to filter on an issue subject that begins with or contains a string.

Let's say I have a project which we get:

`pca = redmine.project.get('PCA')`

Now I want to search for an issue that has 'foo' in the subject.  I try:

`pca.issues.filter(subject='foo*')`

and it says subject is not an acceptable filter.
Right now I'm pulling down all the issues and locally sorting through them.  It takes a long time to download all the issues.

**Comment by maxtepkeev** [comment]
Hi,

There is a list of available filter operators in Redmine's [source code](http://www.redmine.org/projects/redmine/repository/entry/trunk/app/models/query.rb#L174). I believe you can use something like this:

```python
issues = redmine.issue.filter(project_id='PCA', subject='~foo')
```

where `redmine` is a configured redmine instance. That will give you all issues of a `PCA` project which subject contains a `foo` string.

I know it's not very intuitive to use and it's not documented anywhere, but this should work and this is in my TODO list to document all this filters and to create a wrapper to make them more intuitive to use.

**Comment by ckidder** [comment]
Thank you very much.
