### ISSUE TITLE
Use pyredmine from a web2py project

### ISSUE THREAD

**Issue by sbourgeois1** [maxtepkeev/python-redmine#83]
At first, I am not an IT system expert, and I'd like to thank the authors for those great developments. I have just imported Redmine (release 2.6.1) and pyredmine.
Now, I 'm trying to integrate redmine with a project I'm developping with web2py, and I am facing problems when updating or adding items (such as projects) in the redmine db with pyredmine.

In the redmine db, the username used is declared as admin.
Furthermore, I have flagged the 'Enable REST web service' 

Thanks in advance for any suggestion.

Here is the piece of code I use for testing in a web2py controller file.

def tst_read_from_redmine(): # works as expected
    from redmine import Redmine
    myredmine = Redmine('http://localhost:3000',username='my_mail', password='my_secret_pw', version='2.6.1')
    myproject = myredmine.projects[1] # if I use myredmine.project.get(1), I get an error...
    mydico = myproject.__dict__
    return dict (mydico = mydico)

def tst_update_to_redmine(): # error message : 'Redmine' object has no attribute 'project'
    from redmine import Redmine
    myredmine = Redmine('http://localhost:3000', username='my_mail', password='my_secret_pw', version='2.6.1')
    my_return = myredmine.project.update(1, name='my new name')
    return dict (my_return = my_return)

def tst_create_to_redmine():  # error message : 'Redmine' object has no attribute 'project'
    from redmine import Redmine
    myredmine = Redmine('http://localhost:3000', username='my_mail', password='my_secret_pw', version='2.6.1')
    my_project = myredmine.project.new()
    mydico = my_project.__dict__
    return dict (mydico = mydico)

**Comment by sbourgeois1** [comment]
NB: read my_project.__dict__ (double underscore)

**Comment by maxtepkeev** [comment]
Hi,

Short answer: you installed the wrong library, do:

```
pip uninstall pyredmine
pip install python-redmine
```

Long answer: from the description of your problem it looks like you installed the wrong library, called [pyredmine](https://pypi.python.org/pypi/pyredmine) which is not updated since the beginning of 2013. The right library is called [python-redmine](http://python-redmine.readthedocs.org) and this is what you should use to work with Redmine from Python.

**Comment by sbourgeois1** [comment]
Thanks for your answer. I'll try and keep you informed!
Très cordialement,Serge Bourgeois
Mob: +32 477 33 10 11
Mail: serge.bourgeois@yahoo.fr
 
      De : Max Tepkeev <notifications@github.com>
 À : maxtepkeev/python-redmine <python-redmine@noreply.github.com> 
Cc : sbourgeois1 <serge.bourgeois@yahoo.fr> 
 Envoyé le : Mercredi 25 février 2015 15h30
 Objet : Re: [python-redmine] Use pyredmine from a web2py project (#83)
   
Hi,Short answer: you installed the wrong library, do:pip uninstall pyredmine
pip install python-redmine
Long answer: from the description of your problem it looks like you installed the wrong library, called pyredmine which is not updated since the beginning of 2013. The right library is called python-redmine and this is what you should use to work with Redmine from Python.—

**Comment by sbourgeois1** [comment]
Yes, pyton-redmine works now very well ! Thanks very much. 
By the way, I faced a few small issues that I could solve by changing instructions like:
from . import some_module
by 
import some_module
Serge
