### ISSUE TITLE
Support of Redmine CRM Checklists plugin

### ISSUE THREAD

**Issue by Orsox** [maxtepkeev/python-redmine#84]
It would be nice to add a redmine crm plugin checklist to a ticket by phyton redmine

**Comment by maxtepkeev** [comment]
Hi,

Thanks for the feature request.

I'll put that on my TODO list, though I can't tell you the exact ETA for it.

**Comment by tobiasvdk** [comment]
It would be really nice to have this feature.

**Comment by maxtepkeev** [comment]
Will be available in python-redmine v2 which should be released at March.
