### ISSUE TITLE
upload and description in the issue

### ISSUE THREAD

**Issue by mettbest** [maxtepkeev/python-redmine#87]
Hi,

Thanks for the great tool.
I have a small problem: I cannot display the images in the description of attached images to a issue.

In oder words calling e.g. this:
issue = redmine.issue.create(project_id='title', subject='subject', tracker_id=3, description='try to visualize !data.png!', status_id=3, done_ratio=100, assigned_to_id=8, uploads=[{path : /path/to/data.png, filename: data.png}]

the data.png is not displayed in the issue. The attachment is correctly uploaded, in the text there is !data.png! statement but no visualization of the attachment. Any hint?!

Thanks a lot,
Best Mattia

**Comment by maxtepkeev** [comment]
Hi!

I've just tried your code and it works perfectly fine for me here. I can see the visualised image inside the description, just in case here is the code:

```python
issue = redmine.issue.create(project_id='prosto-test', subject='test2', description='try to visualize !i.jpeg!', status_id=3, uploads=[{'path': '/path/to/i.jpeg', 'filename': 'i.jpeg'}])
```

The key part here is the ``filename`` inside the uploads dictionary.

If it still doesn't work for you please let me know your exact Redmine, Python and Python-Redmine versions and what database do you use with Redmine.

**Comment by mettbest** [comment]
Hi Max,

Thanks for the quick support. I found the issue: everything was okay except the 'filename' tag, I've put 'filename': 'data' instead of 'filename': 'data.png' .

By adding the extension of the filename, everything worked great!
Thanks again!
Best

**Comment by maxtepkeev** [comment]
Cool. Glad you figured it out!
