### ISSUE TITLE
I can't create a category

### ISSUE THREAD

**Issue by kelupa** [maxtepkeev/python-redmine#88]
Hi, 
I'm trying to create a new category in a project. 
I  don't know what happening, but I've tried doing in different ways but nothing.
Copy the code:

```python

from redmine import Redmine

redmine = Redmine('http://demo.redmine.org', username='foo', password='bar')

newcategory = redmine.issue_category.create(project_id='proyectosincategoria',name='UNNOMBRE')
```
the output is:
```
Traceback (most recent call last):
  File "Q:/RYD/Python-Redmine/TestCategorias.py", line 12, in <module>
    newcategory = redmine.issue_category.create(project_id='proyectosincategoria',name='UNNOMBRE')
  File "C:\Python27\lib\site-packages\redmine\managers.py", line 180, in create
    response = self.redmine.request('post', url, data=data)
  File "C:\Python27\lib\site-packages\redmine\__init__.py", line 130, in request
    raise AuthError
AuthError: Invalid authentication details
```

but the same type of error occur if I try to get a category:

```python
from redmine import Redmine

redmine = Redmine('http://demo.redmine.org', username='foo', password='bar')

newcategory = redmine.issue_category.get(13772)
```
the output is:

```
Traceback (most recent call last):
  File "Q:/RYD/Python-Redmine/TestCategorias.py", line 16, in <module>
    newcategory = redmine.issue_category.get(13772)
  File "C:\Python27\lib\site-packages\redmine\managers.py", line 127, in get
    return self.resource_class(self, self.retrieve()[0])
  File "C:\Python27\lib\site-packages\redmine\managers.py", line 60, in retrieve
    response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
  File "C:\Python27\lib\site-packages\redmine\__init__.py", line 130, in request
    raise AuthError
AuthError: Invalid authentication details
```

I feel that it is a silly error in my code, but I can't find it.

Thank in advance.

**Comment by maxtepkeev** [comment]
Hi!

The error you're getting is AuthError: Invalid authentication details. Are you sure you're using the correct username and password to authenticate to the Redmine server ?

**Comment by kelupa** [comment]
Hi!
Thanks for your inmediate answer.
I use the same code with "issue" and "project" resources and it works.
For example:
```python
from redmine import Redmine

redmine = Redmine('http://demo.redmine.org', username='foo', password='bar')

workissue = redmine.issue.get(anIssueId)

print workissue.description

newcategory = redmine.issue_category.get(13772)
```
and the issue's description is printed. But I have problem with the "issue_category".

**Comment by maxtepkeev** [comment]
Yes, it works with issue and project resources because Redmine doesn't require a proper authentication to use this resources on demo server (demo.redmine.org). All the other resources require valid username and password, so you have to register at demo.redmine.org and use your username and password in all requests.

**Comment by kelupa** [comment]
You're right.
When I write:
```
http://demo.redmine.org/issue_categories/13772.json
```
t request the username and password. But there is a problem with the demo because I tried with a valid username and password but it was impossible to get in. I did the same with other instance of redmine and it works.
Looks like more a problem on demo server... Isn't it?

Thank you very much.

**Comment by maxtepkeev** [comment]
Glad you figured it out.

It's very possible that demo.redmine.org has some limitations, like access issues etc. I don't know for sure because I'm in no way not connected to the redmine.org. But if you're looking for some public demo server with full access I can recommend you the demo.redminecrm.com.
