### ISSUE TITLE
Extract All Issues Into A CSV for Analytics

### ISSUE THREAD

**Issue by dledgerton** [maxtepkeev/python-redmine#94]
I recently became a manager of a team that is using Redmine to capture data on new project requests and support issues.  I'm looking to create an executive dashboard for myself using Python and/or Excel to show the data from within our Redmine instance.  I've downloaded your library and have success in connecting to our hosted Redmine instance but I can't seem to create a CSV using your library.  Do you have some sample code or examples I can use to create a CSV file from the Redmine instance?  What I'm trying to avoid is logging into the instance and going to the issues page and pressing the CSV button to download the file.  Thank you very much in advance.

**Comment by maxtepkeev** [comment]
Hi David,

Unfortunately there isn't any export functionality available in Python-Redmine right now, but there is already a feature request for that (see issue #58).

But you can easily implement it yourself, Python-Redmine gives you all the available data, so you just have to implement a csv writer to save this data into a file, I can give you a quick example how this could look like:

```python
import csv
import redmine

rm = redmine.Redmine('https://your-redmine-server', username='user', password='pass')

project = rm.project.get('project_identifier')

with open('/absolute/path/to/your/file/{0}.csv'.format(project.identifier), 'wb') as csvfile:
    writer = csv.writer(csvfile)

    for issue in project.issues:
        writer.writerow([
            issue.id,
            issue.subject.encode('utf-8'),
            issue.description.encode('utf-8'),
            issue.status.id
            # other issue attributes if needed, use
            # dir(issue) to get all available attrs
        ])
```

**Comment by dledgerton** [comment]
Hi.  

Thank you so much for  your help.  I'm still new to writing Python but I enjoy it very much.

Here is what I ended up with and it works perfectly.  I had to find some code to help with recognizing if the object had an attribute I wanted but after that my little extraction script works perfectly:

from redmine import Redmine
import settings

redmine = Redmine(settings.SITE,
                  username=settings.USERNAME,
                  password=settings.PASSWORD,
                  requests={'verify':False}
                  )

# Open file for writing
    
f = open('c:/users/a62478/Desktop/data.txt','w',encoding='utf-8')
    
# Create the header row for the text file
    
header = 'ISSUE_ID|SUBJECT|DESCRIPTION|AUTHOR|CREATED_ON|ASSIGNED_TO|ESTIMATED_HOURS|PRIORITY|START_DATE|STATUS|TRACKER|UPDATED_ON'
    
f.write(header)
f.write('\n')

#Add all project information to the text file

RedmineProjects = ['project1','project2','project3']

for project in RedmineProjects:

    selected_project = redmine.project.get(project)

    for issue in selected_project.issues:
    
    # if the object has the attribute print it
    
        if hasattr(issue, 'id'):
            line = str(issue.id)
        else:
            line = 'NA'
    
        if hasattr(issue, 'subject'):
            line = line + '|' + str(issue.subject)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'description'):
            line = line + '|' + str(issue.description).replace('\n', ' ').replace('\r', '')
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'author'):
            line = line + '|' + str(issue.author)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'created_on'):
            line = line + '|' + str(issue.created_on)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'assigned_to'):
            line = line + '|' + str(issue.assigned_to)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'estimated_hours'):
            line = line + '|' + str(issue.estimated_hours)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'priority'):
            line = line + '|' + str(issue.priority)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'start_date'):
            line = line + '|' + str(issue.start_date)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'status'):
            line = line + '|' + str(issue.status)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'tracker'):
            line = line + '|' + str(issue.tracker)
        else:
            line = line + '|' + 'NA'
    
        if hasattr(issue, 'updated_on'):
            line = line + '|' + str(issue.updated_on)
        else:
            line = line + '|' + 'NA'
    
        f.write(line + '\n')
    
f.close()

Thank you so much again.

David

**Comment by dledgerton** [comment]
I got it working.  Thank you so much for your help.

David

**Comment by maxtepkeev** [comment]
Cool!

**Comment by giladste** [comment]
Now that the export function is implemented, I would like to ask how can I export *ALL* columns, including custom fields. The following code exports only the mandatory predefined fields, neglecting all my custom fields which are not listed. 
When exporting using the web-UI, it is possible to check the box on "All columns".
I did not see any help on the subject over at https://python-redmine.com/resources/custom_field.html 
Would love some help on how to apply the check box using the redmine-python project.
Thanks
