### ISSUE TITLE
Keep getting 'AuthError: Invalid authentication details'

### ISSUE THREAD

**Issue by ivokoga** [maxtepkeev/python-redmine#95]
Hi,

I don't know if I am making sth wrong at all, but I tried for a while connection with:
Redmine('Redmine('https_url', username, password)
Redmine('Redmine('https_url', key)

with and without requests={'verify': False}

What other options do I have in order to succeed connecting?

Here is my output error:

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
---------------------------------------------------------------------------
AuthError                                 Traceback (most recent call last)
<ipython-input-18-02f0e8305b7b> in <module>()
----> 1 project = connection.project.get('pivo')

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/managers.pyc in get(self, resource_id, **params)
    125         self.params = self.prepare_params(params)
    126         self.container = self.resource_class.container_one
--> 127         return self.resource_class(self, self.retrieve()[0])
    128 
    129     def all(self, **params):

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/managers.pyc in retrieve(self, **params)
     58         while True:
     59             try:
---> 60                 response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
     61             except ResourceNotFoundError:
     62                 # This is the only place we're checking for ResourceRequirementsError

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/__init__.pyc in request(self, method, url, headers, params, data, raw_response)
    128                     raise JSONDecodeError
    129         elif response.status_code == 401:
--> 130             raise AuthError
    131         elif response.status_code == 403:
    132             raise ForbiddenError

AuthError: Invalid authentication details

**Comment by maxtepkeev** [comment]
Hi,

The warning that you get, i.e. ``InsecureRequestWarning`` comes from the fact that you're using the ``requests={'verify': False}``. I believe you're using this because you have a self-signed certificate on your Redmine server, if you want to disable this warning you can find how to do that [here](https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning).

As to the ``AuthError``, well, it means what it means, you're either providing invalid API key or invalid username/password or a user which you are trying to use to access Redmine doesn't have needed privileges or you didn't turn on REST API in Redmine.

Also, your code seems very strange, I mean what is this:

```
Redmine('Redmine('https_url', username, password)
Redmine('Redmine('https_url', key)
```

It should look like this:

```python

from redmine import Redmine

conn = Redmine('https://your_url', username='user', password='pass', requests={'verify': False})
project = conn.project.get('pivo')
print list(project)
```

**Comment by ivokoga** [comment]
Hi,

Sorry, It was my fault. I mean:
Redmine(https_url, username, password) and Redmine(https_url, key).

I already tried your suggestion and keep getting "Auth error: AuthError: Invalid authentication details "
My piece of code:

```python
from redmine import Redmine

conn = Redmine('https://url', username='****', password='****', requests={'verify': False})
project = conn.project.get('pivo')
print list(project)
```

output:
=============
 %run "/Users/ivokoga/Documents/projetos-python/usuario_redmine/cptecsvnusers.py"
/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised.
---------------------------------------------------------------------------
AuthError                                 Traceback (most recent call last)
/Users/ivokoga/Documents/projetos-python/usuario_redmine/cptecsvnusers.py in <module>()
      8 
      9 conn = Redmine('https://projetos.cptec.inpe.br/', username='*****', password='******', requests={'verify': False})
---> 10 project = conn.project.get('pivo')
     11 print list(project)

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/managers.pyc in get(self, resource_id, **params)
    125         self.params = self.prepare_params(params)
    126         self.container = self.resource_class.container_one
--> 127         return self.resource_class(self, self.retrieve()[0])
    128 
    129     def all(self, **params):

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/managers.pyc in retrieve(self, **params)
     58         while True:
     59             try:
---> 60                 response = self.redmine.request('get', self.url, params=dict(self.params, limit=limit, offset=offset))
     61             except ResourceNotFoundError:
     62                 # This is the only place we're checking for ResourceRequirementsError

/Users/ivokoga/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/redmine/__init__.pyc in request(self, method, url, headers, params, data, raw_response)
    128                     raise JSONDecodeError
    129         elif response.status_code == 401:
--> 130             raise AuthError
    131         elif response.status_code == 403:
    132             raise ForbiddenError

AuthError: Invalid authentication details 



=====
As I can log in with the same username and password in my company's redmine website, I'm confused about where to find the error.

Thanks for your help.

**Comment by maxtepkeev** [comment]
Are you able to login with your username/password to the following address: https://projetos.cptec.inpe.br/projects/pivo.json ?

**Comment by ivokoga** [comment]
Hi maxtepkeev,

I realized that I had authentication problems because REST API was not enabled in redmine. It is now enabled and then I could make a key authentication successfully. 

Thank you very much! :+1:

**Comment by maxtepkeev** [comment]
Glad you figured it out!
