### ISSUE TITLE
redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist

### ISSUE THREAD

**Issue by HRKpython** [maxtepkeev/python-redmine#96]
I am trying to post a new issue to our BUGtracker.  For an existing BUG, if I get the issue using below commands this is the output
issue = redmine.issue.get(523)
print issue.__dict__

data = {'_update_readonly': ('id', 'created_on', 'updated_on', 'author', 'user', 'project', 'issue', 'spent_hours',
                             'relations', 'time_entries', 'children','attachments', 'relations', 'changesets',
                             'journals', 'watchers'), '_relations_name': 'issue',
        '_attributes': {u'status': {u'id': 1, u'name': u'New'}, u'project': {u'id': 1, u'name': u'SStestPipe'},
                        'attachments': None, 'time_entries': None, 'journals': None, 'children': None,
                        u'custom_fields': [{u'id': 1, u'value': u'Low', u'name': u'Urgency'}, {u'id': 2, u'value': u'Exception', u'name': u'Severity'}, {u'id': 7, u'value': u'This is a test. ', u'name': u'Steps to Reproduce'}, {u'id': 5, u'value': u'', u'name': u'SAP Code'}, {u'id': 6, u'value': u'6.6', u'name': u'Version'}, {u'id': 8, u'value': u'', u'name': u'Release Notes'}, {u'id': 14, u'value': u'', u'name': u'Customer'}],
                        u'description': u'this is a test',
                        u'category': {u'id': 2, u'name': u'TM'}, 'changesets': None, 'watchers': None,
                        u'author': {u'id': 36, u'name': u'Joe Engineer'}, u'created_on': u'2015-06-23T20:30:21Z', 'relations': None, u'id': 523,
                        u'priority': {u'id': 1, u'name': u'Low Priority'}, u'tracker': {u'id': 1, u'name': u'Bug'},
                        u'assigned_to': {u'id': 41, u'name': u'Scrum Masters'},
                        u'updated_on': u'2015-06-23T20:30:21Z',
                        u'subject': u'For This is a test',
                        u'start_date': u'2015-06-23', u'done_ratio': 0},
        '_create_readonly': ('id', 'created_on', 'updated_on', 'author', 'user', 'project', 'issue', 'spent_hours', 'relations', 'time_entries', 'children', 'attachments', 'relations', 'changesets', 'journals', 'watchers'),
                                                               '_changes': {}}

however, when I want to post a new issue using below command I get the Requested resource does not exist:

issue = redmine.issue.create(project_id = 'SStestPipe',
                             project =  {'id': 1, 'name': 'SStestPipe'},
                             attachments = None, time_entries= None, journals= None, children= None,
                             subject = 'This is a test',
                             description = 'foo',
                             status = [{'id':1, 'name':'New'}],
                             priority = [{'id':1, 'name':'Low Priority'}],
                             category = [{'id':2, 'name':'TM'}],                                
                             custom_fields = [{'id':1,'value':'Low','name':'Urgency'},
                                              {'id':2,'value':'Exception','name':'Severity'},
                                              {'id':6,'value':'6.6','name':'Version'},
                                              {'id':7,'value':'This is a test','name':'Steps to Reproduce'},
                                              {'id':5,'value':'','name':'SAP Code'},
                                              {'id':8,'value':'','name':'Release Notes'},
                                              {'id':14,'value':'','name':'Customer'}
                                             ])
When I check our Bug Tracker, I filled up all the Required fields. Could you please help me on this? I also try commented out some not required fields like attachements, SAP Code, Release Notes, Customer, but it did not help.

**Comment by maxtepkeev** [comment]
Have you checked [this](http://python-redmine.readthedocs.org/faq.html#create-update-delete-resource-operations-doesn-t-work) out ? Looks very similar to your problem

**Comment by HRKpython** [comment]
[Your Redmine server is probably using https as the primary protocol and you’re trying to connect to it under http protocol. Please use the https protocol and it should work.]
You are right our Redmine server using https [https://btm-.....]. I used this to generate redmine object 
redmine = Redmine('https://btm-/', key='0990636d03', requests={'verify': False}) How should I try to connect to it with https protocol?

**Comment by maxtepkeev** [comment]
It seems that you're already using https by specifying https:// scheme in https://btm-/

After looking at your code that you're using to create a new issue I see that it's not correct, can you try to create an issue with this simple code:

```python
issue = redmine.issue.create(project_id='SStestPipe', subject='SStestPipe', description='foo')
```

If that doesn't work also, make sure that you have a project with ID SStestPipe, because project should already exist before one can create an issue inside it.

**Comment by HRKpython** [comment]
1 - I am sure about the project_id since when I used the get, I was able to see the exact name
2- I cannot put a simple input as yours because the form has some required fields that I need to put in as an input. If I only put those three, I got this error: redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist

**Comment by maxtepkeev** [comment]
Name of the project != identifier of the project, can you try with:

```python
issue = redmine.issue.create(project_id=1, subject='SStestPipe', description='foo')
```

I change SStestPipe to 1. I understand about other required fields, but you should get a ValidationError saying that field X is required, field Y is required etc if that was the case

**Comment by HRKpython** [comment]
Now this is the error:   
File "post.py", line 22, in <module>
    issue = redmine.issue.create(project_id = 1, subject = 'This is a test', description = 'foo')
  File "C:\Python27\lib\site-packages\redmine\managers.py", line 185, in create
    resource = self.to_resource(response[self.container])
KeyError: 'issue'

**Comment by maxtepkeev** [comment]
Very strange, tested here and it worked for me, can you go to "C:\Python27\lib\site-packages\redmine\managers.py" and add ``print response`` to line 183 to see what's inside ``response`` variable, also what version of Redmine do you use.

**Comment by HRKpython** [comment]
now this is the error as you said:
    raise ValidationError(to_string(', '.join(e if is_string(e) else ': '.join(e) for e in errors)))
redmine.exceptions.ValidationError: Steps to Reproduce can't be blank, Version can't be blank, Category can't be blank

**Comment by HRKpython** [comment]
issue = redmine.issue.create(project_id=1, subject='This is a test', description='foo', 
							category = [{'id':2, 'name':'TopMeret'}],                                
                            custom_fields = [{'id':6,'value':'6.6','name':'Version'},
                                               {'id':7,'value':'This is a test','name':'Steps to Reproduce'}])

This is the error now: redmine.exceptions.ValidationError: Category can't be blank

It is not blank!!!!!

**Comment by maxtepkeev** [comment]
Redmine has a concept of project id and identifier, id is an integer while identifier is a string, you can get identifier if you do:

```python
project = redmine.project.get(1)
print project.identifier
```

identifier or id can be used to create issues but name of the project can't.

Now you can add your other fields as described in the [docs](http://python-redmine.readthedocs.org/resources/issue.html#create).

You're getting the Category can't be blank because you're doing it wrong, have a look at the link to the docs, it should be passed as category_id (integer), like this:

issue = redmine.issue.create(project_id=1, subject='This is a test', description='foo', category_id=2)

All the other fields and how they should look like are also described in the docs.

**Comment by HRKpython** [comment]
Dude, Thank you so much.  I read the documentation but honestly it was not clear that I need to put category_id= 2,I tried category_id={'id':2,name:'....'} but it seems it was wrong. Finally I was able to post.

**Comment by maxtepkeev** [comment]
You're welcome.

There is actually an example in the documentation with all the params and how they should look like, but it's missing category_id for some reason. My bad. I'll add it to make it more clear.
