### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by Simon3452** [maxtepkeev/python-redmine#97]
Good day, 

I am using python 2.7 with python redmine 1.1.2. I have tried different ways to upload file to redmine without success. My OS is Windows 7.

project = connection.issue.create(project_id=project_id, description = description_str,
   subject= parameters.getSubject(), custom_fields=[{'id':6 , 'value': '12- Under Service'}, {'id':50 ,'value':'Software'}],  uploads=[{'path' : 'C:\Work\ChiliToolWizard\LogRam_Flush.log'}])

where connection is,
connection = Redmine(LOGBOOK_URL, username = parameters.getUsername(), password = parameters.getPassword(), version='1.1.2')

I tried using update and new method to upload files without success. I also tried to upload method with passing a token to my create method without success as well.

Using the version keyword when I configure my Redmine object I get the following error:

File upload isn't supported on specified Redmine version

Again I have the version 1.1.2 of python redmine. Looking on github I see this version as the latest one. How can I get a version that implement file upload. Please provide as much details as possible in order to get it.

Regards,
Simon

**Comment by maxtepkeev** [comment]
Hi,

What version of Redmine do you use ? Not python-redmine, but Redmine itself

**Comment by Simon3452** [comment]
How can I find that information?

**Comment by Simon3452** [comment]
I installed Bitnami Redmine 3.0.3 which includes Redmine... is there a path I need change or add so my application is able to find latest Redmine?

**Comment by maxtepkeev** [comment]
Ok, so there is python-redmine (latest v 1.1.2) and Redmine itself (latest v3.0.3), from what you've told it looks like you already have both of them, also I don't see any errors in your code, so it should work, though you're using windows and I don't have a windows here to test.

Can you answer several questions, please:

1) Am I understand you right, that issue got created, but file didn't upload ?
2) Did you have any errors ?
3) Are you sure your webserver have access to the file you're trying to upload ?

**Comment by Simon3452** [comment]
1- I can create issues as long as I am not uploading files.
2- If I try to upload files I get the error I mentioned in my first mail.
3- The file is local on my harddrive, I don't think the webserver can see
it.

I installed locally a Redmine 3.0.3 but not sure the webserver I want to
upload the as Redmine 3.0.3. It is might be old.

Regards

On Tue, Jun 30, 2015 at 2:16 PM, Max Tepkeev <notifications@github.com>
wrote:

> Ok, so there is python-redmine (latest v 1.1.2) and Redmine itself (latest
> v3.0.3), from what you've told it looks like you already have both of them,
> also I don't see any errors in your code, so it should work, though you're
> using windows and I don't have a windows here to test.
>
> Can you answer several questions, please:
>
> 1) Am I understand you right, that issue got created, but file didn't
> upload ?
> 2) Did you have any errors ?
> 3) Are you sure your webserver have access to the file you're trying to
> upload ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-117288928>
> .
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by maxtepkeev** [comment]
You've set version incorrectly, you should set to a version of Redmine which is 3.0.3, not to 1.1.2

**Comment by Simon3452** [comment]
Max,

I get the following error.

redmine.exceptions.ResourceNotFoundError: Requested resource doesn't exist

regards,

On Tue, Jun 30, 2015 at 4:45 PM, Max Tepkeev <notifications@github.com>
wrote:

> You've set version incorrectly, you should set to a version of Redmine
> which is 3.0.3, not to 1.1.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-117337198>
> .
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by maxtepkeev** [comment]
This can happen when you're setting issue's project_id to non-existing project

**Comment by Simon3452** [comment]
If I remove the upload keyword from the command shown in my first message
the issue will be created. Same thing with command update() and new().


On Tue, Jun 30, 2015 at 4:52 PM, Max Tepkeev <notifications@github.com>
wrote:

> This can happen when you're setting issue's project_id to non-existing
> project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-117338755>
> .
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by maxtepkeev** [comment]
Can't reproduce this issue here, can you please try to create the same issue on public redmine server demo.redmine.org, and see if it works here. Because if it does, then it looks like there is a problem with this bitnami stack and I would need to setup a virtualbox to find out what's causing this and if it doesn't then you probably doing something wrong and we will continue investigating what exactly may be causing this issue for you.

**Comment by maxtepkeev** [comment]
And also, are you able to attach a file to an issue by hand through your web browser ?

**Comment by Simon3452** [comment]
yes I can attach a file by hand through my web browser.

On Wed, Jul 1, 2015 at 10:29 AM, Max Tepkeev <notifications@github.com>
wrote:

> And also, are you able to attach a file to an issue by hand through your
> web browser ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-117694687>
> .
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by Simon3452** [comment]
I would like to understand when we are talking about Redmine, are we
talking about the one in use on the webserver because that one I don`t know
its version or I actually need one installed on my local machine which is
running the python script?

On Wed, Jul 1, 2015 at 10:29 AM, Patrice Rochefort <
patrice.rochefort@optelvision.com> wrote:

> yes I can attach a file by hand through my web browser.
>
> On Wed, Jul 1, 2015 at 10:29 AM, Max Tepkeev <notifications@github.com>
> wrote:
>
>> And also, are you able to attach a file to an issue by hand through your
>> web browser ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-117694687>
>> .
>>
>
>
>
> --
> Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
> Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
> www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
> Technologies*
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by maxtepkeev** [comment]
When we are talking about Redmine, we are talking about the one that is on the webserver, you said that you used bitnami redmine 3.0.3, I guess this is the one from [here](https://bitnami.com/stack/redmine), just to be sure you can find it's version in http://you-redmin-url/admin/info

**Comment by maxtepkeev** [comment]
Any news about the problem ? Did you try to create an issue with files on demo.redmine.org ?

**Comment by Simon3452** [comment]
Yes, I am able to create issues and upload file on demo.redmine.org. This
prove our Redmine is outdated and do not allow us to upload file. We are
thinking to create another webserver where we will upload files by other
means.

On Fri, Jul 3, 2015 at 11:09 AM, Max Tepkeev <notifications@github.com>
wrote:

> Any news about the problem ? Did you try to create an issue with files on
> demo.redmine.org ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxtepkeev/python-redmine/issues/97#issuecomment-118370750>
> .
>



-- 
Patrice RochefortGestionnaire des outils de simulation/Simulation Tool
Manager1 (418) 688-0334 #6308 - patrice.rochefort@optelvision.com
www.OptelVision.com <http://www.optelvision.com/>- *Safety Through
Technologies*

-- 


------------------------------

© This e-mail and its attachments are intended only for the individual or company to which it is addressed and may contain Optel Vision Inc. proprietary information, which is PRIVILEGED, CONFIDENTIAL, and subject to COPYRIGHT belonging to Optel Vision Inc. under applicable law. If you are not the intended recipient of this e-mail, you are hereby notified that any use, dissemination, or copying of this e-mail or the information contained in this e-mail is strictly prohibited by the sender. If you have received this transmission in error, please return the material received to the sender and delete all copies from your system.

2680 Rue du Parc Technologique, Quebec City (QC) G1P 4S6 CANADA

© Ce courriel et ses pièces jointes sont destinées seulement aux personnes ou entreprises désignées dans ce courriel et peuvent contenir des informations exclusives à Optel Vision Inc. qui sont PRIVILÉGIÉES, CONFIDENTIELLES et sous réserve de DROITS D'AUTEUR appartenant à Optel Vision Inc. en vertu des lois en vigueur. Si vous n’êtes pas le bon destinataire, vous êtes par la présente averti que toute diffusion ou copie de courriel ou des informations contenues dans celui-ci est strictement interdit par l’envoyeur. Si vous avez reçu ce message par erreur, s’il vous plait retourner les pièces jointes à l’envoyeur et supprimez les copies de votre ordinateur.

2680 Rue du Parc Technologique, Québec (QC) G1P 4S6 CANADA 


-- 
Optel Vision awarded "best company of the year” and “best high technology" 
at Fideides 2015.

Optel Vision récipiendaire des prix "meilleure entreprise de l'année” et 
"haute technologie" aux Fidéides 2015.

**Comment by maxtepkeev** [comment]
Thanks for the info, but did you check what version of Redmine you're using, you can do that going to http://you-redmin-url/admin/info using admin account.

**Comment by maxtepkeev** [comment]
Closed due to inactivity, if you still need help, let me know, and I'll reopen it.
