### ISSUE TITLE
Wiki page parent attribute feature

### ISSUE THREAD

**Issue by ddeno** [maxtepkeev/python-redmine#98]
I would like to set the parent attribute for a wiki page when I create it. It does not look like there is a way to do that based on the documentation with either the new() or create() methods. This would be useful so that you can place a wiki page where you wish. It also seems that you cannot change the parent attribute when using update() as well.

**Comment by maxtepkeev** [comment]
Hi,

Thanks for the feature request.

This is implemented in v1.2.0 which is available on PyPI as of now. You can use ``parent_title`` in ``create()``, ``new()`` and ``update()`` methods to work with parent wiki page. Docs are updated as well.

**Comment by ddeno** [comment]
Thanks Max! Tried this out and works perfectly. +1

**Comment by maxtepkeev** [comment]
Awesome. Glad I could help.
